### ISSUE TITLE
Add time series generator Forms

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1032]
# Specifications
## Context

The AntaresSimulator application provides a Time Series (TS) generator that should be ported to AntaresWeb.
This generator is very little used. It allows to generate TS from stastistic laws.

The Time Series Generateor can be found in several places (load, Hydro, Wind, Solar).

## Requirements

- See with Edgar LANE and Valentin BERTAULD to know when they can work with us.
- Time Series Generator are already available in the Themal.
- The objective is to design a separate view to generate a Time Series for a type of object (producer /
  consumer). Provide, for example, a drop-down list with load, Thermal, Hydro, Wind, Solar...
- Question: where should this form be put? See with Florian / Alexander

**Comment by laurent-laporte-pro** [comment]
See also #1130

**Comment by makdeuneuv** [comment]
It will be done on Jira ANT-1991 and ANT-1164
