### ISSUE TITLE
Generate an id for a new study import

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#105]
The study stored on the workspace should have an uid so that different studies with same name can be imported.
The uid can be stored as the folder name containing the new study or/and in the study.antares file

**Acceptance criteria**
- [x] When importing the study, the api must return the uid created for that study
- [x] Two study with same name can be imported under the same name
- [ ] ~~When reading/listing a study with no uid, one must be generated~~

**Comment by qdesmedt** [comment]
@pl-buiquang 
**Question:** est ce qu'en conséquence de cette issue pour utiliser les urls du type */studies/{study}/...* l'utilisateur devra donner l'uid ? et plus le nom de l'étude ?

On peut aussi imaginer qu'il puisse utiliser les deux.

Par exemple, suivant la liste des études ci-dessous:

- name: **study1**
  uuid: **uid1**
- name: **study2**
  uuid: **uid2**
- name: **study2**
  uuid: **uid3**

Si je requête:
-  /studies/study1: OK
-  /studies/uid1: OK
-  /studies/study2: NOT OK (2 études)
-  /studies/uid2: OK
-  /studies/uid3: OK

**Comment by pl-buiquang** [comment]
je pensais que l'utilisateur devrait renseigner l'id.
de toute façon le cas d'usage, c'est :
- (optionnel) l'utilisateur importe une étude
- l'utilisateur liste les études (donc récupere les id et les metadonnées)
- l'utilisateur lit une étude grâce à l'id

Après ça sera au client (autre service, front web) qui gerera le fait que ça sera transparent.

**Comment by qdesmedt** [comment]
@pl-buiquang 
Quand l'utilisateur copie une étude, est ce que l'étude copiée à le même nom ? (et un uuid différent)
Ou gardes t-on le fonctionnement actuel ? (l'utilisateur envoie un nouveau nom d'étude ?)

/studies/{study_uuid}/copy
VS
/studies/{study_uuid}/copy?dest=new_study_name

**Comment by pl-buiquang** [comment]
l'utilisateur doit bien fournir un nouveau nom (même si au final on pourrait effectivement s'en passer).
du coup `/studies/{study_uuid}/copy?dest=new_study_name` avec `dest` en required
