### ISSUE TITLE
Reset playlist when general configuration of MC year number changes

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1085]
# Requirements

## Context

Reset the playlist when the general configuration of the number of MC (Monte Carlo) years changes.

![Image](https://user-images.githubusercontent.com/43534797/217788802-f78ef163-2218-477f-9faa-9bf0eb7738fc.png)

## Specifications

As a user, when I change the number of MC years in the "Monte-Carlo Scenarios" view, the play list must be updated according to the number of years.

- All years must be set (checkboxes are checked)
- Set `playlist_reset` to `True`.

> **NOTE:** we need to upgrade the `GeneralManager.set_field_value` to add a new command to update the playlist when the `nb_years` field is changed.

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv, pourrait-on ajouter une copie d'écran ?

**Comment by makdeuneuv** [comment]
@laurent-laporte-pro  Celle fournie dans la description ne suffit pas ?
