### ISSUE TITLE
Add new general advanced property to manage the hydro allocation

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1091]
The new field that must be added (also in the UI) is described here :
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/def9c60a2ef06febeb7feb996425850acf632beb/docs/reference-guide/13-file-format.md#input

**Comment by makdeuneuv** [comment]
This property haven't develop on simulator and won't be because it have les importance.
