### ISSUE TITLE
Add timeseries import CSV support

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1107]
Currently, only the TSV format is supported: we want to be able to import comma-separated values.

Warning:
- French version of Excel generates CSV files using the ";" delimiter (floating point numbers could also have ","),
- The file could have a Byte Order Mark [(BOM)](https://fr.wikipedia.org/wiki/Indicateur_d%27ordre_des_octets) at the beginning of the file. This BOM should be interpreted and removed on loading.

Implementation: we can use [`csv.Sniffer](https://docs.python.org/3.8/library/csv.html#csv.Sniffer) to automatically detect the file format. It should work for TSV too.

**Comment by laurent-laporte-pro** [comment]
The following function can detect the Byte Order Mark of a file:

```python
import pathlib
import codecs
from typing import Union


def detect_bom(file_path: Union[str, pathlib.Path]) -> str:
    with open(file_path, "rb") as f:
        raw = f.read(4)
    if raw.startswith(codecs.BOM_UTF8):
        return "UTF-8"
    elif raw.startswith(codecs.BOM_UTF16_LE):
        return "UTF-16LE"
    elif raw.startswith(codecs.BOM_UTF16_BE):
        return "UTF-16BE"
    elif raw.startswith(codecs.BOM_UTF32_LE):
        return "UTF-32LE"
    elif raw.startswith(codecs.BOM_UTF32_BE):
        return "UTF-32BE"
    else:
        return ""
```

> **NOTE:** this function is NOT tested.

You can use this `detect_bom` function to use the right file encoding to open the file in texte mode:

```python
file_path = pathlib.Path(...)

bom = detect_bom(file_path)
encoding = f"{bom}-sig" if bom else "UTF-8"

with file_path.open(mode="r", encoding=encoding) as f:
    for line in f:
        print(line)
```

>**NOTE:** the "UTF-8-sig", "UTF-16BE-sig", etc. are useful to ignore the BOM at the beginning of the file.

The following code can be used to detect the CSV/TSV dialect (delimiter, etc.):

```python
import csv


with file_path.open(mode="r", encoding=encoding) as f:
    first_line = f.readline()
    dialect = csv.Sniffer().sniff(first_line)
    f.seek(0)
```

**Comment by makdeuneuv** [comment]
It will be done on Jira ANT-1588
