### ISSUE TITLE
Limit/Group api endpoints

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#111]
To make the api usage more user-friendly and, well, usable,
some endpoint should be left out of the swagger documentation (possibly for the api itself if needed/possible), letting only higher level of the json accessible and returning the whole content.
The list of these group cuts is :
- [x] layers/layers
- [x] settings/generaldata
- [x] output/XXX/about-the-study/parameters 
- [x] output/XXX/about-the-study/study
- [ ] ~~output/XXX/info(.antares-output)~~
- [x] input/areas/XXX/optimization
- [x] input/areas/XXX/ui
- [x] input/bindingconstraints/bindingconstraints
- [x] input/hydro/hydro
- [x] input/links/XXX/properties/YYY
- [x] input/load/prepro/XXX/settings
- [x] input/solar/prepro/XXX/settings
- [x] input/thermal/clusters/XXX/list
- [x] input/thermal/areas
- [x] input/wind/prepro/XXX/settings

**Comment by qdesmedt** [comment]
**Idea**: add a configuration file to the api

[swagger]

endpoints = [
    "layers/layers",
   ...
] 

If done like so, add the following conf:

server = http//localhost:8080

./server.sh --conf path_to_conf_file.ini

**Comment by pl-buiquang** [comment]
To make sur my explanation was clear,
The "group cuts" listed are not the only endpoint we wish to see in the swagger doc. All available path should be listed.
They define the paths which we do not want to see any deeper endpoint.

**Comment by qdesmedt** [comment]
Suite à une discussion entre @qdesmedt / @FrancoisJ:

* Ne faut il pas arrêter de génèrer le swagger automatiquement ?
    * Quid des enpoints "non-restfull" ? (export, etc...)
* Si l'on a ~ 40 endpoints, on peut les écrire "à la main" et être plus précis (exemple, description, ...)

**Comment by pl-buiquang** [comment]
Ne serait il pas possible d'ajouter une metadonnée dans le jsonschema pour que la génération des chemins du swagger s'arrête (ne pas construire les enfants) aux noeuds contenant cette métadonnée ?
Il faudrait effectivement en plus de la génération automatique via le jsonschema (tout ce qui est en dessous de /studies/{study_id} a priori) rajouter une génération ad hoc pour les endpoints qui n'en dépendent pas.

**Comment by qdesmedt** [comment]
**Décision:**

* On continue d'utiliser l'engine
* On utilise un metadata pour l'arrêt
* On analyse la taille du swagger

**Comment by qdesmedt** [comment]
output/XXX/info(.antares-output)
Not yet implemented see #119
