### ISSUE TITLE
Add information about which user launched a study

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1124]
Add information about which user launched a study and the used parameters.

⚠️ WARNING: this feature introduce a database breaking change (database migration).

**Comment by laurent-laporte-pro** [comment]
# Requirements

## API change:

- Add a `owner_identity` in the `JobResult` table (optional foreign key, cascade = `SET_NULL`) model to point to the `Identity` table.
- Add the `owner_identity` when the `JobResult` is created.
- Modify the `JobResultDTO` to add the `owner_name`.

## wabapp change:

- Display the `owner_name` in the task list if not empty.

# Acceptance Criteria

- [ ] The Task list should show the owner name, for instance "launched by John DOE",

> **NOTE:** old Tasks don't have owner name, so, for instance, we should have "launched" without name.

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv => rechercher s'il y a un ticket JIRA correspondant et déterminer la priorité (quelle version / milestone à affecter ?)

**Comment by laurent-laporte-pro** [comment]
Il faut absolument avoir les scripts de migration alembic

**Comment by makdeuneuv** [comment]
Comment tester ce ticket ? Manque t'il des éléments sur le front comme une colonne avec le nom de l'utilisateur qui a lancé le job sur la vue des tâches ?

**Comment by MartinBelthle** [comment]
Le front n'a pas été ajouté. Pour tester, il faut lancer des jobs (avec différents users si possible et un token aussi) puis utiliser l'API GET /jobs/job_id pour voir que l'information a été rajouté dans le json

**Comment by laurent-laporte-pro** [comment]
@MartinBelthle , Avec ta modification, nous obtenons bien le `owner_id` dans le `JobResultDTO`, mais je viens de m'apercevoir que ce n'est pas suffisant car il nous faut afficher le nom de l'utilisateur et pas seulement son ID.

On est d'accord @makdeuneuv ? Je vous propose d'ouvrir un ticket pour à la fois développer le front et améliorer le back afin d'avoir :

```json
"owner" : {
   "id": Identity.id,
   "name": Identity.name,
   "type": Identity.type
}
```

**Comment by MartinBelthle** [comment]
Effectivement on a seulement le `owner_id`. Mais avec le endpoint GET `/v1/users/{id}` en donnant le `owner_id` on récupère son `name` donc ça me semble suffisant pour le front pas besoin de toucher au back selon moi
