### ISSUE TITLE
Integration of Kirchhoff constraint generator

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1130]
The goal is to replicate what we find in Antares Simulator: Kirchoff's constraints generator. However, this system is not functioning very well...

Specifications:

- Create a form (reproduce the existing form).
- Launch the application (binary executable) `antares-kirchoff-constraints-builder` (available in Antares Simulator).
- The binding constraints are written in the corresponding folder.
- Issue: for a study defined in the form of variants, it is necessary to convert the output data from this application into commands. In the `command_extractor` module, there is a method for extracting the binding constraints. It is necessary to refactor the existing code to have a new method that only retrieves the constraints.
- Only the new binding constraints should be considered, based on the constraint IDs.

This ticket is not a priority because this functionality is no longer in use.

**Comment by laurent-laporte-pro** [comment]
This feature is not used!
