### ISSUE TITLE
Xpansion: add missing parameters in the Settings

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1166]
Two new parameters in `settings.ini` : 
- separation_parameter : float (between 0 and 1) default value 0.5
- relaxed_optimality_gap: float (>0) default value 10e-4

This two parameters should be in the parameters panel in a new section "advanced parameters" under "Version C++".
Note that the relaxed_optimality_gap already exist in the R version so it should be merged and moved to the new location.

![Image](https://user-images.githubusercontent.com/43534797/217024208-eeb8bb45-1657-4d87-b057-a320eaf66049.png)

**Comment by laurent-laporte-pro** [comment]
Traduction en français :
- `separation_parameter`: "Paramètre de séparation"
- `relaxed_optimality_gap` : "Gap d'optimalité relaxé"

**Comment by tbittar** [comment]
The unit of `Gap d'optimalité absolu` is euros (or €) and should be added to the interface as in the following screenshot. I do not know what it is the best choice for the display between "€" and  "euros", I let the development team choose what they think is best. All other numerical quantities are dimensionless therefore they have no unit.

![217024208-eeb8bb45-1657-4d87-b057-a320eaf66049](https://user-images.githubusercontent.com/10436551/217031881-9a9f9a77-6a09-4398-ba13-9db3938c97b8.png)

**Comment by laurent-laporte-pro** [comment]
Il faut aussi remplacer l'onglet "Xpansion" pour le basculer dans le Menu latérale de gauche.
Faire une refonte des paramètres d'Xpansion au niveau de l'interface => **un refactoring est nécessaire** pour utiliser le composant "Form"
Mettre à jour les end points côté back office pour lire et mettre à jour les paramètres d'Xpansion (il manquerait le paramètre `separation_parameter`).

Liste des end points:

- GET `/v1/studies/{uuid}/extensions/xpansion/settings` permet de récupérer les paramètres
- PUT `/v1/studies/{uuid}/extensions/xpansion/settings` permet de mettre à jour les paramètres

**Comment by laurent-laporte-pro** [comment]
Le paramètre `separation_parameter` est bien pris e, compte dans la version v2.16 en recette :

![xpansion_separation_parameter](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/0276ba68-040d-43e1-818b-440ac7e228c2)
