### ISSUE TITLE
Add column management to editable matrices

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1170]
# Context

This is related to Time Series (TS)

# Requirement Description

Allow to add / remove columns in editable matrix component.
This may require a new API endpoint.

You need to add a "+" button to add a column and a "-" button to remove it. When deleting, a confirmation popup is needed.

> **NOTE:** Edgar made a proposal regarding the user experience (UX).

# Acceptance Criteria

- [ ] On removal, the column must be removed from the table file.
- [ ] On append, the column must be added in the table file.

**Comment by laurent-laporte-pro** [comment]
Au niveau du backoffice, l'ajout d'une colonne consiste à créer une colonne vide.

Il faut spécifier l'UX.

**Comment by laurent-laporte-pro** [comment]
Already done
