### ISSUE TITLE
info.antares (fichier), dossier output

### ISSUE THREAD

**Issue by TitouanRobert** [AntaresSimulatorTeam/AntaREST#119]
Bonjour,

Il semblerait qu'il manque des informations provenant du fichier dans le titre (la référence au fichier dans l'API à été supprimé et il est directement sourcé à la base de l'étude)

Dans l'étude que j'utilise il contient les informations suivantes : 
[general]
version = 710
name = test3A
mode = Economy
date = 2020.10.15 - 09:57
title = 2020.10.15 - 09:57
timestamp = 1602748657

Merci d'avance,

**Comment by qdesmedt** [comment]
Merci beaucoup pour ce retour Titouan !
Nous le prendrons en compte au plus vite.
N'hésite pas si tu as d'autres retour à nous faire.

**Comment by TitouanRobert** [comment]
Merci à vous :)

**Comment by qdesmedt** [comment]
Bonjour Titouan,

Afin d'être sur, l'extension de ce fichier est bien "info.antares-output" ?

**Comment by TitouanRobert** [comment]
C'est ça oui!
