### ISSUE TITLE
Incorrect error message when upgrading from a 8.4.0 version study

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1206]
Current behavior : InvalidUpgrade(<HTTPStatus.UNPROCESSABLE_ENTITY: 422>, 'The version 840 is not supported')
Expected behavior : Message saying 'You currently have the latest version possible'

**Comment by laurent-laporte-pro** [comment]
Il faudrait griser le bouton de montée de version lorsque l'étude est déjà en dernière version.

Il faut récupérer la liste des versions des études utilisée par le module de mise à niveau. Un nouveau end point est peut-être nécessaire.

(_côté API, il faut renvoyer un message d'erreur plus explicite._)

**Comment by MartinBelthle** [comment]
The only thing left to do is to grey out the upgrade button when the study is in the last supported version. Perhaps it is not even necessary as the error message is explicit on branch dev, in that case this issue is outdated.

**Comment by laurent-laporte-pro** [comment]
## Spécifications

- Lorsqu'un utilisateur se connecte à l'interface web de l'étude, si l'étude est déjà dans la dernière version disponible, le bouton "Mettre à niveau" doit être grisé et non cliquable.

- Si l'utilisateur survole le bouton "Mettre à niveau", un message d'information doit s'afficher pour indiquer que l'étude est déjà dans la dernière version disponible.

- Si l'utilisateur clique sur le bouton "Mettre à niveau" alors que l'étude est déjà dans la dernière version disponible, rien ne doit se passer et aucun changement ne doit être apporté à l'étude. Aucun message d'erreur ne doit s'afficher si l'utilisateur clique sur le bouton "Mettre à niveau".

- [non régression] Si l'utilisateur clique sur le bouton "Mettre à niveau" alors que l'étude n'est pas dans sa dernière version, la boîte de dialogue de mise à niveau doit s'afficher normalement.

- [amélioration du cas nominal] la boîte de dialogue doit s'afficher et proposer une liste de versions dans l'ordre inverse (de la plus récente à la plus ancienne) ; la version la plus récente étant sélectionnée par défaut. La liste ne doit afficher que les versions supérieures à la version courante de l'étude.

**Comment by laurent-laporte-pro** [comment]
GET "/v1/studies/_versions": returns the list of available study versions

**Comment by hdinia** [comment]
> ## Spécifications
> * Lorsqu'un utilisateur se connecte à l'interface web de l'étude, si l'étude est déjà dans la dernière version disponible, le bouton "Mettre à niveau" doit être grisé et non cliquable.
> * Si l'utilisateur survole le bouton "Mettre à niveau", un message d'information doit s'afficher pour indiquer que l'étude est déjà dans la dernière version disponible.
> * Si l'utilisateur clique sur le bouton "Mettre à niveau" alors que l'étude est déjà dans la dernière version disponible, rien ne doit se passer et aucun changement ne doit être apporté à l'étude. Aucun message d'erreur ne doit s'afficher si l'utilisateur clique sur le bouton "Mettre à niveau".
> * [non régression] Si l'utilisateur clique sur le bouton "Mettre à niveau" alors que l'étude n'est pas dans sa dernière version, la boîte de dialogue de mise à niveau doit s'afficher normalement.
> * [amélioration du cas nominal] la boîte de dialogue doit s'afficher et proposer une liste de versions dans l'ordre inverse (de la plus récente à la plus ancienne) ; la version la plus récente étant sélectionnée par défaut. La liste ne doit afficher que les versions supérieures à la version courante de l'étude.

@laurent-laporte-pro merci beaucoup pour ces spécifications, je vais ouvrir une PR pour empecher l'upgrade si l'étude est déjà dans la dernière version disponible

concernant ce point: 
[amélioration du cas nominal] la boîte de dialogue doit s'afficher et proposer une liste de versions dans l'ordre inverse (de la plus récente à la plus ancienne) ; la version la plus récente étant sélectionnée par défaut. La liste ne doit afficher que les versions supérieures à la version courante de l'étude.

j'ouvre une issue dédiée, car cela implique de créer un composant avec un formulaire intégré a la boite de dialogue, pour le choix de la version, il serait bien également de prévoir un refactoring du composant parent (/src/components/NavHeader)

https://github.com/AntaresSimulatorTeam/AntaREST/issues/1508
