### ISSUE TITLE
[Hydro] Fix the display of the units of the reservoir levels matrix

### ISSUE THREAD

**Issue by thibaulttoujouse** [AntaresSimulatorTeam/AntaREST#1208]
La matrice "reservoir levels" dans "hydro" est indiquée est % , pour autant il semble que les données à intégrer soient entre 0 et 1.

**Comment by hdinia** [comment]
Before:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33469289/213410914-af9ff379-124e-4ab4-b569-d0fcb2dcba83.png)

After:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/33469289/213411221-80c4b522-fc55-4dd7-bede-8b701861fc54.png)

We need to display and update values for the reservoir levels matrix between 0 - 100% as in the first picture (old interface)

**Comment by laurent-laporte-pro** [comment]
Generalization of this issue (which will be turned into a User Story)

For each matrix (and not just the Reservoir Levels matrix), we need to specify, for each column:
- the column label (with units),
- the type: integer, float, boolean,
- the range of the value (a min/max interval of values),
- the string representation (Python format) --this representation could change according to the localization (English/French) and must be handled by the UI,
- the string representation used for import/export (TSV format).

For this reason, we need a census of the different types of matrices. And then, we will be able to write the specifications of these matrices.

**Comment by laurent-laporte-pro** [comment]
See [Add column unit#1127](https://github.com/AntaresSimulatorTeam/AntaREST/issues/1127)

**Comment by laurent-laporte-pro** [comment]
Ajouter un paramètre optionnel "pretty_print" côté back-office pour récupérer les données formatée (pourcentages).

**Comment by skamril** [comment]
Issue to remove, duplicate with #1329
