### ISSUE TITLE
Add version upgrade choice

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1210]
Add in the UI the possibility to upgrade to a user specified version.
The proposed versions should only be the upper versions.
Also add the version in a query param in the API.

**Comment by MartinBelthle** [comment]
We should also notify the user that he should not open or interact in any way with the study while it is upgrading otherwise he could lock some files and it will break the study upgrader code

**Comment by MartinBelthle** [comment]
This issue is closed by this PR : https://github.com/AntaresSimulatorTeam/AntaREST/issues/1508
