### ISSUE TITLE
Table mode - renewable clusters & binding constraints

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1215]
### Current situation

It is possible to choose properties from Areas, Links, or Thermal Clusters for mass edition. 

### Request

I would like to add properties for *renewable clusters* and *binding constraints*.

**Comment by laurent-laporte-pro** [comment]
More descriptions:
- In the code, we define the different columns for each type of `table mode`.
- So we have to add 2 new types and define the columns for each type: You have to see the form view to know the columns and the handled data types.

Binding constraints columns:
- type
- bounds
- activated

Renewable clusters:
- group
- time series mode
- enabled
- unit
- nominal capacity
