### ISSUE TITLE
Update input when store in input TS is active

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1226]
Timeseries are generated during the simulation process and are returned in the simulation zip.
This should create commands if it's a variant or juste override the input in raw mode.

**Comment by laurent-laporte-pro** [comment]
duplicate #1112

**Comment by laurent-laporte-pro** [comment]
The preferences could also store the **last used study**, but the user interface must also be able to automatically display the edit page for that study.
