### ISSUE TITLE
Better consider the channel in event bus broadcasting

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1233]
**Component:** websocket

# Feature Description

## Requirements

The event management during the brodcasting of the event bus could be improved by taking into account the channel of each event. The calculation time and filtering could be improved when the number of events to be processed is very big.

The aim of this feature is to change the broadcast rule as follows:
- if the channel is empty, we check only the user's permission;
- otherwise, if the channel is not empty, we check both that the channel is in the subscription list **and** the user's permission.

> **NOTE:** Checking the channel will allow for better filtering of events, but this requires adding channels to events and subscribers. This can be done in another RP.

## Code review

The `Event.channel` attribute should be a non-optional `str` that defaults to "".

# Acceptance criteria

Considering events with the right user permissions:

- [ ] the event manager must send events if the channel is empty (i.e.: ""),
- [ ] the event manager must send events if the channel is a subscriber channel
- [ ] the event manager must not send events if the channel does not correspond to any subscriber channel

Considering events with the bad user permissions:

- [ ] the event manager must not send events to any subscriber

**Comment by pl-buiquang** [comment]
Currently, there is some Event creation that do not have permission assigned.
The permission field should be required so that the new channel permission check correctly send events to allowed clients.
