### ISSUE TITLE
Impossible to export antares studies to Imagrid

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1236]
Due to the new feature of auto-archiving studies that are more than sixty days old since their last update.
Some studies that need to be present on Antaresweb for Imagrid haven't been exported to this other application.

**Comment by laurent-laporte-pro** [comment]
A work-around is to manually unarchive the studies before export.

> **WARNING:** the study archiving function should be dropped (remove this feature). Only the `output` should be archive.

**Comment by laurent-laporte-pro** [comment]
S'il n'y a que le répertoire `output` qui est archivé, on peut juste désarchiver.

Exemple avec le end point `/v1/studies/{study_id}/outputs/{output_id}/download` : "Get outputs data", il faut considérer les output archivée (ZIP). Le end point doit être modifié pour tenir compte des fichier ZIP.

**Comment by laurent-laporte-pro** [comment]
Il faut comprendre comment l'export est fait vers IMAGRID : est-ce qu'il utilisent le end-point ?

**Comment by makdeuneuv** [comment]
Imagrid utilise les APIs Antares Web pour récupérer les sorties et de ce que j'ai compris ces sorties ne doivent pas être zippées.
Je ne sais pas quel end point en particulier est utilisé.

**Comment by laurent-laporte-pro** [comment]
Si je comprends bien, la simulation a été faite il y a longtemps. Suffisamment longtemps pour que l'étude soit archivée en automatique. Or, IMAGRID souhaite récupérer les résultats de la simulation maintenant et donc elle ne sont plus directement disponibles. Je conseillais donc de désarchiver l'étude avant de faire un export des sorties. Mais ça ne fonctionne pas, c'est bien ça ? Est-ce parce que les  sorties ne sont pas archivée et qu'au contraire elles sont supprimées ?

**Comment by makdeuneuv** [comment]
Les tâches de récupération  des résultats de la simulation par Imagrid sont faites en arrière plan, l'utilisateur n'a pas à intervenir. La solution de désarchivage de l'étude avant de faire l'export des sorties a déjà été proposée comme solution temporaire.

Le but de ce ticket est de réfléchir à une solution pérenne (sans intervention de l'utilisateur) sur l'archivage automatique qui ne doit pas prend en compte les études utilisées par Imagrid . Trouver donc un moyen de les exclure de ce mécanisme d'archivage, car dans un peu plus d'un mois nous pourrons avoir de nouveau des utilisateurs qui nous contacterons car leurs études seront de nouveau archivées et non visible par Imagrid.

**Comment by MartinBelthle** [comment]
Par rapport à ce qu'a dit Deneuv au-dessus, ce qui est faisable facilement dans le code c'est de **filtrer sur les owners.** Normalement toutes les études managées ont un owner et donc on peut filtrer là-dessus car on a un pré-filtre sur les études managées.  Ça nécessite quand même de récupérer leurs id mais ça ne devrait pas être trop compliqué si on a leurs noms.  De ce que j'ai pu tester même si ils font des études avec des tokens leur appartenant ça reste le même owner donc ça marche.

Le truc relou c'est que pour chaque nouvel utilisateur d'Imagrid il faudrait rajouter son id dans le code en dur :/

Un autre moyen de contourner serait de **filtrer sur les groupes** ce qui fait qu'on aurait pas besoin de changer le code pour chaque nouvel utilisateur mais juste de l'ajouter au groupe. Mais malheureusement plein d'études managées n'ont pas de groupe associé et je ne sais pas trop comment on gère l'appartenance d'une étude à un groupe dans le code.

**Comment by makdeuneuv** [comment]
La solution du groupe est plus intéressante, par défaut c'est à l'utilisateur d'associer un groupe à son étude managée. Seul les études sur disque ont un groupe associés automatiquement (celui du disque). Soit on crée un groupe associé aux études à importer vers imagrid que les utilisateurs eux-même devront ajouter à leur étude. Soit un crée plutôt un label à la place du groupe (car le groupe implique des droits d'accès que le label ne nécessite pas).

**Comment by MartinBelthle** [comment]
Les 2 solutions groupe et label me semblent équivalentes d'un point de vue utilisateur. Mais je ne sais pas comment implémenter le côté label dans le back (j'ai l'impression que ça relève des métadatas) alors que le check d'appartenance à un groupe, ça serait une ligne de code très simple. Tu en penses quoi @laurent-laporte-pro sur le label ?

**Comment by makdeuneuv** [comment]
Pas de retour des utilisateurs sur ce sujet. De plus Imagrid devrait pouvoir traiter des sorties archivées. Je clos le ticket. Si le sujet réapparaît, un ticket sera ouvert.
