### ISSUE TITLE
Absence fichier : /input/thermal/areas

### ISSUE THREAD

**Issue by TitouanRobert** [AntaresSimulatorTeam/AntaREST#124]
Le fichier est absent sur l'API, chez moi il a cette tête

[unserverdenergycost]
at = 3000.000000
[spilledenergycost]
at = 10.000000
be = 10.000000

**Comment by qdesmedt** [comment]
Salut @TitouanRobert,

1/

Effectivement le jsonschema n'était pas complet. 
Il ne contenait pas le mot clé "spilledenergycost".

2/

Cependant, il contenait bien "unserverdenergycost".
Quand tu dis: "absent sur l'API" ?
Parles tu du "Swagger" ? Ou bien as tu testé directement sur l'API ?

Merci de ton retour !

**Comment by TitouanRobert** [comment]
Bonjour,

Sur l'API.

Merci pour ta réponse
Titouan
