### ISSUE TITLE
Committing package-lock.json

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/AntaREST#1248]
**Description**

To my knowledge, the best practice for web apps is to commit `package-lock.json` to the repository, in order to guarantee build stability.

Indeed, when I downloaded the repo a few weeks ago, I could not build the app because of an inconsistency between material UI libraries at that time.
The presence of package-lock.json would have solved that issue.

Note that this can happen not only in dev environment, but also in CI/CD environments.

**Comment by laurent-laporte-pro** [comment]
closed by #1323
