### ISSUE TITLE
Field "Year" not working correctly in result page

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1254]
When we empty the field "Year" (right panel after clicking on "Change"), `Synthesis`  is selected automatically.

The link between the two fields is bad.

**Comment by laurent-laporte-pro** [comment]
Porblème d'affichage dans le menu de droite permettant de filtrer les résultats.



![Image](https://user-images.githubusercontent.com/43534797/230338938-114a9105-47b9-43cf-9bd1-740791148b1b.png)

**Comment by makdeuneuv** [comment]
@skamril Il n'y a aucune indication sur comment tester cet _issue_ et aucune PR associée.

**Comment by makdeuneuv** [comment]
Still present.

**Comment by skamril** [comment]
Close because the fix is made in #1626
