### ISSUE TITLE
Use unzipped output instead of zipped when both are present

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#1261]
When building the `FileStudyConfig` and specifically parsing the output in `antarest.study.storage.rawstudy.model.filesystem.config.files.ConfigPathBuilder._parse_outputs`, it happens that the output exists in two forms (zipped and unzipped, the filename stem being the same, eg. 20220726-0745eco and 20220726-0745eco.zip).
Currently there is no guarantee that the unzipped one is chosen as a reference (the listing of outputs is a map keyed with the filename stem, with the latter version found overriding the previous one).

Building this map should be done otherwise to ensure that if two versions of the same output are present, the unzipped one is preferred.

**Comment by laurent-laporte-pro** [comment]
You can also fix the following code `antarest.study.storage.rawstudy.model.filesystem.config.files.ConfigPathBuilder.parse_simulation`:

```python
with ZipFile(path, mode="r") as zf:
    namelist = zf.namelist()
    error = "checkIntegrity.txt" not in namelist
    xpansion = "lp/lp_namer.log" in namelist
```
