### ISSUE TITLE
feat(launcher): Integrate Antares Solver v8.5.0

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1272]
En tant qu'utilisateur, je souhaite utiliser la version en cours de développement d'Antares Simulator v8.5.0-rc*N* afin d'effectuer des tests en recette.

A faire en premier pour pouvoir lancer une étude et visualiser les résultats

- Mise à jour des numéros de version dans la liste déroulante de la fenêtre de lancement (front)
- Mise à jour des numéros de version dans antares-launcher (tâche à confirmer)
- Mise à jour des scripts de lancement sur le [dépôt antares-cd](https://devin-source.rte-france.com/antares/antares-cd) (launchAntares.sh & launchAntaresRec.sh)

Voir : [Nouvelle version d'Antares Simulator](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?pageId=271680464)

**Comment by laurent-laporte-pro** [comment]
Le fichier est modifié à la main sur CALIN directement en production (et en recette).

Voir la procédure sur le [Wiki documentaire](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?pageId=175515426).

**Comment by laurent-laporte-pro** [comment]
_(no development branch for this issue)_

**Comment by makdeuneuv** [comment]
Actions done, this issues can be closed.

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv , as-tu lancé une étude en version 8.5 depuis Antares web sur la recette ? Est-ce que les sorties sont satisfaisantes ?

**Comment by laurent-laporte-pro** [comment]
Il y a effectivement une modification à faire côté back-office. La liste des versions est données par l'URL `/v1/studies/_versions` dans l'API. Donc, soit il faut corriger le programme, soit corriger la configuration.

**Comment by makdeuneuv** [comment]
J'ai pu lancer une étude en 8.5 et les sorties dans les fichiers output sont conformes. Antaresweb appele bien le bon solveur.
