### ISSUE TITLE
dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1286]
### Context
I was trying to test ./AntaresWeb/AntaresWebServer on Ubuntu (standalone version ?)

I made `antares-8.4-solver` and `./AntaresWeb/AntaresWebServer` executable, then tried to execute `./AntaresWeb/AntaresWebServer`. But I got this error

[389384] Error loading Python lib '/home/omnesflo/Téléchargements/antares-web/AntaresWeb/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/omnesflo/Téléchargements/antares-web/AntaresWeb/libpython3.8.so.1.0)

It's probably because you use ubuntu-latest (22.04), and I run 20.04.

**Comment by makdeuneuv** [comment]
According to the literature, this issue may be the fact that you don't have the right version of glibc for your OS. The minimum glibc version now for lastest OS  is 2.27.
We need more details : 
- the version of glibc on our OS : ` ldd --version`

Someone have resolve this by delete the file libm.so.6 ([https://aur.archlinux.org/packages/figma-linux](https://aur.archlinux.org/packages/figma-linux))

**Comment by flomnes** [comment]
Right, ldd returns 2.31 for the glibc version. Will try to delete said file.

**EDIT**

Deleting the file doesn't work. `dlopen` fails because it doesn't exist !

**Comment by flomnes** [comment]
Fixed in 2.13
