### ISSUE TITLE
Study upgrade from version 8.0 to 8.1 not fully implemented

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1308]
The function to upgrade a study from version 8.0 to version 8.1 performs the following processing:

- Update the `settings/generaldata.ini` file:
  - Add the value `"renewable-generation-modelling = aggregated"` in the `"other preferences"` section.
- Creation of the directory `input/renewables/clusters`,
- Creation of the directory `input/renewables/series`,

Currently, the folders are created but no file is written inside.

See the `TODO` in the source code: https://github.com/AntaresSimulatorTeam/AntaREST/blob/e9fae4204d6da2a4f710bcbc0361e0380d2f9b15/antarest/study/storage/study_version_upgrader.py#L148-L160

**Comment by laurent-laporte-pro** [comment]
@flomnes Can you give us more information about what to do to migrate a v8.0 study?

**Comment by flomnes** [comment]
> @flomnes Can you give us more information about what to do to migrate a v8.0 study?

New parameters :
* "other preferences"."hydro-heuristic-policy": str (`accommodate rule curves`/`maximize generation`. default = `accommodate rule curves`)
* "optimization"."include-exportstructure": bool (default = false)
* "optimization"."include-unfeasible-problem-behavior": str (`warning-dry`, `warning-verbose`, `error-dry`, `error-verbose`, default = `error-verbose`)

Parameter renaming `"general"."custom-ts-numbers"` becomes `"general"."custom-scenario": bool`

[Source](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?spaceKey=ANTR&title=Evolution+du+format+Antares)

**Comment by laurent-laporte-pro** [comment]
> > @flomnes Can you give us more information about what to do to migrate a v8.0 study?
> 
> New parameters :
> 
> * "other preferences"."hydro-heuristic-policy": str (`accommodate rule curves`/`maximize generation`. default = `accommodate rule curves`)
> * "optimization"."include-exportstructure": bool (default = false)
> * "optimization"."include-unfeasible-problem-behavior": str (`warning-dry`, `warning-verbose`, `error-dry`, `error-verbose`, default = `error-verbose`)
> 
> Parameter renaming `"general"."custom-ts-numbers"` becomes `"general"."custom-scenario": bool`
> 
> [Source](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?spaceKey=ANTR&title=Evolution+du+format+Antares)

Ok, thanks for the new settings specifications. The migration script creates two subfolders. What are they for? Aren't there any files to convert or generate?

**Comment by laurent-laporte-pro** [comment]
> > @flomnes Can you give us more information about what to do to migrate a v8.0 study?
> 
> New parameters :
> 
> * "other preferences"."hydro-heuristic-policy": str (`accommodate rule curves`/`maximize generation`. default = `accommodate rule curves`)
> * "optimization"."include-exportstructure": bool (default = false)
> * "optimization"."include-unfeasible-problem-behavior": str (`warning-dry`, `warning-verbose`, `error-dry`, `error-verbose`, default = `error-verbose`)
> 
> Parameter renaming `"general"."custom-ts-numbers"` becomes `"general"."custom-scenario": bool`
> 
> [Source](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?spaceKey=ANTR&title=Evolution+du+format+Antares)

Ok, thanks for the new settings specifications. The migration script creates two subfolders. What are they for? Aren't there any files to convert or generate?

**Comment by laurent-laporte-pro** [comment]
Add a notification message : C'est à l'utilisateur de remplir les répertoires.
