### ISSUE TITLE
Upload a matrix file

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#132]
The url POST /studies/{study_id}/{path_to_matrix} should replace or create the corresponding filesystem representation of the data matrix.
In future version with a different storage backend, this could mean the matrix is stored elsewhere (without overwriting any existing previous one) and the reference to it should be updated in the json representation of the study. In this regard the operation wouldn't be idempotent that's why this is a POST and not a PUT.
For now, i guess we can replace the file at the requested path.

The path_to_matrix must be of the correct type or an error should be thrown.

**Comment by GPivette** [comment]
"The path_to_matrix must be of the correct type or an error should be thrown" 
Que faut-il vérifier précisément ? Une extension en .txt, un path valable (sans espaces), correct par rapport au jsonschema, ou autre chose ?

**Comment by pl-buiquang** [comment]
je pensais que les feuilles qui étaient des matrices (donc oui globalement les fichiers qui ont des extensions en .txt) avait un type spécial. mais apparemment c'est simple string. Donc a priori oui c'est les extension .txt
Après le path doit etre valable aussi évidemment
