### ISSUE TITLE
[ANT-652] Add an “Inflow Structure” tab

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1330]
## Problem Statement
This is a tab that exists in the old GUI shown below
![image](https://user-images.githubusercontent.com/114937156/220875865-802956f7-cc6a-46f5-949f-a029b4eba3f6.png)

## Proposed Solution

This tab contains three elements:

-  The “inter-montly correlation” coefficient.
- "Overall monthly hydro energy", which contains for each month the columns "Expectation" (average contribution), Std Deviation (standard deviation of contributions), Min/Max, RoRshare (distribution of contributions between the dams and the run of the river).
- “Inflow Pattern” which corresponds for each day of the year to a weighting of the inputs.

**Comment by laurent-laporte-pro** [comment]
Traduction des libellés :

- "Inflow Structure" => "Inflow Structure". ???

**Comment by hdinia** [comment]
## Inflow structure 
- Overall monthly hydro (ROR + Storage)
Fichier: input/hydro/prepro/[area]/energy

- Inflow pattern
Fichier: input/hydro/common/capacity/inflowPattern_[area]
