### ISSUE TITLE
[ANT-652] The labels in the first column and in the first row of the "Daily Power" screen which lead to the misinterpretation of this data as TS.

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1333]
## Description
The labels in the first column and in the first row of the "Daily Power" screen which lead to the misinterpretation of this data as TS.
![image](https://user-images.githubusercontent.com/114937156/220884057-d8d223f8-6210-430b-b655-baa08a4e25a5.png)
![image](https://user-images.githubusercontent.com/114937156/220884080-9820d4b5-451b-4fc0-8ed4-5e05aee3fa96.png)

While these are parameters given in % tank filling ranging from 0 to 100%, this is what it should look like
![image](https://user-images.githubusercontent.com/114937156/220884151-604b79e5-4fc9-45d7-b49a-0acb9cddd44b.png)
![image](https://user-images.githubusercontent.com/114937156/220884184-305da0d9-f6cc-4196-8818-15e3b7a0ae30.png)

## Environment

- [x] Production
- [x] Staging

**Comment by hdinia** [comment]
See #1332
