### ISSUE TITLE
[ANT-672] Add new optimization form fields

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1339]
## Context

The goal of this request is to modify the adequacy patch configuration form: reorganization of the menus and addition of the new fields brought by Antares Simulator v8.5 (see Florian’s Specifications in #1304).

For the sake of clarity, we propose to create a specific "Adequacy patch" entry in the menu (note: we may do the same for Xpansion in the future).

![adequacy_patch_p1](https://user-images.githubusercontent.com/43534797/223998153-1525954c-4821-4c28-a6ea-e8de072efd5a.png)

## Specifications

What to do:
- Add a new entry "Adequacy patch" in the sidebar,
- Add a new form dedicated to the adequacy patch: move the options of the "Optimization Preferences" entry to this form
- Add the new options of version v8.5 (see below)
- Translate the labels in French

![adequacy_patch_p2](https://user-images.githubusercontent.com/43534797/224000193-a9a230bb-07e4-44cd-9fe5-5dbeb2b23f02.png)

The following fields are added:

- price-taking-order [string] can take values "DENS" (default value) and "Load".
- include-hurdle-cost-csr [bool]. Default value = false
- check-csr-cost-function [bool]. Default value = false
- threshold-initiate-curtailment-sharing-rule [double >= 0]. Default value = 0.0
- threshold-display-local-matching-rule-violations [double >= 0]. Default value = 0.0
- threshold-csr-variable-bounds-relaxation [int >= 0]. Default value = 3

Suggestion for the translation (to be confirmed with @flomnes):

- price-taking-order: "Prix de la prise en charge"
- include-hurdle-cost-CSR: "Inclure le coût de la hausse de la CSR"
- check-CSR-cost-function: "Vérifier la fonction de coût CSR"
- threshold-initiate-curtailment-sharing-rule: "Seuil de déclenchement de la règle de partage des réductions"
- threshold-display-local-matching-rule-violations: "Seuil d'affichage des violations de la règle d'appariement local"
- threshold-CSR-variable-bounds-relaxation: "Seuil d'assouplissement des limites variables de la CSR"

**Comment by skamril** [comment]
`include-split-exported-mps` and `link-type` fields have been removed  and have never been used https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1199/files#diff-4e5b998fd8bbd6428301a61d350eb29c158b20eaf36bbe8a6486a89d4e89ef51

**Comment by laurent-laporte-pro** [comment]
### Tests d'intégration

J'ai remarqué quelques anomalies dans le formulaire Adequacy Patch. Je pense qu'il y a quelques ajustements à faire :

- [x] Actuellement, il est possible de laisser le champ "price-taking-order" vide alors que sa valeur par défaut devrait être "DENS".

![issue-1339_price-taking-order-default](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/ad423d35-f713-4eac-a66f-45a6f14553cc)

- [x] Il y a une erreur de validation 422 qui se produit lorsqu'on configure l'un des trois champs "Avancé", ce qui empêche de configurer l'adequacy patch correctement.

![MicrosoftTeams-image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/657b4e62-8e73-4309-bb74-4a5e8adab9c9)

- [x] Est-il possible de réduire la largeur des trois champs de configuration "Avancés" ?

![adp_advanced_fields](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/4c8a23ff-03bc-4d44-bcd4-b40d42b7a5c1)


- [x] Il y a un problème avec la sauvegarde de la configuration, car si l'on change d'onglet et que l'on revient dessus,
  la configuration est perdue.

Je pense que ces problèmes peuvent être corrigés rapidement.

**Comment by laurent-laporte-pro** [comment]
Détail sur l'erreur 422 :

PUT `http://localhost:3000/v1/studies/9b7e23a4-782c-4522-93de-a95d4e158984/config/adequacypatch/form`

```json
{
  "description": "value is not a valid float",
  "exception": "RequestValidationError",
  "body": {
    "thresholdDisplayLocalMatchingRuleViolations": 1
  }
}
```

**Comment by JMJ-rte** [comment]
- Actuellement, il est possible de laisser le champ "price-taking-order" vide alors que sa valeur par défaut devrait être "DENS" 
   **Oui, la valeur par défaut est DENS**
- Il y a une erreur de validation 422 qui se produit lorsqu'on configure l'un des trois champs "Avancé", ce qui empêche de configurer l'adequacy patch correctement.
   **Les 3 paramètres sont positifs, il n'est donc pas possible de rentrer des valeurs négatives, d'où les erreurs**
- Est-il possible de réduire la largeur des trois champs de configuration "Avancés" ?
  **Oui, ce serait préférable que le champ où apparait la valeur du paramètre soit sur la même ligne que son libellé**
- Il y a un problème avec la sauvegarde de la configuration, car si l'on change d'onglet et que l'on revient dessus,
la configuration est perdue.
  **Anomalie à corriger**
