### ISSUE TITLE
Fichiers .txt de contraintes

### ISSUE THREAD

**Issue by TitouanRobert** [AntaresSimulatorTeam/AntaREST#134]
Bonjour,

Il manque à priori les fichiers .txt sur les contraintes  : 

http://localhost:8080/studies/antaresStd/input/bindingconstraints/**nomcontrainte.txt**

![image](https://user-images.githubusercontent.com/12134403/99694342-9cd62500-2a8c-11eb-9c4e-c7ccb9abc904.png)

**Comment by TitouanRobert** [comment]
Je peux en joindre un si vous voulez le format, il peuvent aussi être vide a priori

**Comment by qdesmedt** [comment]
Merci Titouan pour ce retour.
Il est prit en compte !
