### ISSUE TITLE
[ANT-658] Ouputs of variant are not visible

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1351]
Outputs are present in "Debug"

When you create a first variant on a study, the results of its simulations are visible on the web interface.

Then when a second variant is created from the first one, the results of the simulations of the second variant are not visible on the interface although they are present (in the debugging view).

The results of all variants, whatever their level, should be visible on the web interface.

**Comment by MartinBelthle** [comment]
J'ai écrit ça sur GoPro, il y a eu une update depuis ? Parce que ça m'avait l'air d'être un problème front

Quand on clique sur un output dans la variante de niveau 2+ (variante de variante), il n'y a pas l'appel API get /studies/uuid/raw?path ... alors que cet appel est présent pour l'étude parent et la variante "de niveau 1". Le front devrait déclencher l'appel API et ne le fait pas pour une raison qui m'échappe.

**Comment by MartinBelthle** [comment]
@skamril Screenshot associé  au fichier index.tsx dans le module ResultDetails. Le paramètre data vaut `undefined` alors que quand ça marche, il est renseigné. Cela n'entraîne aucun appel API car cet appel est seulement déclenché dans une boucle qui nécessite le paramètre data.
![bugDataFronf](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/e9fd18d8-bf82-4073-9011-65e349635f55)
