### ISSUE TITLE
Table mode is unstable for custom tables

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1352]
## Description
Table mode leads to invalid studies / tables for custom tables.

## Steps to Reproduce
1. Create a custom table in "table mode"
2. Add a few fields
3. Change a few boolean values (checkboxes)

## Actual Behavior
The table becomes invalid with the following error "AxiosError: Request failed with status code 500"

## Expected Behavior
No error

## Screenshots
![image](https://user-images.githubusercontent.com/26088210/221877044-bbc6db54-9e30-4c34-be74-197e569fa0b3.png)

![image](https://user-images.githubusercontent.com/26088210/221877573-ec780d61-fec9-4def-92b4-6b23777f006a.png)

## Possible Solution
Maybe don't allow editions that would lead to an invalid state. Some enums are treated as strings for example.

## Environment

- [X] Production
- [X] Staging
## Additional Information

- If applicable, provide the study ID that this issue relates to:
- The date and time when the issue occurred: 27/02/2023
- Browser and version: Firefox 107.0 (64 bits)
- Operating System: Linux Ubuntu 20.04

**Comment by makdeuneuv** [comment]
The bug no longer occurs
