### ISSUE TITLE
[ANT-652] Add "Allocation" form in Hydro

### ISSUE THREAD

**Issue by hdinia** [AntaresSimulatorTeam/AntaREST#1357]
## Problem Statement

The tab "Allocation" must be added as on the old interface, see the screenshot below

![image](https://user-images.githubusercontent.com/33469289/221922137-cf5c045f-7045-4c55-a7a2-c831c558b5f8.png)

**Comment by hdinia** [comment]
Allocation => Fichiers input/hydro/allocation/<id de la zone>.ini
Contenu

```ini
[[allocation]]
id zone = coeff
id zone 2 = coeff 2
```

> **NOTE:** le nom de la section comporte des crochets.

**Comment by laurent-laporte-pro** [comment]
La matrice d'allocation représente les quantités d'eau des réservoirs hydrauliques à turbiner pour chaque zone par rapport à la consommation de cette zone et des autres zones. Les colonnes représentent les zones productrices (avec un réservoir hydraulique), les lignes représentent les zones dont la consommation électrique doit être prise en compte.

Les quantités peuvent être des proportions (en nombres entiers) ou des taux (entre 0 et 1) de consommation. En principe, lors de la simulation, le solveur calcule une moyenne pondérée des quantités.

Par défaut, la matrice d'allocation est une diagonale de 1 : chaque zone doit turbiner en fonction de sa propre consommation uniquement.

Exemple : si dans la colonne "France" j'ai 3 dans la ligne "France" et 1 dans la ligne "Italie", cela signifie que l'eau turbinée par le réservoir en France est répartie aux 3/4 en fonction de la consommation de la France et à 1/4 en fonction de la consommation de l'Italie.

|        | France | Italie |
|--------|--------|--------|
| France | 3      | 0      |
| Italie | 1      | 1      |

Au niveau de l'interface utilisateur, la première ligne et la première colonne doivent être figées (au sens de colonne / ligne figées dans Excel). Les cellules vides de la matrice peuvent être vides (au lieu de zéro), si cela est plus lisible.

Remarques :

- L'allocation hydraulique concerne toutes les zones de l'étude.
- Il y a autant de lignes que de colonnes (autant que de zones)
- Il est possible d'avoir une allocation même s'il n'y a pas de lien entre les nœuds.
