### ISSUE TITLE
[ANT-652] Add "Spatial correlation" form

### ISSUE THREAD

**Issue by hdinia** [AntaresSimulatorTeam/AntaREST#1358]
## Problem Statement

The tab "Spatial correlaton" must be added as on the old interface, see the screenshot below

![image](https://user-images.githubusercontent.com/33469289/221923015-82300ff6-3bf4-49bb-90c6-88b5ea6b544e.png)

# Spatial Correlation Form for Hydro

## User Story:

As a User using Antares Web, I want to input correlation coefficients between two areas within the Hydro section, so that I can define relationships between areas for hydro power simulations and enhance the accuracy of my study results.

## Acceptance Criteria:

1. The Spatial Correlation Form should be integrated within the Hydro section of the Antares Simulator web application.
2. A new "Spatial Correlation" tab should be added inside the Hydro section.
3. A separate form should be available for each area of the study, allowing users to input correlation coefficients between the current area and other areas.
4. A matrix visualization should be accessible to users, allowing them to view all the correlations between all the areas of a study.
5. The form should include two input fields labeled "Area 1" and "Area 2" for users to enter the names of the two areas they want to define a correlation for.
6. The form should include a third input field labeled "Coefficient" for users to enter the correlation coefficient as a float.

> An example of the expected input format should be: "area1%area2=coefficient."

7. A "Submit" button should be added to save the input data and send it to the FastAPI backend.
8. Input validation should be implemented to ensure that:

> Area names (Area 1 and Area 2) are non-empty strings.
> The correlation coefficient is a float, a valid number between -100 and 100, inclusive.
> Error messages are shown if input fields do not meet the above requirements.

9. The user interface of the Spatial Correlation Form should be visually consistent with the rest of application.
10. The user's input should be correctly formatted and sent to the FastAPI backend.
11. The FastAPI backend should have endpoints for getting spatial correlations, updating spatial correlations, and getting the overall matrix.
12. The FastAPI backend should successfully update the ini file that stores all the spatial correlations of a study.
13. The new feature should not negatively impact the application's overall performance.
14. Clear and concise error messages should be displayed to the user if there is any issue with updating the ini file.

> Show a success message or visual indicator when a user successfully submits a new correlation coefficient or updates an existing one, providing users with feedback on their actions.

15. The user should be able to view the current spatial correlations of a study in the Spatial Correlation Form before making changes.
16. The frontend should display the area-specific forms, the overall matrix, and any information retrieved from the backend endpoints for spatial correlations.
17. The implementation should be tested to ensure proper functionality and a smooth user experience.

**Comment by hdinia** [comment]
Spatial correlation => Fichier input/hydro/prepro/correlation.ini. Le contenu est le suivant :

Il y a toujours une section "general". Si general.mode = annual, la section annual contient des couples d'id de zones

Si general.mode = monthly, ce sont les sections numérotées de 0 à 11 qui contiennent ces couples.

Dans tous les cas, les sections doivent exister, même si elles sont vides (cf. exemple ci-dessous)

[general]
mode = <annual / monthly>

[annual]
<area 2>%<area> = coeff
etc.

**Comment by hdinia** [comment]
# Spatial Correlation Form for Hydro Power Simulation

## User Story:

As a User using Antares Web, I want to input correlation coefficients between two areas within the Hydro section, so that I can define relationships between areas for hydro power simulations and enhance the accuracy of my study results.

## Acceptance Criteria:

1. The Spatial Correlation Form should be integrated within the Hydro section of the Antares Simulator web application.
2. A new "Spatial Correlation" tab should be added inside the Hydro section.
3. A separate form should be available for each area of the study, allowing users to input correlation coefficients between the current area and other areas.
4. A matrix visualization should be accessible to users, allowing them to view all the correlations between all the areas of a study.
5. The form should include two input fields labeled "Area 1" and "Area 2" for users to enter the names of the two areas they want to define a correlation for.
6. The form should include a third input field labeled "Coefficient" for users to enter the correlation coefficient as a float.

> An example of the expected input format should be: "area1%area2=coefficient."

7. A "Submit" button should be added to save the input data and send it to the FastAPI backend.
8. Input validation should be implemented to ensure that:

> Area names (Area 1 and Area 2) are non-empty strings.
> The correlation coefficient is a float, a valid number between -100 and 100, inclusive.
> Error messages are shown if input fields do not meet the above requirements.

9. The user interface of the Spatial Correlation Form should be visually consistent with the rest of application.
10. The user's input should be correctly formatted and sent to the FastAPI backend.
11. The FastAPI backend should have endpoints for getting spatial correlations, updating spatial correlations, and getting the overall matrix.
12. The FastAPI backend should successfully update the ini file that stores all the spatial correlations of a study.
13. The new feature should not negatively impact the application's overall performance.
14. Clear and concise error messages should be displayed to the user if there is any issue with updating the ini file.

> Show a success message or visual indicator when a user successfully submits a new correlation coefficient or updates an existing one, providing users with feedback on their actions.

15. The user should be able to view the current spatial correlations of a study in the Spatial Correlation Form before making changes.
16. The frontend should display the area-specific forms, the overall matrix, and any information retrieved from the backend endpoints for spatial correlations.
17. The implementation should be tested to ensure proper functionality and a smooth user experience.

**Comment by laurent-laporte-pro** [comment]
Validation des critères d'acceptation tels que définis dans le ticket sur GitHub :
✅ Le formulaire « CORRELATION » se trouve bien dans la section « HYDRO » de chaque zone.
✅ L’onglet se nomme « CORRELATION » au lieu de « Corrélation Spaciale », nous avons préféré un libellé court.
✅ Le formulaire est bien présent dans toutes les zones.
❌ La visualisation de la matrice n'est pas visible ⇨ reporté pour la version v2.15
⛔ Le critère d'acceptation ne correspond plus aux spécifications.
✅ Il est possible de saisir les coefficients.
✅ Le bouton "Sauvegarder" est bien visible et permet de soumettre le formulaire.
✅ Les contraintes d'unicité des champs est bien respecté / les contraintes sur les valeurs possibles des coefficients est bien respecté aussi.
✅ Le formulaire se présente de manière consistante par rapport à d'autres formulaires de saisie, notamment avec celui des allocations hydrauliques.
✅ Les données en pourcentage sont bien converties en nombre entre -1 et 1 dans la configuration (debug + ini)
✅ Les points d'entrée du backend correspondent bien à la demande (voir issue [#1443](https://github.com/AntaresSimulatorTeam/AntaREST/issues/1443))
✅ On retrouve bien les données mises à jour dans le fichier INI.
❗Il faudrait aussi vérifier le comportement des Variants.
⛔ Il est difficile de faire un test de performance ici.
Vérification des messages :

- ✅ Saisie d'un texte au lieu d'un nombre
- ✅ Saisie d'un caractère bizarre
- ✅ Saisie d'un nombre < 100
- ❌ Saisie d'un nombre > 100 : Le message d'erreur pour une valeur au-dessus de 100 est faux : "La valeur minimum est 100" au lieu de "La valeur maximum est 100".
- ❌ Suppression du coefficient de la zone en cours => Cela ne devrait pas être possible. Le comportement est bizarre : lorsqu'on clique sur "Sauvegarder", le champ de la zone en cours revient.
- ❌ Modification du coefficient de la zone en cours => Cela ne devrait pas être possible.

✅ Suppression d'un champ différent de la zone en cours.
✅ Visualisation des coefficients OK.
❌ La visualisation de la matrice n'est pas visible ⇨ reporté pour la version v2.15
✅ L'application est testée.

**Comment by laurent-laporte-pro** [comment]
@hdinia Voici le compte rendu que j'avais envoyé par e-mail à la suite de la démonstration de la v2.14

- Au niveau du formulaire des allocations hydraulique, il faudrait ajouter des en-têtes en haut du formulaire pour indiquer « Load » et « Coeff. » en anglais (et « Conso » et « Coeff. » en français). Les nombres sont sans dimension.
- Au niveau du formulaire des corrélations hydraulique, les en-têtes seront différentes : « Load » et « % » en anglais (et « Conso » et « % » en français). Les nombres sont des pourcentages.
- Le bouton « View all allocations » doit afficher la matrice complète de toutes les zones de l'étude.
- L'affichage de la matrice de corrélation doit être amélioré pour mettre en valeur les nombres non nuls : les mettre en gras, par exemple. De même, il faudrait mettre en valeur la diagonale de 1 (utiliser une couleur de fond ?).
- Il faudrait aussi ajouter "Coeff." dans les deux matrices, par exemple en haut à droite pour bien indiquer que les valeurs sont sans dimension.
- Autre remarque : le bouton « View all allocations » doit être traduit en français par « Voir toutes les allocations ». Je n'ai pas bien fait attention au libellé pour les corrélations…

Il faudrait tenir compte de ces remarques.

**Comment by laurent-laporte-pro** [comment]
Fixed by #1496
