### ISSUE TITLE
`build-front.sh` script not up-to-date

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1369]
## Description

Le script [`scripts/build-front.sh`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/130f196ef76416e399cd80ed4a7efc3ba2a7f802/scripts/build-front.sh) fait référence à un fichier `src/i18n.js` qui n'existe pas. On a une erreur lors du lancement.

### Steps to reproduce the behavior:

Lancer les commandes de build du front en suivant les instructions du [`README.md`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/130f196ef76416e399cd80ed4a7efc3ba2a7f802/README.md):

```sh
$ cd webapp/
$ npm install
[...]
$ cd ..
$ sh scripts/build-front.sh 
scripts/build-front.sh: 9: [[: not found
sed: impossible de lire src/i18n.js: Aucun fichier ou dossier de ce type
```

## Possible Solution

Le script `build-front.sh` est utilisé / référencé dans les fichiers suivants :

- AntaREST/.github/workflows/deploy.yml:        run: bash ./build-front.sh
- AntaREST/README.md:NODE_OPTIONS="--max-old-space-size=8192" ./scripts/build-front.sh
- AntaREST/docs/install/0-INSTALL.md:3. Build front (for local mode use `cd ..; ./scripts/build-front.sh` instead of `npm run build`)

Il est donc utilisé dans une phase de build.

Le TypeScript `webapp/src/i18n.ts` existe bien, mais pas le fichier JavaScript.

## Environment

- [x] Development

**Comment by laurent-laporte-pro** [comment]
Merci pour la correction.

Lorsque je lance le script, le fichier `i18n.js` est modifié comme suit:

```diff
diff --git a/webapp/src/i18n.js b/webapp/src/i18n.js
index 376a0e2c..dd2da8e4 100644
--- a/webapp/src/i18n.js
+++ b/webapp/src/i18n.js
@@ -19,7 +19,7 @@ export default function i18nInit(version = "unknown") {
     .init({
       fallbackLng: "en",
       backend: {
-        loadPath: () => `/locales/{{lng}}/{{ns}}.json?v=${version}`,
+        loadPath: `/locales/{{lng}}/{{ns}}.json?v=${version}`,
       },
       react: {
         useSuspense: false,
```

Dois-je commiter les changements ?

**Comment by skamril** [comment]
Oui je vais ajouter le changement
