### ISSUE TITLE
Validation failed on new Xpansion canditate

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1373]
## Description

A `CandidateNameIsEmpty` exception is raised when creating an unnamed candidate in Xpansion's create new candidate dialog.

### Steps to reproduce the behavior:

1. Open a study;
2. Click on the "XPANSION" tab, then on "CANDIDATES;
3. Click on the Plus button "⊕" to create a candidate, the "New Candidate" dialog box will appear;
4. From the "Link" drop-down list, select a link;
5. The "SAVE" button becomes active, click on it.

## Actual Behavior

When you click on the "SAVE" button, you get the following error:

```text
Failure to create the candidate

Status : 400
Exception : CandidateNameIsEmpty
Description : Bad Request
```

## Expected Behavior

(none)

## Screenshots

![xpansion_nouveau_candidat](https://user-images.githubusercontent.com/43534797/222782743-b9ec6e2e-ca96-4fdb-8133-37558068889d.png)

## Possible Solution

In my opinion, the button should remain inactive until all required fields have been filled in.

On the other hand, the 400 error should be managed at the UI level.

## Environment

- [x] Production (not checked)
- [x] Staging

### Add any other context about the problem here.

- For instance: https://antares-web-recette.rte-france.com/studies/aceeccc7-b56e-44da-b8b4-514dcf556580/explore/xpansion

**Comment by skamril** [comment]
I add validation for "Link" and "Annual cost per MV" fields too.
