### ISSUE TITLE
[ANT-667] Wrong frequency for binding constraints matrices

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1383]
Set matrice frequency relative to the binding constraints frequency:

  -  [ ] if "type" = "hourly" -> **hourly**
  -  [ ] if "type"= "daily" -> **daily**
  -  [ ] if "type"= "weekly" -> **daily**

Location: check the TODO in "AntaREST/antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py"

**Comment by makdeuneuv** [comment]
For type daily we have hourly in the matrix
