### ISSUE TITLE
Permission issues for executables in the Linux package

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1397]
Currently, it's necessary to make 2 files executable after dezipping the archive
- **AntaresWeb/AntaresWebServer**
- **AntaresWeb/antares_solver/antares-8.4-solver**

It would be better if these files had execute permissions by default. According to [this SE thread](https://unix.stackexchange.com/questions/313656/preserving-permissions-while-zipping), it's possible to preserve permissions in zip archive.

TAR preserves permissions, so that's another option.

**Comment by laurent-laporte-pro** [comment]
Fixed in v2.14.4
