### ISSUE TITLE
Add timestamp in results

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1409]
## Problem Statement

In the "results" tab, it's currently impossible to determine what timestamp corresponds to a given entry.

![image](https://user-images.githubusercontent.com/26088210/226659414-fac0db02-1f6e-42ff-a84f-998c9593cc96.png)

## Proposed Solution

Add a special column that contains the timestamp (hour, day, week, etc.)

![image](https://user-images.githubusercontent.com/26088210/226659583-b28c8169-10d2-4c2d-9424-2530549bb22c.png)

## Developer Notes

- Any potential roadblocks or concerns: [e.g. dependencies on other features, limitations in technology]

**Comment by MartinBelthle** [comment]
## Example of `Results` view:

It's currently impossible to determine what timestamp corresponds to a given entry.

![results](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/effbb71d-6930-43f7-a40d-54bb2a44d447)

## Proposed Solution

Add a special column that contains the timestamp (see below the debug view of the same matrix)
Probably just remove the colum `Time` as it is already registered in the matrix index.

![debug](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/0ce3c5d3-fc94-41a4-b74f-fcba9f06de23)

## Developer notes

The API call raised when going on the view `Results` for this example is the following :    
1. GET `/studies/study_id/raw?path=matrix_path`


The APi calls raised when going on the `Debug ` view are the following : 
1. GET `/studies/study_id/raw?path=matrix_path`
2. GET `/studies/study_id/matrixindex`
3. GET `studies/study_id/matrixindex?path=output/matrix_path`

I do not see the real use of the 2nd API call here but at least we see the matrix index.
The same API call should be raised in both cases to solve this issue (investigate about the 2nd API call which seems odd).

**Comment by MartinBelthle** [comment]
Actually this is the same issue as https://github.com/AntaresSimulatorTeam/AntaREST/issues/1670

**Comment by laurent-laporte-pro** [comment]
The anomaly is not entirely resolved; evidently, there is a new issue regarding this issue: in the "weekly" or "annual" view of the results, the displayed date is "invalid date".

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/f5d0493a-1591-4e02-9d47-1764839bd455)

See study `ce14cbd5-7c6e-4fb6-a478-412a6e768979` on production server.

**Comment by laurent-laporte-pro** [comment]
# Matrix indexes/frequency

The row labels (indexes) are a function of the frequency of the time series.

## hourly matrix:

The index data is a date-time string with the format **"MM/DD HH:MM"**.
For example: '07/01 00:00', '07/01 01:00', '07/01 02:00', '07/01 03:00'…

In the legacy IHM, the index format is `"DD MMM HH:MM  I"`, where `I` is the 1-based index of the time series in the matrix.

![output-hourly](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/2efe8870-8358-41ee-abf9-d798a943446e)

## daily matrix:

The index data is a date string with the format **"MM/DD"**.
For example: '07/01', '07/02', '07/03', '07/04', '07/05'…

In the legacy IHM, the index format is `"DD MMM  I"`.

![output-daily](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/5ed29341-626d-4388-9deb-25cab74e843c)

## weekly matrix:

The index data is a week number with the format **WW**, where `WW` is the week number.
For example: 26, 27, 28, 29, 30, 31, 32, 33, 34, 35…

In the legacy IHM, the index format is `"WW`.

![output-weekly](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/bb09b03e-dcf7-4ad2-a101-ee9aaa02d928)

## monthly matrix:

The index data is a month number string with the format **'MM'**, where `MM` is the month number.
For example: '07', '08', '09', '10', '11', '12', '01', '02'…

In the legacy IHM, the index format is `"MMM  I"`, where `I` is the 1-based index of the time series in the matrix.

![output-monthly](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/ff6c2e9b-67e0-4f47-8bc8-2dce8ac9a362)

## yearly matrix:

The index data is the string **"Annual"**.

In the legacy IHM, the index format is `"Annual"`.

![output-annual](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/62b32f4c-f39e-47d8-b8cc-5f31b2e36449)
