### ISSUE TITLE
Studies list loading performance

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/AntaREST#1435]
## Problem Statement

When study list is not in cache, the loading of studies from database takes 30s for our 6000 studies.

## Proposed Solution

To minimize the occurrence, 2 main possibilities:
- minimize cache misses: we could increase the cache expiration time (one hour today)
- optimize the retrieval of studies metadata from database:
  the poor performance may be linked to lazy loading of "owner info" and "additional data" of studies, which probably leads to 6000*2 additional requests to database, in our situation, see for example here:
  https://github.com/AntaresSimulatorTeam/AntaREST/blob/1ff7d63e4fb7358165f5175501a9400e0927ca5f/antarest/study/common/utils.py#L23-L24

**Comment by laurent-laporte-pro** [comment]
https://github.com/AntaresSimulatorTeam/AntaREST/pull/1848
