### ISSUE TITLE
Invalid "Free Data Sample" study [desktop]

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1442]
## Description

Avec Antares Web Desktop, est livée une étude exemple nommée "000 Free Data Sample" qui se trouve en version v8.2.

Or, la simulation de cette étude ne fonctionne pas avec le solveur Antares Solver v8.5.0.

### Steps to reproduce the behavior:

1. Lancer une simulation avec cette étude.

## Actual Behavior

Nous avons le message d'erreur "Stochastic TS stored in input : study must be upgraded to 8.5" dans les logs:

```shell
W0405 18:05:25.396062 23940 environment.cc:2239] Environment variable XPRESSDIR undefined.
E0405 18:05:25.396333 23940 environment.cc:2302] NOT_FOUND: Could not find the Xpress shared library. Looked in: [C:\xpressmp\bin\xprs.dll', 'C:\Program Files\xpressmp\bin\xprs.dll]. Please check environment variable XPRESSDIR
[Wed Apr  5 18:05:25 2023][solver][check] Antares Solver v8.5.0 (15377ba)
[Wed Apr  5 18:05:25 2023][solver][infos]   :: built for 64-bit architectures, Microsoft Windows, 8 cpu(s)
[Wed Apr  5 18:05:25 2023][solver][infos]   :: hostname = Terreur
[Wed Apr  5 18:05:25 2023][solver][infos] 
[Wed Apr  5 18:05:25 2023][solver][infos]   :: from C:\Users\JohnDoe\Downloads\AntaresWeb-windows-latest\AntaresWeb\antares_solver
[Wed Apr  5 18:05:25 2023][solver][infos]   :: log filename: C:\Users\JohnDoe\Downloads\AntaresWeb-windows-latest\tmp\local_launch_2oty71wn\export\logs\solver-20230405-180525.log

[Wed Apr  5 18:05:25 2023][solver][infos] 
[Wed Apr  5 18:05:25 2023][solver][notic] Preparing 000 Free Data Sample...
[Wed Apr  5 18:05:25 2023][solver][infos]   detected version: 820
[Wed Apr  5 18:05:25 2023][solver][infos]   from `C:\Users\JohnDoe\Downloads\AntaresWeb-windows-latest\tmp\local_launch_2oty71wn\export`
[Wed Apr  5 18:05:25 2023][solver][infos] 
[Wed Apr  5 18:05:25 2023][solver][infos]   simulation mode: Economy
[Wed Apr  5 18:05:25 2023][solver][infos]   simplex optimization range: week
[Wed Apr  5 18:05:25 2023][solver][infos] Aggregate renewables were chosen. Output will be disabled for renewable clusters.
[Wed Apr  5 18:05:25 2023][solver][infos]   :: enabling the 'year-by-year' mode
[Wed Apr  5 18:05:25 2023][solver][infos]   :: ignoring export mps

[Wed Apr  5 18:05:25 2023][solver][infos]   :: ignoring adequacy patch
[Wed Apr  5 18:05:25 2023][solver][infos]   :: ignoring export structure
[Wed Apr  5 18:05:25 2023][solver][error] Stochastic TS stored in input : study must be upgraded to 8.5
[Wed Apr  5 18:05:25 2023][solver][infos] [statistics] disk: read: 2 ko, written: 0 ko
[Wed Apr  5 18:05:25 2023][solver][infos] [statistics] network: read: 0 ko, written: 0 ko
[Wed Apr  5 18:05:25 2023][solver][error] Got a fatal error reading the study.
[Wed Apr  5 18:05:25 2023][solver][error] Aborting now. See logs for more details
```

## Expected Behavior

Describe what you expected to happen.

## Screenshots

(none)

## Possible Solution

Actuellement, la seule solution pour l'utilisateur est de faire une mise à niveau de l'étude en v8.5,
dans ce cas, la simulation fonctionne bien.

## Environment

- Antares Web Desktop v2.13.1

### Add any other context about the problem here.

- Lien vers l'étude: [000 Free Data Sample](https://github.com/AntaresSimulatorTeam/AntaREST/blob/9e9e47d57bb223cf54853be25d0ccc002f14c55d/resources/deploy/examples/studies/example_study.zip)

**Comment by laurent-laporte-pro** [comment]
@flomnes, I would like to know if this study is configured correctly.

Is this a case of incompatibility between version 8.2 of the study and the version 8.5 of the sorlver? Or is this a case where the sample study needs to be upgraded?

**Comment by makdeuneuv** [comment]
Antares simulator à partir d'une certaine version (je ne l'ai plus en tête) ne prend plus en charge la sauvegarde dans les input du  Stochastic TS. Il faut donc décocher la sauvegarde au niveau des input dans configuration > Time series management . Et la simulation se lance correctement. Ce n'est pas en bug en soit.

**Comment by flomnes** [comment]
Je propose de supprimer cette étude, et de la remplacer par une copie pour laquelle l'option "store in input" est désactivée.

**Comment by MartinBelthle** [comment]
In the new release 2.14.3, the study is in version 8.5 so this issue is no longer relevant.
