### ISSUE TITLE
Duplicate fields in thermal clusters form

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1453]
## Description
In the thermal clusters view, the number of units and nominal capacity fields are duplicated
Provide a clear and concise description of the issue.

## Steps to Reproduce
Any study with a thermal cluster has these fields duplicated in the form. Even when creating a new cluster

## Expected Behavior
The Number of Units and Nominal Capacity fields should not be duplicated.

## Screenshots
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/114937156/232430824-f376d2d9-4dc3-4a8a-9482-839bf5e46d97.png)

## Environment
- [x] Production
- [x] Staging

**Comment by laurent-laporte-pro** [comment]
### Integration tests

⇨ Correction OK ✅
