### ISSUE TITLE
Inconsistency in the API URL prefix for the Desktop version of AntaresWeb

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1457]
## Description
In local (desktop) version for AntaresWeb, we expect to find a url as on the client/server version concerning the api, namely /api following the url, therefore http://localhost:8080/api. Except that instead we have http://localhost:8080/v1.
It is not intuitive and the user does not know that it is necessary to put /v1 instead of the url of the local version.

## Expected Behavior
This should therefore be modified so that the url of the api on the local version is http://localhost:8080/api

## Additional Information
It's on AntaresWeb desktop for Windows. We don't have check this on Linux version.

**Comment by laurent-laporte-pro** [comment]
Il doit y avoir un problème de redirection d'URL côté gunicorn:

Si on rafraîchit la page, par exemple `http://127.0.0.1:8080/studies/03e3ce4b-8767-4196-8270-897697312d05`, on obtient systématiquement une erreur 404 Not Found

**Comment by makdeuneuv** [comment]
In v2.14.4 it's  http://localhost:8080 url for api.

**Comment by laurent-laporte-pro** [comment]
Les URLs sont maintenant corrigées. L'URL pour l'API est `http://localhost:8080/api/v1/toto`.
