### ISSUE TITLE
Bug on displaying of layers and districts

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1458]
## Description
The layers and districts present are not displayed and even those newly created.

## Steps to Reproduce
- take a study whom have some layers and district.
- Go to the map and go see the layers and districts

You can also follow this steps to reproduce
- Create a new study
- add few areas and links
- create a layer with two areas
- go back to the map
- and try to see the layer create previously

## Screenshoots
![image](https://user-images.githubusercontent.com/114937156/232524697-f3258c77-f2db-4921-a635-1f335d661bd4.png)

## Additional Information
This issue is on all the versions of AntaresWeb (desktop, server).

**Comment by makdeuneuv** [comment]
Le bug est présent en recette et en prod.

**Comment by hdinia** [comment]
C'est fix, mais le correctif n'a pas encore été déployer visiblement
