### ISSUE TITLE
Issue with "Last day" field in Configuration > General

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1459]
When "Leap year" is enabled, it's not possible to set "Last day" field with the value 366

**Comment by laurent-laporte-pro** [comment]
### Integration Tests

✅ La vérification sur le champ "Last Day" se fait bien.
❌ Le message d'erreur n'est pas traduit en Français.

![configuration_general_last_day](https://user-images.githubusercontent.com/43534797/235972034-c9df0613-8f0b-47a1-9ac7-a5e2bece960f.png)

❌ Lorsqu'on change des valeurs dans la section "Calendrier", on obtient un message d'erreur HTTP 422 :First day, last day and leap year fields must be defined together

![configuration_general_validation_error](https://user-images.githubusercontent.com/43534797/235972117-5dbb1098-bdff-4d9e-8539-b2eb9c0b50ad.png)

❌ Les noms des champs dans la section "Calendrier" me semble incohérent : on a par exemple "Horizon" pour un champ contenant une année "2017"

![configuration_general_field_names](https://user-images.githubusercontent.com/43534797/235973172-42e6dbe5-5e79-4ad5-8826-5d3181fdf9f1.png)


⇨ Correction KO ❌ : le formulaire n'est pas utilisable.
