### ISSUE TITLE
No login page - desktop version

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1468]
## Description
When you launch the desktop server and go to the url http://localhost:8080 you are directly connected to the application.

## Actual Behavior
There is no possibility to have several users in the event that one wishes to install this version on a machine accessible by two users or even more. The user that appears on the studies created on the application is the admin user. But it does not allow you to create others users. And there is also no way to disconnect.

## Additional Information
It's on AntaresWeb desktop for Windows. We don't have check this on Linux version.

**Comment by laurent-laporte-pro** [comment]
Pour moi c'est un comportement normal car la version Desktop ne possède pas de module d'authentification de type LDAP / ActiveDirectory. Néanmoins, on doit pouvoir mettre en place l'authentification basique de type login / mot de passe gérée en base de données.

**Comment by makdeuneuv** [comment]
Oui l'objectif est de permettre à l'utilisateur admin de créer d'autre utilisateur avec un mot de passe et leur permettre de se connecter à l'application. Mais ce n'est pas le ticket le plus urgent sur le desktop.

**Comment by makdeuneuv** [comment]
Fermeture de l'issue car il s'agit d'un comportement normal.
