### ISSUE TITLE
Bug on the map, it no longer appears in some cases - Desktop version

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1469]
## Description
When exploring a study and leaving immediately and after go exploring another one, the map of the new study does not display the zones.
However, it displays the labels of the layers of the previous study.
We have to go back to the initial url http://localhost:8080 in the browser's address bar because an F5 doesn't work (it returns _{"detail":"Not Found"}_ ).

This case only happens when you go first to consult a large study (several zones and links and layers) then a small study (3 zones, 2 links, 1 layers). Seen below screenshot of the consultation of the second study (the smallest) with the layers labels of the first study (the biggest).

## Screenshots
![image](https://user-images.githubusercontent.com/114937156/233009805-e8769090-0f29-456d-8ba9-9482f1085589.png)

## Additional Information
It's on AntaresWeb desktop for Windows. We don't have check this on Linux version.

**Comment by laurent-laporte-pro** [comment]
~May be related to #1457~

**Comment by makdeuneuv** [comment]
Update : in v2.14.4 the F5 works and the areas appears in the map. But in first time, when we go exploring another study after leaving the first we always haven't the areas displayed. We need now to refresh with F5. 
P.S.: The issue not present anymore in client server version.

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv , est-ce que tu pourrait nous donner plus de détails avec éventuellement des copies d'écran ?

**Comment by makdeuneuv** [comment]
Étapes pour reproduire :

1. Consulter la map d'une importante étude comportant de nombreuses zones (plus de 100) et liens (plus de 300), ainsi que plusieurs layers (plus de 5), puis quitter cette étude.
2. Aller consulter la map d'une étude plus petite avec très peu de zones (moins de 10) et liens (moins de 10), ainsi qu'un seul layer.
3. Les zones de la petite étude n'apparaissent pas et la map est vide. Cependant, les layers de l'étude précédemment consultée sont affichés.

Dans la version 2.14.4, en appuyant sur F5, la map de la petite étude s'affiche correctement. Ce bug ne se produit que dans le cas où une grosse étude est consultée suivie d'une petite étude, uniquement dans la version desktop.

**Comment by makdeuneuv** [comment]
Le bug ne se reproduit plus (version 2.16.7).
