### ISSUE TITLE
Presence of tasks from a deleted study in the task view.

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1470]
## Description
When you delete a study that has tasks and these are still present in the application's tasks page, the name of the study no longer appears in the list. Instead we have the Unknown name followed by the study ID.

And when you click on it to be redirected to this study that has been deleted, we have an empty page that grinds and returns nothing.

## Possible Solution
As a solution, after deleting the study, remove all of its tasks from the tasks page. or again, if one clicks on a task called Unknown (study id) the user receives a message informing them that the study no longer exists (because it has been deleted).
And when you click on it to be redirected to this study that has been deleted, we have a black page that grinds and returns nothing.

## Screenshot
![image](https://user-images.githubusercontent.com/114937156/233014522-96c865b3-fc33-4777-b982-158d6a8da24e.png)

## Environment

- [x] Production
- [x] Staging
- [x] Desktop

**Comment by MartinBelthle** [comment]
An easy quick win concerns the jobs (also the example in the screenshot above). Currently when clicking on the Tasks View, the API call GET /jobs is made with `filter_orphans`=False. It should be True and any job belonging to a deleted study will disappear from this view.
