### ISSUE TITLE
Missing database indexes

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/AntaREST#1484]
## Problem Statement

The alembic scripts don't create database indexes, whereas the application performs some requests that would benefit from it.

We need to list all indexes that are missing by inspecting all `repository` modules:

- `job_result` table:
  - `study_id` is used for search but not indexed
- ...

**Comment by makdeuneuv** [comment]
!sera traité dans la tâche jira ANT-1035
