### ISSUE TITLE
Ajout de filtre dans une requête API

### ISSUE THREAD

**Issue by TitouanRobert** [AntaresSimulatorTeam/AntaREST#149]
Bonjour à tous,

Il pourrait être intéressant de pouvoir filtrer un sous ensemble de données quand on fait une requête à l'API. Par exemple : 
Je souhaites récupérer la totalité des données horaires pour la totalité des areas et pour les MCind 1, 2 et 4

Un exemple de chemin : 
antaresStd\output\20201015-0957eco-test3a\economy\mc-ind\00001\areas\at\values-hourly

Pour réponde à cette requete l'API offre aujourd'hui 2 possibilités : 
Requêter les fichiers un à un et faire des boucles.
Requêter directement tout depuis antaresStd\output\20201015-0957eco-test3a\economy\mc-ind\ er ramener énormément d'informations par forcement utile pour la requête considérée.

Un développement intéressant serait de pouvoir entrer une requête de la façon suivante : 
antaresStd\output\20201015-0957eco-test3a\economy\mc-ind\ **[00001, 00002, 00004]** \areas\ **[*]** \values-hourly

Les blocs en gras indique les endroits ou l'on veut plusieurs éléments d'un coup (ici les mc-ind 1, 2 et 4 pour le premier et la totalité des areas symbolisées avec le caractère *).

La forme (les crochets et l'étoile) est un exemple on peut imaginer d'autres caractères pour réponde à cette demande!

Je ne connais la complexité du développement, ni si il est pertinent pour tout le projet mais je penses qu'il pourrait être utile de notre côté!

Disponible pour en discuté et pour plus de renseignement si ce n'est pas claire, n'hésitez pas.

Merci pour tout.

**Comment by pl-buiquang** [comment]
la forme plus canonique pour ce genre de requête étant tout simplement les valeurs séparées par des virgules sans les crochets.
`antaresStd/output/20201015-0957eco-test3a/economy/mc-ind/00001,00002,00004/areas/*/values-hourly`
