### ISSUE TITLE
[UI] Duplicate inputs in thermal cluster form

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/AntaREST#1494]
## Description

In thermal cluster form, "Nombre d'unités" and "Capacité nominal" seem duplicated:
![image](https://user-images.githubusercontent.com/6557571/235671874-01d3b735-a624-461a-877d-bd9db0e63740.png)

**Comment by hdinia** [comment]
Thank you for reporting this anomaly, it has already fixed in this PR: https://github.com/AntaresSimulatorTeam/AntaREST/pull/1456
