### ISSUE TITLE
[ANT-659] Refactor some old forms

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1504]
Refactor theses forms below and remove auto submitting:

- [x] Modelization > Areas > Thermal
- [x] Modelization > Areas > Renewables
- [ ] Modelization > Binding Constraints
- [ ] Modelization > Links

**Comment by laurent-laporte-pro** [comment]
Il faudrait voir avec @JasonMarechal25 pour intégrer les nouveautés des binding constraints.
