### ISSUE TITLE
Impossible to add new area in a layer or district

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1507]
## Description
We can't add new areas on a layer or a district after we have deleted some old areas whom been there.

## Steps to Reproduce
- create a study with 4 zones
- add a layer
- add zone 2 and 4 to this layer
- delete all areas of the study
- create 6 new areas with new names
- add 2 of these new areas in the layer or in the "All areas" district
- A 404 error appears with the message "zones not found" with the zone names of those that have been deleted

Temporary fix, you have to delete the layer or district and create a new one to be able to add the new areas. 

## Expected Behavior
There should be no errors when adding new areas to the layer or district.

## Screenshots
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/ac599bd0-a22b-44f3-9316-31498dacaaa8)

## Environment
- [ ] Production
- [x] Staging

**Comment by hdinia** [comment]
@makdeuneuv  Thanks for reporting the issue, I'll investigate on that one. Seems related to the API

**Comment by makdeuneuv** [comment]
The issue still present with another log message. Here error 500 KeyError.

![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/a97098ae-8974-4407-8798-48cfce773682)

**Comment by makdeuneuv** [comment]
Now we can add new area on a district but we can't' make it for layer

**Comment by makdeuneuv** [comment]
Bug toujours présent, je laisse @laurent-laporte-pro voir si les merges en dev et le déploiement ont été bien effectué (car le soucis est présent dans plusieurs autres tickets où le correctif n'est pas présent après déploiement de la branche.)

**Comment by makdeuneuv** [comment]
@hdinia The issue still present, you say there is a PR related to the issue. Can you link the both please? thanks! I move the issue in Review state.

**Comment by hdinia** [comment]
@makdeuneuv The bug mentioned in this issue has been corrected, but you may still encounter errors related to other problems in map state management (for example, when you delete areas and create new ones, then try to add them to a layer, the information from the old deleted areas is sent in addition to the new ones, resulting in an error). 
there are also other minor problems that I mention in this ticket that I opened, so I'm closing this one, which is well resolved, and I'm going to give priority to this new ticket, which is linked. Please check: https://github.com/AntaresSimulatorTeam/AntaREST/issues/1565
