### ISSUE TITLE
Retrieving users list is slow and causes timeouts

### ISSUE THREAD

**Issue by sylvlecl** [AntaresSimulatorTeam/AntaREST#1521]
## Description

On the "studies" screen (and probably others), the web application performs a request to get users details:
`<url>/api/v1/users?details=true`

This requests is very slow on prod environment, from a few seconds to 30+s, which in the end causes HTTP 500 errors.

As in issues #1435 , #1483 and #1484, there is probably some important improvement to implement in database requests, to improve that situation.

**Comment by makdeuneuv** [comment]
Relates to #1435, #1483 and #1484.
