### ISSUE TITLE
Modifying a value in the front does not raise an API call

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1530]
## Description

Go to this view : ![cout_non_modifie](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/caba1b01-8fa2-4200-bf83-3e366ad7b399)
Modify any value in the "Coût de l'énergie" form and save your changes.
You will see that your changes are not taking into account because no API call is raised.

## Solution

Modifying the form should raise and API call with the command Update_config of the file input/thermal/areas.ini

**Comment by makdeuneuv** [comment]
Le bug semble être corrigé en 2.14.3 en prod (vérification faites sur une étude).
@skamril si tu confirmes, je te laisse clôturer le ticket (car je ne sais pas quelle PR était associée à sa résolution). Merci

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv , c'était une PR orpheline.
