### ISSUE TITLE
[ANT-758] No data available on view results 

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1541]
## Description
For the areas, I only asked for the annual results in summary; in AntaresWeb impossible to see them.
But when the results is downloading on disk they are there.

## Screenshots
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/5c40d8f0-ac42-4725-9e4f-29867cdf9be7)

## Environment

- [x] Production
- [x] Staging

## Additional Information
Study: e1d5f541-c049-45ed-a093-b67a4f670ff3 (in Production)
Results: 20230530-0716eco

**Comment by laurent-laporte-pro** [comment]
May be related to #1351

**Comment by makdeuneuv** [comment]
Remarques faites par Sylvain, lorsqu'on rafraîchi la page on a les résultats qui s'affiche. Probablement un problème de front plus que de back-end.

**Comment by makdeuneuv** [comment]
bug résolu en 2.14.4.
