### ISSUE TITLE
General and operating parameters for renewable are not displayed

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1544]
## Description
The characteristics of renewable clusters are not displayed. This information is however visible in debug mode.
It concern managed and disk studies.

## Steps to Reproduce
Take any study with renewable clusters and consult one of them

## Expected Behavior
This characteristics appears in the previous versions, we need to go back to the previous behavior.

## Screenshots
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/21886cb2-5ec9-4b1b-9c93-ea62bd74e49b)

## Environment

- [x] Production
- [x] Staging

**Comment by laurent-laporte-pro** [comment]
La stack trace indique ceci :

```python
pydantic.error_wrappers.ValidationError: 1 validation error for RenewableFormFields
response -> nominalCapacity
  value is not a valid integer (type=type_error.integer)
```

La valeur lue depuis le fichier de configuration est :

```python
{
  'group': 'Solar PV',
  'name': 'at_solar_pv',
  'nominalcapacity': 10600.0,
  'ts-interpretation': 'production-factor',
  'unitcount': 1
}
```

En d'autres termes, nous avons un `float` au lieu d'un `int`. Si je change manuellement en `int`, cela fonctionne bien.
