### ISSUE TITLE
bug on the correlation form

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1547]
## Description

Provide a clear and concise description of the issue.
### Steps to reproduce the behavior:
1. Go to area, choose an area
2. Go to the Hydro tab then correlation
3. Go to the field "add a zone"
4. Choose an area and it appears at the top of the form and the field next to it flashes without displaying a value
5. Then click save
6. Error 500 appears

## Screenshots
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/d76870d0-fc8c-4473-89fd-2d6834d81782)

## Environment

- [x] Production
- [x] Staging
## Additional Information
Example of study in integration 0d7653a2-99d4-4bdb-b353-3b7b5b090262

**Comment by laurent-laporte-pro** [comment]
On n'arrive pas à reproduire le bug.

**Comment by makdeuneuv** [comment]
Bug produit en intégration et prod (id étude en prod 41d20487-7f06-4125-8b1b-9cc5e9ce5ce7, id étude en intégration 0d7653a2-99d4-4bdb-b353-3b7b5b090262).
En somme, lorsque tu cliques sur une zone et que tu souhaites ajouter une autre pour la corrélation, le champ où l'on doit mettre le pourcentage de correlation clignote (comme le cas du bug sur le formulaire des clusters renouvelables).
Et quand on clique sur sauvegarder il y a l'erreur 500.

Par contre, sur une étude qui avait déjà sa configuration Hydro avant importation sur Antares web n'a pas ce bus. Le bug s'est produit quand j'ai créé une étude 8.5 et que j'ai voulu créer cette corrélation à partir de zéro sur une zone.

Il faudrait je pense valider avec l'équipe fonctionnelle le fonctionnellement nominale de la corrélation quand on crée une étude à partir de zéro ; est-ce qu'il faudrait mettre par défaut la zone elle-même et ensuite l'utilisateur ajoutera des zones supplémentaires avec un pourcentage de corrélation ?
Par défaut une zone a un pourcentage de corrélation à 100% vis-à-vis d'elle même (c'est le constat fait sur l'étude qui n'a pas le bug).

**Comment by hdinia** [comment]
moved to #1593
