### ISSUE TITLE
[ANT-760] TS eager update is very slow

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1548]
La mise à jour groupée de plusieurs cellules dans une colonne de série temporelle peut être très longue s'il y a beaucoup de valeurs sélectionnées. C'est notamment le cas lorsqu'on sélectionne toute une colonne de 8760 lignes. On remarque des temps de mise à jour de l'ordre de plusieurs secondes, voir dizaines de secondes.

![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/29ac8dc2-ff4c-489e-94bb-c6c093e8cd91)

Pour reproduire :
- Ouvrir, par exemple, un cluster thermique,
- Dans une matrie, sélectionner un groupe de cellules,
- Saisir une value et faire Ctrl+Entrée pour valider la saisie pour toutes les cellules sélectionnées.

Information complémentaires:

La requête envoyée est une requète PUT avec les données suivantes :

PUT `/v1/studies/5663be9f-a058-4dab-8f15-12df7868d3d3/matrix?path=input/thermal/prepro/at/at_ccgt%20new/modulation`

```json
[
  {
    "coordinates": [[4, 0]],
    "operation": {
      "operation": "=",
      "value": 120
    }
  },
  {
    "coordinates": [[5, 0]],
    "operation": {
      "operation": "=",
      "value": 120
    }
  },
  {
    "coordinates": [[6, 0]],
    "operation": {
      "operation": "=",
      "value": 120
    }
  },
  {
    "coordinates": [[7, 0]],
    "operation": {
      "operation": "=",
      "value": 120
    }
  },
  {
    "coordinates": [[8, 0]],
    "operation": {
      "operation": "=",
      "value": 120
    }
  },
  {
    "coordinates": [[9, 0]],
    "operation": {
      "operation": "=",
      "value": 120
    }
  }
]
```

**Comment by laurent-laporte-pro** [comment]
Il faudrait gérer des slices (ranges) :

```python
{
    "slices": [
        {"row_from": 0, "row_to": 8760, "column_from": 0}
    ],
    "operation": {
        "operation": "=",
        "value": 1,
    },
}
```

**Comment by makdeuneuv** [comment]
Le correctif n'est pas effectif en intégration, lorsque l'on sélectionne un groupe de ligne puis que l'on saisit la valeur souhaitée puis Ctrl+Entrée on a bien la notification comme quoi la matrice a été mise à jour. Mais si l'on change d'onglet puis que l'on revient, on constate que la mise à jour n'a été prise en compte que sur la première ligne (les autres ont l'ancienne valeur)

**Comment by laurent-laporte-pro** [comment]
fixed in v2.14.3 #1597
