### ISSUE TITLE
[ANT-763] Set by default "Public mode" to "Read" on importing a study (When user have no groups)

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1559]
## Problem Statement

As an user, when I import a study on Antares Web, the "Public mode" must be set to "Read" by default. Do this only when the user who importe the study doesn't have any groups affected to him.

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/7eb3dbc0-dca6-439d-949d-8ca9a7c5b957)

**Comment by MartinBelthle** [comment]
Any particular reason the mode should be READ ? 

It could be one of them (probably EDIT is better no ?): 
```python
 class PublicMode(str, enum.Enum):
    NONE = "NONE"
    READ = "READ"
    EXECUTE = "EXECUTE"
    EDIT = "EDIT"
    FULL = "FULL"

**Comment by laurent-laporte-pro** [comment]
Bon, après analyse du code côté backend, bien qu'ils soient référencés, il semblerait que les modes publiques `EDIT` et `EXECUTE` ne soient pas réellement utilisés.

Cela dit, il m'est difficile de bien comprendre le rôle exact de ce type énuméré…

**Comment by MartinBelthle** [comment]
J'ai l'impression que c'est utilisé pour check les perimissions quand même. Pour pouvoir run une étude, il faut avoir soit FULL, EDIT ou EXECUTE, pareil pour éditer une matrice il faut être en FULL ou EDIT etc. Du coup mettre en EDIT permettrait de pouvoir tout faire (sauf supprimer l'étude) directement

**Comment by MartinBelthle** [comment]
J'ai fait mes tests et effectivement changer le public mode ne sert à rien quand on est owner on à déjà tous les droits. La seule raison que je vois de logique pour passer l'étude en `READ` c'est pour permettre à d'autres utilisateurs de la lire. Est-ce que tu pourrais nous éclairer sur la demande utilisateur @makdeuneuv ?

**Comment by laurent-laporte-pro** [comment]
Le paramètre de visibilité des études `PublicMode` devrait être défini sur "Lecture seule" (`READ`) afin que les autres membres du groupe puissent voir et lire les études importées. Il est essentiel de ne pas autoriser le mode "Modification" (`EDIT`) ni le mode "Exécution" (`EXECUTE`) pour empêcher toute modification ou exécution par les autres membres du groupe (afin d'éviter la production de nouveaux résultats).

**Comment by makdeuneuv** [comment]
Ce ticket est relatif au ticket #1560 qui consiste à assigner par défaut à l'étude les groupes de l'utilisateur qui l'importe.
Cependant, dans le cas où l'utilisateur n'a aucun groupe d'assigné (ce qui est rare mais arrive dans les premiers jours d'arrivés d'un nouvel utilisateur), il faudrait que le "Public mode" soit mit à Read. Je modifie la description de l'issue en conséquence.

**Comment by makdeuneuv** [comment]
Le correctif n'est pas effectif. Voici le comportement actuel après déploiement en recette : 
- Pour un utilisateur qui n'a aucun groupe d'assigné, lorsqu'il importe une étude, la dernière prend la valeur None dans le "Public mode"
- Pour un utilisateur qui a au moins un groupe d'assigné, lorsqu'il importe une étude, cette dernière prend la valeur None dans le "Public mode " et aucun des groupes de l'utilisateur ne lui est affecté.

Voici le comportement attendu : 
- Pour un utilisateur qui n'a aucun groupe d'assigné, lorsqu'il importe une étude, celle-ci prend la valeur Read dans le "Public mode"
- Pour un utilisateur qui un ou plusieurs groupes d'assigné, lorsqu'il importe une étude, l'étude prend la valeur None dans le "Public mode" ET tous les groupes de l'utilisateur sont affectés à l'étude.
