### ISSUE TITLE
[ANT-763] Assigned by default to a study imported all groups of the user

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1560]
## Problem Statement
As a user, when I import a study on Antares Web, the imported study must be assigned to all the groups to which I belong.
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/5e595203-2bf6-42d4-9af7-1e31d5bc4994)

It's possible for a study to be affected to multiple groups.

**Comment by MartinBelthle** [comment]
This issue is related to https://github.com/AntaresSimulatorTeam/AntaREST/issues/1559 because to reproduce the VMs group behaviour (which is what's asked in the initial user request), we need to assign the user groups to the study and put its PublicMode to None

**Comment by makdeuneuv** [comment]
Réouverture de l'issue car le besoin n'est pas rempli. Le besoin est le suivant : 
- Pour un utilisateur qui un ou plusieurs groupes d'assigné, lorsqu'il importe une étude, l'étude prend la valeur None dans le "Public mode" ET tous les groupes de l'utilisateur sont affectés à l'étude.
