### ISSUE TITLE
[ANT-763] Set the user name as author on file study.antares when we importe a study

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1561]
## Problem Statement

As a user, when I import a study on Antares Web, the Author field on the web interface take as value my user name but in the study.antares it not. We have the name of the previous author.
The request is to consider that the new imported study is adopted by the user who imports it, so he becomes the author.

**Comment by sylvlecl** [comment]
Not 100% sure we want to do this: it loses the track of who actually created the original study. 
Should we distinguish "author" and "owner" ?
Should we have a list of authors, to allow the co-existence of the original author and the user who imports the study ?

We also need to be careful about GDPR here, in the case we would like to keep the original author: we should probably not keep that information for a user that the application does not know.

**Comment by makdeuneuv** [comment]
Your remark is right. After a few verification, this feature is already implemented. When we import a study, antares web associate to the author field on the interface the user who made the import. But on the file study.antares the previous author is still mentioned and the user who made the import doesn't appear in the file (see the screenshot 1. the user who made the import and 2. the user in the file study.antares, first author).
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/92b62da0-3d27-4984-b037-a2c84c4100a0)

I will rename the issue and the demand.

**Comment by MartinBelthle** [comment]
After several discussions with Deneuv and Alexander, the following changes should be implemented in Antares Web:
- When creating a study, the `study.antares` file in Antares Web should include the user's name (previously, it was listed as "Unknown").
- When a user creates a variant in Antares Web, their name should be recorded in the `study.antares` file (previously, it was the same as the parent study).

**Comment by laurent-laporte-pro** [comment]
## Tests d’intégration sur mon PC

Bon, je ne sais pas si c'est cohérent ou non, mais si j'**importe** une étude de quelqu'un d'autre, j'en devient le propriétaire mais l'auteur n'est pas modifié dans le fichier `study.antares` :

![On study import, author is not changed](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/a4dc1171-b69b-4943-9146-d3a9cfa7d8d1)

Par ailleurs, je ne suis rattaché à aucun groupe et le `PublicMode` est à `NONE` ✅

![On study import, PublicMode is NONE](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/31a4cbc9-8992-4e1d-9ec4-65b19a23df3d)

> ~Veuillez noter que le tag que j'avais entré n'est pas restitué.~
> En fait, pour ajouter un tag, il faut saisir le texte du tag et taper Entrée. Puis il faut valider le formulaire. Si on ne tape pas Entrée, le tag que l'on a saisi est perdu.

**Comment by laurent-laporte-pro** [comment]
## Tests d’intégration sur mon PC

Si je **crée** une étude, j'en devient le propriétaire et l'auteur :

![On study creation, author is updated with login](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/3fc64800-d5e4-4356-ac34-0d37644a0da0)

Le mode publique correspond bien à ce que j'avais choisit ✅

![On study creation, PublicMode is correct](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/0f12c391-57dd-41ea-ad3c-0613e216d26b)

> Mais le tag n'est pas conservé ! 🤕

**Comment by MartinBelthle** [comment]
@laurent-laporte-pro  Quand tu dis importer, tu dis bien importer une étude que tu as sur ton PC en local (non vu par Antares Web) sur le serveur ? 

> Oui, il s'agit bien de l'import depuis une archive compressée au format ZIP, vers Antares Web
> – Laurent.

Si oui, le comportement attendu est de ne pas modifier l'auteur mais simplement l'owner (cf. message de Sylvain en haut de l'issue). 
Il faut aussi ajouter les groupes auxquels appartient l'owner (peut être que tu n'es dans aucun groupe). 
Si l'user n'a pas de groupe il faut passer le public mode à READ (demande non codée car ajoutée après ma PR) sinon NONE. 

Pour la création d'une étude cf. mon message plus haut dans l'issue (ça m'a l'air respecté d'après ce que tu montres).

En résumé, tout me semble correct, il ne reste qu'à coder le PublicMode à READ si l'user n'a pas de groupe

**Comment by laurent-laporte-pro** [comment]
## Tests d’intégration sur mon PC

Si je copie une étude en base (étude managée), je deviens propriétaire de l'étude mais l'auteur n'est pas modifié. Ce Comportement est identique à l'import d'une étude depuis une archive ZIP ✅

![On study management, owner is updated](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/cdc6f890-da0b-4e76-92cb-81e38b9e3cc1)

**Comment by laurent-laporte-pro** [comment]
## Tests d’intégration sur mon PC

Si je **crée un variant** d'une étude appartenant à quelqu'un d'autre, j'en deviens à la fois le propriétaire et l'auteur, ce qui me semble logique. ✅

![On variant creation, user become the author](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/d274240a-b3f9-490e-884a-96268384c828)
