### ISSUE TITLE
[ANT-764] Assigned by default to a study copied to database all groups of the user

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1564]
## Problem Statement

As a user, when I copy to database a study on Antares Web, the copied study must be assigned to all the groups to which I belong.

Related issue #1560

**Comment by laurent-laporte-pro** [comment]
What do you mean by "database" ?

**Comment by makdeuneuv** [comment]
It's translation for "copier en base". It's means copy a local study on antares web server as a managed study.

**Comment by MartinBelthle** [comment]
This issue is related to #1563 because to reproduce the VMs group behaviour (which is what's asked in the initial user request), we need to assign the user groups to the study and put its PublicMode to None

**Comment by MartinBelthle** [comment]
The code does not exactly implement what's asked, it assigns all groups of the source study to the destination one.
What's asked:
- Assign the **user's groups** to the destination study.
- If the user has no groups, set PublicMode to READ (new demand).

In a nutshell, we should do the same thing we've done for IMPORT endpoint
