### ISSUE TITLE
Add Support for Microsoft Office documents in Antares Web API

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1573]
## Problem Statement

The Script team uses tools to generate studies in order to run simulations from Antares Web. Additional Microsoft Office Excel files are stored in the User directory. For example, an Excel sheet named "synthesys_windSolar.xlsx" is generated in the "/user/wind_solar" directory.

In order to standardize the development done in the R language, the Script team wants to use the Antares Web API instead of directly reading and writing files on the disk.

The current version of Antares Web allows reading and updating files using GET, POST, and PUT requests by specifying a path to the desired file. GET requests can also list the contents of directories, thus indicating the existence of files.

However, in the case of reading, only files in JSON format can be retrieved. In other words, it is not possible to read Microsoft Office files. Currently, the GET request `/v1/studies/{uuid}/raw` only provides JSON files.

This request proposes adding support for Microsoft Office formats when reading and writing documents in Antares Web.

Example URL: `/v1/studies/9cbd21b4-f9af-416f-8076-88173b1858b3/raw?path=%2Fuser%2Fwind_solar&depth=3&formatted=true`

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/9282b489-43f4-43e5-9ba7-81a7009a2de1)

## Proposed Solution

Detect the file's MIME type based on the path in the `raw_studies_blueprint.get_study` function.

The workaround is to use the JSON format instead of Excel.

**Comment by laurent-laporte-pro** [comment]
## Acceptance criteria

The `raw_studies_blueprint.get_study` end point should support Microsoft Office, LibreOffice, CSV, TSV, and Text files, in addition to JSON files.

1. When a GET request is made to `/v1/studies/{uuid}/raw` with a valid path to a Microsoft Office (e.g., .xlsx, .docx, .pptx), LibreOffice (e.g., .odt, .ods, .odp), CSV, TSV, or text file, the response should have the appropriate content type set based on the file format. For example, Excel files should have `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` as the content type.

2. The response body for Microsoft Office, LibreOffice, CSV, TSV, and text files should contain the actual file content in its original format, not converted to JSON.

3. If the requested file is not one of the supported formats mentioned above, the endpoint behavior should raise exception. The recommended status code is 415 - Unsupported Media Type.

4. The endpoint should correctly handle various file formats, such as .xlsx, .docx, .pptx, .odt, .ods, .odp, .csv, .tst, .txt, etc.

5. The existing functionality of the `raw_studies_blueprint.get_study` endpoint for JSON files should not be affected by this upgrade. JSON files should still be returned with the appropriate content type (`application/json`) and their original content.

6. The upgrade should be thoroughly tested to ensure that it works as expected and does not introduce any regressions or errors.

7. The code changes for the upgrade should follow the coding conventions and best practices of the project.

8. Documentation for the upgraded endpoint should be updated to reflect the new behavior and supported content types.

**Comment by laurent-laporte-pro** [comment]
Mapping between common file extensions and their corresponding content types:

- .xlsx (Microsoft Excel): `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
- .docx (Microsoft Word): `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
- .pptx (Microsoft PowerPoint): `application/vnd.openxmlformats-officedocument.presentationml.presentation`
- .odt (LibreOffice Writer): `application/vnd.oasis.opendocument.text`
- .ods (LibreOffice Calc): `application/vnd.oasis.opendocument.spreadsheet`
- .odp (LibreOffice Impress): `application/vnd.oasis.opendocument.presentation`
- .csv (Comma-Separated Values): `text/csv`
- .tsv (Tab-Separated Values): `text/tab-separated-values`
- .txt (Plain Text): `text/plain`

**Comment by makdeuneuv** [comment]
It's normal to still have this result after fixed this issue @laurent-laporte-pro ?


![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/1a0a0c38-59f9-4545-a524-f868a6fb1e92)

**Comment by makdeuneuv** [comment]
The issue reported still present. When we go to xlxs or docs files, we can't display it.

**Comment by MartinBelthle** [comment]
In fact, for these cases, the back-end sends a PlainTextResponse or a StreamingResponse because from what I saw with Hatim, the front expect the type `file` for these files. I tried to send a JsonResponse but it doesn't work for this reason.

There are 2 solutions:
- The front end continues to receive these files as such but needs to check the suffix of the path : (.csv, .xlsx, etc.) and according to this suffix, load the data and display it correctly.
- We can also do what's described just above in the back-end (probably more logic) but the front-end will have to expect other types / no types at all and I do not know if this is possible.

The first solution seems far more simple to me.

**Comment by laurent-laporte-pro** [comment]
> It's normal to still have this result after fixed this issue @laurent-laporte-pro ?
> 
> 
> ![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/1a0a0c38-59f9-4545-a524-f868a6fb1e92)

L'objectif initial de la demande (de l'équipe Script) était d'avoir un Endpoint pour téléverser des fichiers Excel dans l'arborescence `user`. La fonction de lecture existe déjà (le téléchargement via GET) mais elle n'était pas correctement implémentée. La fonction d'écriture (le téléversement via PUT ou POST) n'existait pas. D'où la PR.

L'affichage n'est pas très joli mais il faut se rappeler qu'on est dans la vue Debug. Donc, pour moi, c'est correct.
