### ISSUE TITLE
[ANT-761] Absence of the solver in the artifact of antares deskop

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1574]
## Description
Since v2.13.1 of antares web, the embedded solver 8.5.0 which should normally be in the folder AntaresWeb/antares_solver/ is not present because the folder _antares_solver_ is no longer there.

**Comment by flomnes** [comment]
Still present in v2.14.2

Also, even after adding the solver manually, it seems that the study folder is not provided to **antares-solver**

```
[2023-06-14 11:22:03][solver][0;31m[error][0m A study folder is required. Use '--help' for more information
```

**Comment by laurent-laporte-pro** [comment]
Corrigé dans la version v2.14.3

**Comment by makdeuneuv** [comment]
@laurent-laporte-pro  J'ai téléchargé la version 2.14.3 dans les github action et l'archive ne contient que le dossier AntaresWeb (absence des autres dossiers telles que Example, matrices, logs, etc). On ne peut donc pas tester la version desktop complète avec cet artifact.

**Comment by makdeuneuv** [comment]
L'arborescence a changé, nous avons maintenant un zip dans un zip. Le solver est bien présent dans l'artifact généré dans le github action.

**Comment by laurent-laporte-pro** [comment]
fixed in v2.14.3 #1597
