### ISSUE TITLE
Unknown version when we need to have the desktop app version

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1576]
## Description
When you go on the app name, the version and the commit need to be display. But we get "unknown (unknown)" see the screenshot
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/8e87d27a-fdce-4fd9-b8f3-4f6552b7bbd3)

the result of the api version http://[localhost:8080/version](http://localhost:8080/version) gave this :  _{"description":"Unexpected server error","exception":"CalledProcessError"}_

This issue appears since v2.14.2

**Comment by laurent-laporte-pro** [comment]
Aurais-tu les logs dans la console de l'application web afin de récupérer la stack trace ?

**Comment by laurent-laporte-pro** [comment]
ANALYSE:

En première analyse, la chaîne de caractères "unknown (unknown)" est utilisée par le _front end_ lorsqu'il tente de récupérer la version de l'application, mais que la récupération échoue : dans ce cas, il n'y a pas de gestion d'erreur et on retourne une valeur pas défaut.

Le code qui fait l'appel au _back office_ est implémenté par la fonction `getVersion` qui se trouve dans `webapp/src/services/api/misc.ts`, dont voici un extrait :

```ts
export const getVersion = async (): Promise<APIVersion> => {
  const res = await client.get("/version");
  return res.data;
};
```

NOTE : contrairement aux autres URL de l'API, cette URL n'est pas préfixée par "/v1", c'est peut-être là la subtilité.

**Comment by laurent-laporte-pro** [comment]
Je ne reproduit pas cette anomalie avec Antares Web v2.14.2 sous Windows :

![version_number_screenshot-v2 14 2](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/e2bc83fa-67c1-4d30-9c72-e5b873edd2ad)

**Comment by laurent-laporte-pro** [comment]
Par contre, le gitcommit ne s'affiche pas sous Ubuntu : le fichier doit manquer ou être mal positionné dans l'arborescence avant le build.

![version_number_screenshot-v2 14 2-Ubuntu](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/94f910e1-054f-40a8-a518-8a7804cacd78)

Extrait des logs côté console :

```log
INFO:     127.0.0.1:52790 - "GET /config.json HTTP/1.1" 404 Not Found
fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
INFO:     127.0.0.1:52790 - "GET /version HTTP/1.1" 200 OK
```

**Comment by laurent-laporte-pro** [comment]
Corrigé dans la version v2.14.3

**Comment by makdeuneuv** [comment]
En attente d'avoir un artefact du desktop pour tester.

**Comment by makdeuneuv** [comment]
Bug résolu dans la version 2.14.3
