### ISSUE TITLE
Missing key on correlation config for newly created study

### ISSUE THREAD

**Issue by hdinia** [AntaresSimulatorTeam/AntaREST#1593]
## Description

The correlation from is broken on new studies with empty configuration.
#### Reproducibility: 100%
1. Create new study
2. Create at least one area
3. Go to Explore > Modelization > Areas
4. Select an area
5. Go to > Hydro > Correlation
6. See KeyError (screenshot below)

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/33469289/6168dc78-2df8-48d8-910a-62efe8355fd4)

## Possible Solution

To fix this issue the key `annual` must be added to the ``correlation.ini`` on empty configuration 

## Invalid ``correlation.ini`` configuration:
```ini
[general]
mode = annual
```

## Expected ``correlation.ini`` configuration:
```ini
[general]
mode = annual

[annual]
```

**Comment by laurent-laporte-pro** [comment]
fixed in v2.14.3 #1597
