### ISSUE TITLE
Impossible to see thermal cluster form

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1599]
## Description
In production we have this issue, but it's not present on staging.
Id of the study 893f7de3-bfb1-4707-b66e-37895eb9ed8b
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/63a48cea-97ea-4c56-9bd3-f4075c1edfde)

In other studies, we don't have the issue. I think it's the case the error 500 isn't manage properly.

**Comment by makdeuneuv** [comment]
Nous pensons aussi que c'est du fait du générateur d'étude qui écrit des éléments différemment de ce qui est attendu sur AntaresWeb. Il faut donc un meilleur contrôle des données avec des erreurs appropriées pour que l'utilisateur sache quoi corriger dans son jeu de données.

**Comment by MartinBelthle** [comment]
@makdeuneuv  J'ai ouvert la vue de la même étude le 21 juin à 19h et je n'ai pas eu le problème. Y'a t-il eu un changement dans les fichiers de l'étude entre-temps ?

**Comment by makdeuneuv** [comment]
Je ne pense pas, je viens de reproduire en ouvrant le premier cluster thermique de la zone AT. Après la MEP de la 2.14.3 nous avons un message d'erreur plus parlant. Voici la capture d'écran.
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/6a3fe02d-e614-4559-b7c3-78b3e05bf7cb)

**Comment by makdeuneuv** [comment]
Cependant, vu que le formulaire clignote on n'a pas la main dessus pour modifier de potentiel erreur de données. Je viens de vérifier dans les fichiers en entrée, le champs mustRun est une chaîne vide ainsi que FixedCost. Pour moi Antares Web devrait fixer leurs valeurs par défaut dans ce cas, à déterminer avec l'équipe Simulator.

**Comment by MartinBelthle** [comment]
Après avoir discuté avec Alexander et Florian, on ne veut pas fixer les valeurs par défaut si on reçoit un champ avec une chaine vide au lieu d'un entier. Ce qui est voulu par Alexander c'est plutôt de  **toujours afficher le fichier, quelque soit le format des champs et indiquer d'une façon ou d'une autre qu'un champ est incorrect (couleur spéciale ou pop-up).** Il voudrait ça car actuellement comme le front ne montre rien, l'utilisateur ne sait pas comment modifier son fichier pour que ça marche (sur une étude managée il n'a pas accès à son fichier autrement que par la vue DEBUG).  Pour moi ça entraîne pas mal de changement au niveau du back et surtout du front. Vous en pensez quoi @laurent-laporte-pro, @skamril ?

**Comment by laurent-laporte-pro** [comment]
Voici les améliorations que l'on peut apporter :

1. rendre moins strict la lecture des données afin d'autoriser la conversion des chaînes de caractères dans le bon format (booléen, entier, etc.)
2. améliorer le contrôles des données en entrée (lors d'un import) afin de remonter les anomalies en amont.

Par contre, si la structure d'une étude est incorrecte, il ne nous sera pas possible d'afficher les données, et donc, l'utilisateur n'aura pas la main pour corriger. En d'autres termes, lorsque l'équipe Script génère des données, elle se doit de les contrôler.

**Comment by laurent-laporte-pro** [comment]
Je pense clore ce ticket, car nous avons déjà des tickets concernant l'évolution des formulaires, notamment pour les clusters thermiques et renouvelable.
Aussi, je préfère avoir un ticket spécifique concernant le contrôle des données à l'import.
