### ISSUE TITLE
"GET /version HTTP/1.1" doesn't work on the desktop version and local env

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1604]
## Description

When launching AntaresWeb on local environment or on desktop version when you open the front this message appears in the console : 
![pip_freeze](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/89db9a13-0e79-4b0c-b07b-a59147641a12)

This is not a blocking issue but it is problematic in case you want to see dependencies version

## Steps to reproduce

1. Launch the desktop version
2. Open the front (localhost:8080)
3. Look at the console and see this error message. 
Or : 
1. Try to use the GET /version endpoint
2. See that it fails

## Expected behavior

I want to be able to use this endpoint as it is possible on the web version

## Environment

Desktop version 2.14.3
Ubuntu

**Comment by laurent-laporte-pro** [comment]
@MartinBelthle Merci de fournir une description qui permettra à l'utilisateur de comprendre l'anomalie et qui nous permettra aussi de faire les tests d'intégration au niveau de l'interface web et de l'API Swagger.

Autrement dit, ça serait bien d'utiliser le modèle que l'on s'est donné pour faire les demandes de correction…

**Comment by MartinBelthle** [comment]
I filled in this issue in a hurry my bad

**Comment by laurent-laporte-pro** [comment]
❌ Lorsque l'application est compilée avec PyInstaller, il n'y a pas d'interpréteur Python; On a l'erreur :

```json
{
  "description": "Unexpected server error: Command '['/home/paul/Projects/AntaREST/dist/package/AntaresWeb/AntaresWebServer', '-m', 'pip', 'freeze']' returned non-zero exit status 2.",
  "exception": "CalledProcessError"
}
```

**Comment by laurent-laporte-pro** [comment]
✅ Anomalie contournée : si l'application est packagée avec PyInstaller, on n'exécute pas `pip freeze` .

**Comment by MartinBelthle** [comment]
J'ai testé avec la version desktop 2.14.4 et ça fonctionne
