### ISSUE TITLE
Incorrect French translation for Transmission Capacity enumerate values

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1614]
## Description

La traduction des libellés de la liste déroulante de « Capacités de transmission » n’est pas correcte.

### Steps to reproduce the behavior:

D’abord, il faut s’assurer que l’interface utilisateur est en français.

1. Ouvrir une étude,
2. Aller dans le menu "Modélisation",
3. Choisir l’onglet "Liens",
4. Choisir un lien dans la liste des liens à gauche,
5. Cliquer sur la liste déroulante "Capacité de transmission" pour afficher les choix possible.

## Actual Behavior

La liste déroulante affiche les libellés suivants :

- "Infinite" qui n’est pas correct, car c’est un mot anglais,
- "Null" qui n’est pas correct, car c’est au masculin,
- "Activé" qui n’est pas correct, car c’est au masculin.

## Expected Behavior

Nous devrions avoir les libellés suivants :

- "Infinie",
- "Nulle",
- "Activée".

## Screenshots

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/569d3ce7-ea3a-44f4-b85e-3a235ae7b130)

## Possible Solution

Il faut corriger les traductions :

```json
{
  "study.modelization.links.transmissionCapa": "Capacités de transmission",
  "study.modelization.links.transmissionCapa.infinite": "Infinite",
  "study.modelization.links.transmissionCapa.ignore": "Null",
  "study.modelization.links.transmissionCapa.enabled": "Activé"
}
```

## Environment

- ☑ Production
- ☑ Staging

**Comment by makdeuneuv** [comment]
Les champs ne sont toujours pas traduit, je suppoe que cela n'a pas été déployé. Je repasse le ticket en progression

**Comment by laurent-laporte-pro** [comment]
Corrigé dans la version v2.14.4

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/0dad22f0-0b44-46a8-abbd-7f778410a8d5)
