### ISSUE TITLE
Table mode : wrong area names

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1623]
## Description
Open table mode

Areas should appear in row labels

Instead, we get **ui**, **optimization** and **adequacy_patch**. Note that each area directory contains those three INI files.

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/26088210/59962019-244e-4b88-908a-661298f093f5)

- If applicable, provide the study ID that this issue relates to: f079dd4f-f478-4f92-a6c6-ff2165aba28c

- Any relevant library versions: [e.g. React 17.0.1]
- The date and time when the issue occurred: 27/06/2023
- Browser and version: Firefox 107.0
- Operating System: Ubuntu 20.04

**Comment by makdeuneuv** [comment]
Ce cas de figure ne se produit que quand une étude n'a qu'une seule zone. Ajouter une deuxième zone et les deux apparaissent bien dans le table mode. @flomnes Il faudrait convenir ensemble du cas nominal, est-ce qu'une seule zone dans une étude doit apparaître dans le table mode ? Parce que ce n'est pas ce qui est implémenté actuellement.
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/f4e095fa-d342-4bd8-8934-4802206e0989)

**Comment by MartinBelthle** [comment]
Après discussion avec Florian, on veut afficher la zone dans le Table Mode même si elle est seule. Donc il faut corriger ce bug
