### ISSUE TITLE
Missing French translation for Adequacy Patch

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1624]
## Description

Les libellés du formulaire d'Adequacy Patch ne sont pas traduits en français.

### Steps to reproduce the behavior:

D’abord, il faut s’assurer que l’interface utilisateur est en français.

1. Ouvrir une étude en version v8.3 ou v8.5,
2. Aller dans le menu "Configuration",
3. Choisir l’onglet "Adequacy Patch".

## Actual Behavior

Les libellés sont en anglais.

## Expected Behavior

Nous devrions avoir les libellés traduit.

## Screenshots

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/c66787f0-a636-4cea-82fc-4c7828c19467)

## Possible Solution

Il faut corriger les traductions :

```json
{
  "study.configuration.adequacyPatch.enableAdequacyPatch": "Enable adequacy patch",
  "study.configuration.adequacyPatch.ntcFromPhysicalAreasOutToPhysicalAreasInAdequacyPatch": "NTC from physical areas out to physical areas in adequacy patch",
  "study.configuration.adequacyPatch.ntcBetweenPhysicalAreasOutAdequacyPatch": "NTC between physical areas out adequacy patch",
}
```

## Environment

- ☑ Production
- ☑ Staging

**Comment by laurent-laporte-pro** [comment]
Voir avec @JMJ-rte

**Comment by JMJ-rte** [comment]
Entendu, à votre disposition pour proposer ou valider toute proposition de libellés.

**Comment by hdinia** [comment]
Une traduction d'**Adequacy patch** pourrait être **Patch d'adéquation** ou **Correctif d'adéquation**, voir de laisser ce libellé en anglais si la traduction est incorrecte ou maladroite

- ``Patch d'adéquation`` pourrait être utilisé dans un contexte où "patch" est couramment utilisé en français pour désigner une mise à jour ou un correctif logiciel.

- ``Correctif d'adéquation`` est une autre option qui pourrait être plus facile à comprendre pour un public non technique, car "correctif" est un terme plus général que "patch".

#### Voici quelques propositions:

**"Enable adequacy patch"** = "Activer le patch d'adéquation"

**"NTC from physical areas out to physical areas in adequacy patch"** = "NTC des zones physiques extérieures vers les zones physiques intérieures via le patch d'adéquation"

**"NTC between physical areas out adequacy patch"** = NTC entre les zones physiques extérieures et le patch d'adéquation"

Qu'en pensez vous, @JMJ-rte , @laurent-laporte-pro ?

**Comment by laurent-laporte-pro** [comment]
Pour "Adequacy patch", on garde le mot en anglais.

**Comment by hdinia** [comment]
@laurent-laporte-pro, @JMJ-rte 
Je vous propose:

- "Activer l'adequacy patch"
- "NTC à partir des zones physiques vers des zones physiques via l'adequacy patch"
- "NTC entre zones physiques et l'adequacy patch"

```json
  "study.configuration.adequacyPatch.enableAdequacyPatch": "Activer l'adequacy patch",
  "study.configuration.adequacyPatch.ntcFromPhysicalAreasOutToPhysicalAreasInAdequacyPatch": "NTC à partir des zones physiques vers des zones physiques via l'adequacy patch",
  "study.configuration.adequacyPatch.ntcBetweenPhysicalAreasOutAdequacyPatch": "NTC entre zones physiques et l'adequacy patch",
```

**Comment by laurent-laporte-pro** [comment]
@hdinia peux-tu prendre contact avec J.-M. via Teams, car, personnellement je suis incapable de répondre. Les libellés sont déjà très long, vu qu'on est dans le formulaire spécifiquement dédié à l'Adequacy Patch, le pense qu'on peut omettre "Adequacy Patch" dans les deux derniers libellés.

Sinon, Chat GPT nous éclaire ainsi (ça vaut ce que ça vaut) : 

Dans le contexte de la simulation du réseau électrique, NTC fait référence à "Net Transfer Capacity", qui peut être traduit en français par "Capacité Net de Transfert" ou "Capacité de Transfert Nette".

La NTC est la capacité maximale autorisée pour le transfert d'électricité entre deux zones géographiques ou pays voisins, tout en garantissant que le réseau reste stable et sécurisé. Elle est généralement exprimée en mégawatts (MW) et peut varier en fonction des conditions du réseau, telles que les contraintes de lignes de transmission, les niveaux de demande et la disponibilité des ressources électriques.

Dans le contexte spécifique de l'outil Antares Simulator, "NTC from physical areas out to physical areas in adequacy patch" se réfère à la capacité de transfert net de l'électricité des zones physiques extérieures vers les zones physiques intérieures via le patch d'adéquation. Et "NTC between physical areas out adequacy patch" désigne la capacité de transfert net entre les zones physiques extérieures et le patch d'adéquation lui-même.

**Comment by hdinia** [comment]
Seen with @PPlessiez 
- "Activer l'adequacy patch"
- "NTC à partir des zones physiques exclues de l'adequacy patch vers des zones physiques incluses dans l'adequacy patch"
- "NTC entre zones physiques exclues de l'adequacy patch"

**Comment by hdinia** [comment]
> @hdinia peux-tu prendre contact avec J.-M. via Teams, car, personnellement je suis incapable de répondre. Les libellés sont déjà très long, vu qu'on est dans le formulaire spécifiquement dédié à l'Adequacy Patch, le pense qu'on peut omettre "Adequacy Patch" dans les deux derniers libellés.
> 
> Sinon, Chat GPT nous éclaire ainsi (ça vaut ce que ça vaut) :
> 
> Dans le contexte de la simulation du réseau électrique, NTC fait référence à "Net Transfer Capacity", qui peut être traduit en français par "Capacité Net de Transfert" ou "Capacité de Transfert Nette".
> 
> La NTC est la capacité maximale autorisée pour le transfert d'électricité entre deux zones géographiques ou pays voisins, tout en garantissant que le réseau reste stable et sécurisé. Elle est généralement exprimée en mégawatts (MW) et peut varier en fonction des conditions du réseau, telles que les contraintes de lignes de transmission, les niveaux de demande et la disponibilité des ressources électriques.
> 
> Dans le contexte spécifique de l'outil Antares Simulator, "NTC from physical areas out to physical areas in adequacy patch" se réfère à la capacité de transfert net de l'électricité des zones physiques extérieures vers les zones physiques intérieures via le patch d'adéquation. Et "NTC between physical areas out adequacy patch" désigne la capacité de transfert net entre les zones physiques extérieures et le patch d'adéquation lui-même.

j'etais justement en train d'ajouter que j'avais vu avec Paul P donc c'est good, merci ! @laurent-laporte-pro
