### ISSUE TITLE
Cannot refresh API page on desktop version

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1625]
## Description

As described in the title, when i want to refresh the API page (/apidoc), it returns a white screen : 

![bug_refresh](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/f565595d-8dcb-4780-84dd-cd42aa7ba317)

### Steps to reproduce the behavior:
1. Launch the desktop version of AntaresWeb
2. Click on the API button
3. Refresh your page

## Expected Behavior

I would like my page to refresh correctly

## Environment

v2.14.4

**Comment by makdeuneuv** [comment]
issue still present, but it's minor.
