### ISSUE TITLE
[ANT-796] Temporalities Not Updating in Result View after Applying Changes

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1626]
## Description

I'm on the "View Result" page and I want to change the temporality of the results I see. However, when I make the change and click on "Apply," nothing happens. I'm then forced to click on another button (for example, "Links") and go back to my original view in order to see the change take effect.

## Steps to Reproduce

1. Click on any result of a study.
2. Attempt to change the temporality of the results you want to see.
3. Notice that nothing happens.
4. Try to refresh the page, but realize that your change is lost.
5. Redo your change.
6. Click on the "View Links" button and return to the original view to observe that the change is now applied.

## Expected Behavior

When I click on "Apply," I expect to see my change instantly without any additional steps required.

## Screenshots

The view Result and the Apply button : 
![bug_view_result](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/4cd30743-46ce-41fb-86a4-5480973b5157)

## Environment

- [x] Production
- [x] Staging

## Additional Information

Issue encountered with AnatresWeb version v2.14.3 and hotfix 2.14.4 on 28/06 at 10:30

**Comment by sylvlecl** [comment]
It seems to me that i's not only the temporality which is not updated, but also the other fields.
It's very important to fix those problems, since they simply do not allow to visualize simulation results correctly.
