### ISSUE TITLE
Presence of Unnecessary and Unusable Outputs in '000 Free Data Sample' Study

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1627]
## Description
In the '000 Free Data Sample' study on Antares Desktop (version 2.14.4), there are certain outputs included that are neither necessary nor usable. These outputs do not provide any relevant information related to the economy folders. As a result, they create confusion and hinder the usability of the study example. It would be more beneficial to remove these unnecessary outputs and provide a clearer demonstration of the study without them.

## Screenshot
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/a23ed836-3f96-41a9-b9e1-0a0abc8cb067)

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/449fb7c2-0959-4dbd-a440-1f3af4d671d0)

## Additional Information
Antares Desktop 2.14.4 (GitHub Actions artifact).
This issue is not urgent.

**Comment by MartinBelthle** [comment]
@makdeuneuv Do we want to put no output or a realisitic one with the folder economy ? Note : This could be a bit heavy

**Comment by makdeuneuv** [comment]
No output it's the best way.
