### ISSUE TITLE
[ANT-706] Refactor Thermal Cluster View

### ISSUE THREAD

**Issue by hdinia** [AntaresSimulatorTeam/AntaREST#1641]
Related to #1513

**Comment by laurent-laporte-pro** [comment]
## Gestion de la configuration INI

Pour la gestion de la configuration des fichiers INI, je pense qu'il faut introduire deux classes :

- Une classe de base `ThermalClusterConfig` (ou `ThermalClusterBaseConfig`, comme tu veux) pour gérer les options d'un cluster thermique en version < 8.6,
- Une sous-classe `ThermalCluster860Config` (qui hérite de `ThermalClusterConfig`) pour gérer les options supplémentaire présentes en v8.6

De plus, pour les groupes de clusters, il est nécessaire d'introduire un type énuméré, par exemple `ThermalClusterGroup`.

Voici un diagramme de classes :

![ThermalClusterConfig Class Diagram-Page-1](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/024c0be5-7caf-4083-9514-08ec67c8f282)

**Comment by laurent-laporte-pro** [comment]
## Gestion des formulaires de création, de mise à jour et de lecture, tu peux te contenter d'avoir trois classes :

- La classe `ThermalClusterCreation` pour la création d'un cluster thermique,
- La classe `ThermalClusterInput` pour les données d'entrée permettant la mise à jour globale ou champ par champ d'un cluster thermique. Cette classe contiendrait optionellement tous les champs, y compris les champ de v8.6.
- La classe `ThermalClusterOutput` héritant de `ThermalClusterInput` qui ajoute le champ `id`.

Voici un diagramme de classes :

![ThermalClusterConfig Class Diagram-Page-2](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/d633e012-fbad-44dd-a557-423cb8dc2bfc)

**Comment by laurent-laporte-pro** [comment]
## Mapping entre les Formulaires et les Fichiers INI

D'un côté, les classes `ThermalClusterCreation`, `ThermalClusterInput` et `ThermalClusterOutput`, et de l'autre, les classes `ThermalClusterConfig` et `ThermalCluster860Config`, établissent une relation bijective qui permet de faire correspondre les champs des formulaires avec les options de la section INI.

# Lecture des Données depuis le Fichier INI

Lors de la lecture (GET), le processus consiste à passer de la configuration à un formulaire `ThermalClusterOutput` en suivant ces étapes :

1. Les options sont extraites à l'aide de la méthode `file_study.tree.get()`, puis une instance de `ThermalClusterConfig` ou `ThermalCluster860Config` est créée en fonction de la version de l'étude.

2. Ensuite, la méthode `values = config.dict(by_alias=False)` est utilisée pour obtenir un dictionnaire associant les noms des champs au format snake_case.

3. Enfin, un objet `ThermalClusterOutput` peut être construit à partir de ce dictionnaire `values`. Les valeurs manquantes (dans le cas d'une version antérieure à 8.6) seront définies comme étant égales à None.

## Mise à Jour des Données dans le Fichier INI

Lorsqu'une mise à jour (PATCH) ou une création (POST) est effectuée, le processus implique de passer du formulaire `ThermalClusterInput` à la configuration en suivant ces étapes :

1. Tout d'abord, les données du formulaire sont converties en utilisant la méthode `values = form.dict(by_alias=False, exclude_none=True)`. Cette étape permet de conserver uniquement les attributs à mettre à jour.

2. Pour la mise à jour, il est nécessaire de gérer habilement les anciennes valeurs du fichier INI en conjonction avec les nouvelles valeurs fournies par le formulaire. Cette opération est réalisée dans l'implémentation de `STStorageManager.update_storage`. Il est crucial de prendre en compte la version de l'étude, et une exception doit être déclenchée si le formulaire contient un champ qui n'existe pas dans une version antérieure à 8.6.

3. Enfin, un objet `ThermalClusterOutput` complet, englobant à la fois les données anciennes et les nouvelles, peut être construit et renvoyé en résultat.
