### ISSUE TITLE
Xpansion does not find output for sensitivity analysis 

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/AntaREST#1645]
## Description

Sensitivity analysis of Xpansion does not find the study output folder.
### Steps to reproduce the behavior:
1. Launch an Xpansion study, get an output `<my-output>`.
2. Launch Xpansion with sensitivity analysis, and select the output `<my-output>`.
3. The run fails because Xpansion does not find the output `<my-output>`.

## Actual Behavior
- When the Xpansion study launched at step 1 has the option "Automatic unzipping", the run terminates with the following error :
```python
[30599] Failed to execute script 'launch' due to unhandled exception!
Traceback (most recent call last):
  File "launch.py", line 45, in <module>
  File "antares_xpansion/driver.py", line 101, in launch
  File "antares_xpansion/driver.py", line 159, in launch_sensitivity_step
  File "antares_xpansion/config_loader.py", line 429, in _create_sensitivity_dir
  File "antares_xpansion/config_loader.py", line 441, in _sensitivity_dir
  File "antares_xpansion/config_loader.py", line 361, in xpansion_simulation_output
  File "antares_xpansion/config_loader.py", line 510, in _set_last_simulation_name
  File "antares_xpansion/config_loader.py", line 544, in get_last_modified_dir
IndexError: list index out of range
```
- Otherwise, when the Xpansion study launched at step 1 **does not have** the option "Automatic unzipping", the run terminates with the following error :
```python
Exporting study...
Extracting study xxx

Failed to launch study xxx: see stack trace below:
Traceback (most recent call last):
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 527, in _run_study
    self.callbacks.export_study(
  File "/antarest/launcher/service.py", line 462, in _export_study
    self.study_service.export_study_flat(
  File "/antarest/study/service.py", line 1205, in export_study_flat
    return self.storage_service.get_storage(study).export_study_flat(
  File "/antarest/study/storage/rawstudy/raw_study_service.py", line 378, in export_study_flat
    export_study_flat(
  File "/antarest/study/storage/utils.py", line 399, in export_study_flat
    shutil.copytree(
  File "/usr/local/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_my_output>'
```

## Expected Behavior
I expect the run to find the output, carry out the sensitivity analysis and terminate normally.

## Possible Solution
After running an Xpansion study, the output folder contains both a folder `<my-output>` and an archive `<my-output.zip>` (when the option `Automatic unzipping` is selected). When launching the sensitivity analysis for `my-output`, Xpansion looks for **the archive** `<my-output.zip>`. However, AntaresWeb sends to the cluster **the folder** `<my-output>` and not the archive, which causes the error.

Maybe AntaresWeb should package the archive `<my-output.zip>` instead of the folder `<my-output>` when sending the study to the cluster.

Also, should Xpansion be able to handle both cases (if it does not find a zip, look for a folder) ? @JasonMarechal25 

## Environment

- [ ] Production
- [ ] Staging
- [x] Integration

**Comment by laurent-laporte-pro** [comment]
## ANALYSE

La fonction d'export des études dans le format "RAW" (c'est-à-dire, sous la forme d'une arborescence de fichiers) est utilisée à plusieurs endroits dans l'application :

1. Lors de la conversion d'un variant en étude "RAW" pour créer un _snapshot_. Dans ce cas, l'export est généré sans les sorties (`outputs=False`).
2. Lors de l'archivage d'une étude. Dans ce cas, l'export est effectué avec toutes les sorties (`outputs=true`).
3. Lors de l'export d'une étude. Dans ce cas, l'utilisateur peut choisir d'exclure ou non les sorties.
4. Lors du lancement de la simulation d'une étude (cas qui nous intéresse). Dans ce cas, nous fournissons une liste des sorties à exporter en fonction des paramètres Xpansion.

Si nous souhaitons exporter les sorties au format ZIP plutôt qu'en utilisant une arborescence de répertoires, il est nécessaire d'analyser l'impact d'un changement de format au niveau de l'API. @makdeuneuv et/ou @MartinBelthle, nous aurions besoin de vos retours d'expérience utilisateur sur ce sujet.

Par ailleurs, la fonction d'export ne gère pas le cas où certaines sorties sont déjà compressées, ce qui constitue une anomalie.

**Comment by MartinBelthle** [comment]
On peut imaginer un booléen en plus pour spécifier si on doit zipper les résultats ou non (default value : **unzipped**)

**Cas 1.** Pas d'output donc la question ne se pose pas. **default**
**Cas 2.** Comme on archive toute l'étude, je pense qu'il ne faut pas zipper en plus les outputs (à discuter) **unzipped**
**Cas 3.** Pour moi, si l'utilisateur exporte son étude avec certains outputs, il veut utiliser son contenu. Donc il faudrait garder le comportement actuel : **unzipped**. On pourrait aussi rendre ce booléen paramétrable dans le front au moment de l'export des outputs (à discuter)
**Cas 4.** Seul Xpansion utilise cette fonctionnalité donc **zipped**

Qu'en penses-tu @laurent-laporte-pro ?

**Comment by sylvlecl** [comment]
**Important note for that issue:**
Note that xpansion expects only one result to be provided for the sensitivity analysis, as mentioned by @JasonMarechal25 in #1371.

For the sensitivity analysis, we should export only that result (in a zip file), and we should provide the option `--simulationName` to xpansion.

**Comment by MartinBelthle** [comment]
Yes this is noted. We already import only one input and the .sh script is not an issue (no need for `--simulationName` as there is only one output, see here [sensitivity-doc](https://antares-xpansion.readthedocs.io/en/stable/user-guide/get-started/sensitivity-analysis/#run-the-sensitivity-analysis)). The only issue left is that the output is not zipped if I'm correct.

**Comment by laurent-laporte-pro** [comment]
You're right. However, in my opinion, providing a ZIP file instead of a directory is a poor idea because the entire study is compressed before being sent to the SLURM server.

Additionally, I believe it would be wise to suggest that the Xpansion team support both formats (ZIP and directory), similar to how we already handle reading certain study configuration files. Xpansion will still need to decompress the ZIP archive to utilize the output data, resulting in unnecessary work for both Antares Web and Xpansion.

@tbittar and @JasonMarechal25, what do you suggest?

**Comment by tbittar** [comment]
Yes I agree, the issue has been discussed within the Xpansion team, and we have decided to make the tool accept both zipped and unzipped folder when it looks for the study output for sensitivity analysis. 

See https://github.com/AntaresSimulatorTeam/antares-xpansion/issues/665

**Comment by laurent-laporte-pro** [comment]
> Yes I agree, the issue has been discussed within the Xpansion team, and we have decided to make the tool accept both zipped and unzipped folder when it looks for the study output for sensitivity analysis.

Good news! It allows us to shift our focus to another issue: enabling the launcher to send a ZIP-compressed output when the user choose _not_ to uncompress the outputs after a previous simulation. @MartinBelthle, do you think you can work on this last issue?

**Comment by MartinBelthle** [comment]
I created this issue https://github.com/AntaresSimulatorTeam/AntaREST/issues/1655 to tackle what Laurent's last comment is about. I also close this issue as it will be solved thanks to Xpansion team ongoing dev
