### ISSUE TITLE
Use Antares Solver v8.6.1 (hotfix release)

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1651]
## Description

We need to use Antares Solver v8.6.1 in Antares Web, as this version corrects an issue regarding the cost calculation for short-term storage. There is no impact on the structure of input or output files.

As a reminder, the version is available at https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/tag/v8.6.1.

In particular, the version number in the `scripts/package_antares_web.sh` file should be corrected, as it remains v8.5 (c.f.: #1489).

Acceptance criteria :

- [x] In the study launch dialogue box, the drop-down list of Solver versions must display version v8.6,
- [x] The `launchAntaresRec.sh` script must be up to date during acceptance and integration,
- [x] The `scripts/package_antares_web.sh` script must be up to date with version **8.6.1**.
- [x] From the web interface, if a new study is created, it must be in v8.6
- [x] It must be possible to upgrade a study to v8.6. The result must contain the new parameters.
- [x] When you run a study in 8.6, you must be able to view  outputs
- [x] When running a simulation, we must check that the solver version is **v8.6.1** in the logs.

**Comment by makdeuneuv** [comment]
I open this issue #1659 and point 4 and 6 in description are not yet implemented.
