### ISSUE TITLE
[ANT-706] Add ST-storage API Endpoints

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1653]
### Description

In the latest release of Antares Solver (version 8.6), a new object called "short-term storage" can be configured within
a study area. Although short-term storages are not directly related to thermal and renewable clusters, their
implementation is similar. Both share the concept of groups and use a similar INI file configuration.

As part of the ongoing development of Antares Web, we have added several commands to manage short-term storages,
including creation, deletion, and update. Additionally, we are currently working on implementing managers for the API
Endpoints.

The objective of this feature request is to develop the necessary Endpoints for managing short-term storages. These API
Endpoints will be utilized by the front office of the web application to display the list of short-term storages grouped
by storage groups. They will also facilitate the display of a form for entering parameters for a short-term storage and
its associated time series matrices.

Furthermore, the Script team will leverage these API Endpoints to automatically generate studies configured with
short-term storages. These Endpoints will complement the existing commands.

### Scope of Work

The following Endpoints need to be defined:

1. Endpoint to create a new storage in a given area (POST).
2. Endpoint to retrieve the list of storages within an area, grouped by storage group  (GET).
3. Endpoint to retrieve the list of storages within an area for a given named group —optional implementation—  (GET).
4. Endpoint to obtain the storage fields to display the form (GET).
5. Endpoint to update one or multiple storage fields (PUT) —for incremental update—.
6. Endpoint to display one of the five matrices associated with a storage (GET).
7. Endpoint to replace one of the five matrices with a new one (PUT).
8. Endpoint to delete one or several storage(s) (DELETE).
9. Endpoint to check matrices consistency and show results (GET).

> Note: [Using HTTP Methods for RESTful Services](https://www.restapitutorial.com/lessons/httpmethods.html)

> Note: The Endpoint for editing matrix columns and cells is already implemented.

For each Endpoint, the URL, the parameters, return values, and documentation (using Markdown) should be defined. Additionally, the Endpoints should enforce access rights (read or write) for the study. The processing logic should be delegated to the
Short-Term Storage Manager. To implement your Endpoints, use the `antarest/study/web/study_data_blueprint.py` file.

"Integration" tests similar to those developed for thermal clusters should be implemented, covering both nominal and known
error cases (documented in the Manager). Store your unit tests in `tests/integration/study_data_blueprint`, i.e.: `test_st_storage`.

Please note that the Short-Term Storage Manager (`STStorageManager`) is currently under development. Therefore, the feature implementation should be based on the feature branch available on GitHub: `feature/1522-add-st-storage-manager`. The branch for working on this feature has already been created and is named `feature/1653-add-st-storage-api-endpoints`.

Exemple of markdown documentation for `/v1/studies/{uuid}/matrix`:

```md
Edit a matrix in a study based on the provided edit instructions.

Args:
- `uuid`: The UUID of the study.
- `path`: The path of the matrix to update.
- `matrix_edit_instructions`: A list of edit instructions to be applied to the matrix.

Permissions:
- User must have WRITE permission on the study.
```

**Comment by makdeuneuv** [comment]
In the PR associate, we have juste 8 endpoint versus 9 describe here.
@laurent-laporte-pro is it normal?
