### ISSUE TITLE
Impossible to read a study after a simulation

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1661]
## Description
A user run a simulation on a study and after the end the results are available but we can't read the study on anatresweb insterface (map, configuration results, etc). The user can not see the study. See the screenshot.

ID of the study on production :  8a20d8e7-d466-4a23-b547-aa39ff19fb2d

This issue is urgent.

##Screenshot

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/64f6069f-ffaa-4dbf-9801-ecb4dc477da9)

![MicrosoftTeams-image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/0ca76649-9133-4ecd-9661-0c76e3138c59)

**Comment by MartinBelthle** [comment]
On the 23th of August, i do not have this problem anymore, the study can be opened without any trouble.
Therefore, i close this issue.
