### ISSUE TITLE
The list of solver available versions in the launcher dialog box is wrong

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1672]
## Description

In the launcher dialog box, you can choose a solver version to launch your study, example on recette environment : 

![liste_versions](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/5ab06fbe-cca1-4c97-bbe8-b5a9ace8a0e5)

This list is returned by the endpoint `GET /studies/_versions` but it has nothing to do with the list of available solvers which can be retrieved via the endpoint `GET /launcher/_versions`

## Expected Behavior

The front end should use the 2nd API to show the available launcher versions : `GET /launcher/_versions`
The API returns a dict object such as : 

![new_model_response](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/db1ab875-b6c6-4c45-9b8e-33b4d0a9be03)

The key `default` is always present and its value will be a dict object with a key (slurm or local) and the list of solver versions. This is the list the front should display (we do not care about the key `others` here).

## Environment

- [x] Production
- [x] Staging

## Developer note

You should do your devlopment on the linked PR because it implements the new reponse model of the endpoint described right above.

**Comment by makdeuneuv** [comment]
Aucun changement sur l'interface, de plus il n'y a plus la v8.6 qui apparaît dans la liste alors que cette version est bien présente en retour de l'api  /launcher/_versions (voir capture d'écran). @hdinia  pourrais-tu vérifier s'il ne s'agit pas d'une régression? Merci.

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/dda4f4df-ce3d-4ad6-bba5-8c4fb4c0514b)

**Comment by hdinia** [comment]
C'est pourtant effectif sur `dev`, es-tu sûre que le fix est présent sur l'environnement ou tu as testé ? 

Sur le screen on voit bien ma config en local avec une seule version au lieu des versions d'etudes:
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/33469289/baf905b7-05ba-46af-9237-4f03dab60b6c)

> Note: le endpoint est desormais `v1/launcher/versions`
@makdeuneuv

**Comment by laurent-laporte-pro** [comment]
The list of versions is displayed correctly in the staging server (after correction)

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/77635bac-db27-42ad-a404-e724cc44b7ea)

This list matches the list of versions available in the configuration file:

```yaml
launcher:
  default: slurm
  slurm:
    […]
    antares_versions_on_remote_server :
      - "610"
      - "700"
      - "710"
      - "720"
      - "800"
      - "810"
      - "820"
      - "830"
      - "840"
      - "850"
      - "860"
```
