### ISSUE TITLE
Elastic on recette environment does not work anymore 

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1675]
## Description

http://antares-supervision-recette.rte-france.com:5601/app/home#/ does not work anymore.

Not urgent but it is annoying.

**Comment by makdeuneuv** [comment]
The filesystem /var and /var/log was full.
Space was been added, but still have issue with Kibana.

**Comment by makdeuneuv** [comment]
It take time for Kibana to restart, now it's working.

**Comment by makdeuneuv** [comment]
Remarks : I think there are no logrotate on OPF server and it happens some time filesystems of log are full.

**Comment by makdeuneuv** [comment]
Setting up a logrotate configuration, adding disk space. The server is accessible now.
