### ISSUE TITLE
Job progress can exceed 100%

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1681]
## Description

Example of a job progress way over 100%

![MicrosoftTeams-image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/073458f9-40c8-40ec-8b9c-d17246898981)

The back-end returns this value, it is not a front-end issue.
Also, this is not reproductible:  using the log_parser.py on the log file does return a value below 100%.

My guess based on what I saw, is that the `launch_progress_dto.coef` that's supposed to be 0.8 (and stay like this) can become 800 whithout any apparent reason

## What's asked

On the long term, we expect the simulator to log this type of line :
**[Thu Jul 27 14:08:52 2023][solver][infos] Job completion XX%**
When it will, we will simplify the parser to use only this value.

For now, we expect AntaresWeb to show job progress less than 100%.

**Comment by makdeuneuv** [comment]
Screenshot made on 09/06/2023 after release of v2.14.5. Bug still present.

![bug pourcentage affichage simu2](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/be8f94a3-07f6-4454-81d9-0696bf849bfe)
![bug pourcentage affichage simu](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/3d2f8920-2dcb-4732-8b6d-a851cf433697)

Task id : 094c5567-1096-47c8-970b-89f59382d040
Study id : 44b99268-fd73-4d3e-a3a3-be34fc6683aa

The simulation ended the next day at 8:23 p.m.

**Comment by makdeuneuv** [comment]
Observation: The bug occurs when a simulation takes more than 24 hours to complete.
