### ISSUE TITLE
[ANT-670] Batch size not correctly handled

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/AntaREST#1683]
## Description

Batch size setting for Xpansion study cannot be modified (probably due to a typo). Xpansion expects a setting called `batch_size` whereas AntaresWeb tries to set up a parameter called `batch-size` 

### Steps to reproduce the behavior:
1. Open an Xpansion study
2. Change the batch size setting (only possible via the API: update Xpansion settings)
3. Launch the study
4. See error of illegal parameter in settings file:

```
check_setting_option_type: Illegal batch-size option in settings file.
Simulation failed, output results are not available
```

## Actual Behavior
AntaresWeb does not use the correct key for the batch size parameter.

## Expected Behavior
AntaresWeb writes the batch size setting with the `batch_size` key in `settings.ini` (see https://github.com/AntaresSimulatorTeam/AntaREST/pull/1485#issuecomment-1551007950)

- [ ] Production
- [x] Staging

## Additional Information
This bug is really annoying as for studies on database, there is (to my knowledge) no other way to modify the study, which prevents me from doing validation tests for the Benders by batch feature for Xpansion.

**Comment by laurent-laporte-pro** [comment]
The fix regarding the naming (and typing) of parameters in the `settings.ini` configuration file for Xpansion has been implemented on both the `dev` branch and the `hotfix/v2.14.5` branch. This update will be deployed in the staging environment first, and then in production once the hotfix is validated.
