### ISSUE TITLE
[ANT-798] Exception thrown while viewing thermal clusters

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1686]
## Description
When navigating in a study (no matter which one), an exception is systematically raised.

### Steps to reproduce the behavior:

- Navigate with the mouse to Modeling / Area / Thermal clusters
- Open view of any cluster, for example CCGT-old-2 from GR area
- Return directly to another area, for example BG

Then we get this exception:
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/13d2ffe2-3e0a-4d7c-a0dc-4a4d66dd5bca)

## Expected Behavior

When consulting a thermal cluster, if you click on a area, you must obtain the view of the list of thermal clusters of the associated area. No exception should be thrown.

## Environment

- [X] Production
- [X] Staging

**Comment by laurent-laporte-pro** [comment]
@hdinia, can you add your own analysis. May be related to a router…
