### ISSUE TITLE
[ANT-827] Increase the default number of core in the launch window to 22

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1695]
## Problem Statement
Currently the default value for the number of cores when you want to run a simulation is 12.
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/d6330a30-65a1-470e-9fdc-f59ae9c8374e)

Change this value to 22 (this is the maximum number of cores on the compute nodes currently).

**Comment by laurent-laporte-pro** [comment]
Quick fix: set the default number of cores to 22 (instead of 12)

See: https://github.com/AntaresSimulatorTeam/AntaREST/commit/2c8979916d46a0ed46a67bc75ac9a2e365e3f164

**Comment by laurent-laporte-pro** [comment]
This issue is resolved in the `hotfix/v2.14.5` branch / staging server:

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/284d0d3a-8f91-48e5-8247-0a3fbf875a11)
