### ISSUE TITLE
[ANT-844] Multiple desktop versions do not share data

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1701]
## Problem Statement

Every time an user wants to install a new Antares Web desktop version, if he wants to keeps its previous studies, he needs to perform a few tricks and risks to remove everything.

## Proposed Solution

To avoid this we need to :

**1)** Create a script located in `AntaREST/resources/deploy` that does this:
- Look for a folder named `antares_web_data` located at the root of the desktop folder. (the name can be different, it's just an example)
- If it exists, stop
- Else : Create it and copy the folders `examples`, `matrices` and the file `database.db`to the root of the folder.

**2)** Modify the `AntaREST/resources/deploy/config.yaml` file to point to `antares_web_data`

**3)** Add in the `AntaREST/resources/deploy/README.md` file that this script must be run each time a Desktop version is installed.

**4)** Add in the same README that each new Desktop version must be installed in the same parent folder, and that the `antares_web_data` folder must not be deleted, otherwise data will be lost.

### Important point

I think Windows only executes `.exe` files that are not executable under Unix 

Maybe it's not so complicated to add a "bash" in front of the .sh command when you run it under Windows, but I doubt it. 

If this does not work, it is also needed to change the GitHub Action "deploy" and the `AntaREST/scripts/package_antares_web.sh` so that it makes a distinction between os and choose the right executable. That would also mean that the script would be duplicated in `.exe` and `.sh` versions which is not so good ...

**Comment by MartinBelthle** [comment]
We could also mutualize `tmp` directory (needs to modify `config.yaml` file)

**Comment by makdeuneuv** [comment]
it will be solved with the desktop installeur
