### ISSUE TITLE
[ANT-828] nb_cores - Evolution of Application Configuration

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1704]
# Description

This feature request introduces changes to the application configuration to enable dynamic management of the number of CPU cores. It involves the removal of the old parameter `default_n_cpu` and the addition of a new parameter `enable_nb_cores_detection` and a new object `nb_cores` with the parameters `min`, `default`, and `max`.

## Changes Made

- Removed the old parameter `default_n_cpu` from the application configuration file (`application.yaml`).
- Added a new parameter `enable_nb_cores_detection` and a new object `nb_cores` to the configuration for both the production, example, Desktop version, and unit test files.
- Updated the classes in the `antares.core.config` package to integrate these changes.
- Updated the corresponding unit tests (created them if they were missing).
- Updated the docstring for these classes.

### Old Application Configuration

Currently, the application configuration file (`application.yaml`) includes a parameter `default_n_cpu` representing the number of CPU cores for the SLURM compute server:

```yaml
launcher:
  default: local
  local:
    # [...]
  slurm:
    default_n_cpu: 12
    # [...]
```

This parameter needs to be modified to utilize the new configuration presented below.

This refactoring also affects the `default_n_cpu` attribute of the `SlurmConfig` class.

### New Application Configuration

We propose the following configuration:

```yaml
launcher:
  default: local

  local:
    enable_nb_cores_detection: True
    # [...]

  slurm:
    enable_nb_cores_detection: False
    nb_cores:
      min: 1
      default: 22
      max: 24
    # [...]
```

This configuration involves adding a parameter `enable_nb_cores_detection` and a new object `nb_cores` with the parameters `min`, `default`, and `max`.

## Class Diagram

The class diagram below represents the various classes to be modified to handle this new configuration:

![nb_cores drawio](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/02586d58-86d6-4f57-b401-f80c38f04e3f)

### Configuration of the Number of CPU Cores

The `NBCoresConfig` class is designed to manage the configuration of the number of CPU cores used during simulation execution.

**Attributes**:
- `min` (integer): Represents the minimum number of allowed cores for a simulation (default is 1).
- `default` (integer): Sets the initial default value for the number of cores (default is 22).
- `max` (integer): Indicates the maximum number of allowed cores for a simulation (default is 24).

**Methods**:
- `from_dict(data: JSON) -> NBCoresConfig (Class Method)`: Creates an instance of `NBCoresConfig` from a data dictionary.
- `_validate_nb_cores() -> None` (Protected): Validates the number of cores parameters, raising an exception if they are invalid (i.e., if 1 ≤ min ≤ default ≤ max is false). The error message should specify the name of the invalid attribute(s).
- `to_json() -> dict`: Retrieves the number of cores parameters, returning a dictionary containing the values "min" (minimum allowed value), "defaultValue" (default value), and "max" (maximum allowed value).
- `__post_init__() -> None`: This method must be implemented to perform post-initialization validation of the number of cores.

### Configuration of the Local Server

The `LocalConfig` class needs to be modified to add the `enable_nb_cores_detection` parameter and the `nb_cores` object.

**Attributes**:
- `enable_nb_cores_detection` (boolean): Indicates if automatic detection of the number of cores is enabled (default is disabled). When enabled, the application will attempt to automatically detect the number of available cores on the user's machine.
- `nb_cores` (NBCoresConfig): This parameter configures the minimum, maximum, and default number of cores. It is optional and will be calculated if `enable_nb_cores_detection` is active.

**Methods**:
- `from_dict(data: JSON) -> LocalConfig (Class Method)`: Creates an instance of `LocalConfig` from a data dictionary. It should be modified to support the `enable_nb_cores_detection` parameter and the `nb_cores` object. This method should execute automatic detection of the number of cores if the `enable_nb_cores_detection` parameter is active.
- `_autodetect_nb_cores() -> Dict[str, int]` (Protected): Automatically detects the number of cores available on the user's machine using the `multiprocessing.cpu_count()` function. It returns an object of type `Dict[str, int]` to update the `nb_cores` object.

### Configuration of the SLURM Server

The `SlurmConfig` class needs to be modified to add the `enable_nb_cores_detection` parameter and the `nb_cores` object and to remove the `default_n_cpu` parameter.

**Attributes**:
- `default_n_cpu` (integer): This parameter should be removed.
- `enable_nb_cores_detection` (boolean): Indicates if automatic detection of the number of cores is enabled (default is disabled).
- `nb_cores` (NBCoresConfig): This parameter configures the minimum, maximum, and default number of cores. It is optional and will be calculated if `enable_nb_cores_detection` is active.

**Methods**:
- `from_dict(data: JSON) -> SlurmConfig (Class Method)`: Creates an instance of `SlurmConfig` from a data dictionary. It should be modified to support the `enable_nb_cores_detection` parameter and the `nb_cores` object. This method should execute automatic detection of the number of cores if the `enable_nb_cores_detection` parameter is active. To ensure compatibility between the old version of the configuration and the new version, this method must support the `default_n_cpu` parameter if it exists: in the new configuration, this value corresponds to the `nb_cores.default` parameter.
- `_autodetect_nb_cores() -> Dict[str, int]` (Protected): Automatically detects the number of cores available on the SLURM server by executing an `sinfo` command via SSH on the remote server. It returns an object of type `NBCoresConfig` to update the `nb_cores` object. A `NotImplementedError` exception will be raised to indicate that this detection is not yet available for a SLURM server.

### Configuration of the Launcher

The `LauncherConfig` class needs to be modified to add a function for retrieving the number of cores to use for displaying the simulation launch dialog.

**Methods**:
- `get_nb_cores(solver: str) -> NBCoresConfig`: This method retrieves the number of cores configuration for a given `solver`: "local," "slurm," or "default." The `to_json()` method of this object can be used as a response to the API endpoint to be used by the front office to initialize the simulation launch dialog.

**Comment by TLAIDI** [comment]
About the argument of the method get_nb_cores, we think me and @MartinBelthle that it should be named as launcher not as solver

**Comment by laurent-laporte-pro** [comment]
close by #1704
