### ISSUE TITLE
[ANT-828] nb_cores - Add API Endpoint "get_nb_cores"

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1705]
Create "get_nb_cores" Endpoint for Retrieving Min, Default, and Max Core Count**

## Description

Addition of a new API endpoint named "get_nb_cores". This endpoint will provide information about the minimum, default,
and maximum core counts available on either the SLURM computation server or the local desktop version.

### Endpoint Details

- **Endpoint Name**: `get_nb_cores`
- **HTTP Method**: GET
- **Path**: `/v1/launcher/nbcores`
- **Response Model**: `Dict[str, int]`

**Query String Parameter:**

- **Parameter Name**: `solver`
- **Parameter Type**: str

## Functionality

The objective of this new endpoint is to retrieve core count information for a selected solver, which can be one of the
following options:

- "slurm": Referring to the SLURM computation server.
- "local": Referring to the local desktop version.
- "default": Referring to the default solver.

**Example Response**:

```json
{
  "min": 2,
  "default": 4,
  "max": 16
}
```

## Implementation Details

This feature will utilize the existing `get_nb_cores` method within the `LauncherConfig` class to gather core count
information based on the selected solver.

This enhancement is dependent on feature request #1704.

**Comment by TLAIDI** [comment]
In which directory within the stack should we implement the `/v1/launcher/nbcores` endpoint?

**Comment by laurent-laporte-pro** [comment]
> In which directory within the stack should we implement the `/v1/launcher/nbcores` endpoint?

All endpoints are implemented within the `antarest.launcher.web` Python package. They are all labeled with the `APITag.launcher` tag. You will easily find the following endpoints:

- POST `/v1/launcher/run/{study_id}`: Execute a study
- GET `/v1/launcher/jobs`: Retrieve job information
- GET `/v1/launcher/jobs/{job_id}/logs`: Retrieve job logs using the job ID
- GET `/v1/launcher/jobs/{job_id}/output`: Export job output
- POST `/v1/launcher/jobs/{job_id}/kill`: Terminate a job
- GET `/v1/launcher/jobs/{job_id}`: Fetch job details by job ID
- DELETE `/v1/launcher/jobs/{job_id}`: Delete a job
- GET `/v1/launcher/jobs/{job_id}/progress`: Get job progress based on the job ID
- GET `/v1/launcher/engines`: Retrieve available engines
- GET `/v1/launcher/load`: Obtain the cluster load as a percentage of usage
- GET `/v1/launcher/versions`: Retrieve a list of supported solver versions

As described in the specifications, you can use the `/v1/launcher/versions` endpoint as a reference for implementing `/v1/launcher/nbcores`...

**Comment by TLAIDI** [comment]
What we are expected to return with the endpoint : /v1/launcher/nbcores if the solver is **slurm** ?

**Comment by MartinBelthle** [comment]
If I understood correctly, if we have an older version of the `application.yaml` (that does not contain the fields we are going to introduce) we want to return default values (1, the value registered in the field `default_nb_cpus` that will disappear with the new version, 24). 

If the `application.yaml` contains the new parameters, there are 2 cases:
- If the parameter `enable_core_detection` is True, we want to raise a `NotImplementedError`.
- If it is False, we want to return what's registered in the `application.yaml`

**Comment by MartinBelthle** [comment]
@laurent-laporte-pro I don't understand why this endpoint takes the `launcher` as an argument. From what I understood, we wanted to read the `default` value in the `application.yaml` file and return the info according to this value. Therefore, I think this endpoint should not have any argument

**Comment by laurent-laporte-pro** [comment]
> @laurent-laporte-pro I don't understand why this endpoint takes the `launcher` as an argument. From what I understood, we wanted to read the `default` value in the `application.yaml` file and return the info according to this value. Therefore, I think this endpoint should not have any argument

Actually, I'd like this endpoint to be implemented in a similar way to the GET `/v1/launcher/versions` endpoint, allowing you to retrieve the versions of the default solver or the solver of your choice. Of course, this choice would only be available for the API, the launching dialog box would not have access to this function.

**Comment by MartinBelthle** [comment]
Okay so the dialog box will use the argument `default` but the endpoint will allow every possibility. Why not.
