### ISSUE TITLE
[ANT-828] nb_cores - Enhance Simulation Launcher Dialog

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1706]
## Current Behavior Reminder

The simulation study launcher dialog allows users to configure the number of cores to be used for each job. This configuration is facilitated through a slider, with values ranging from 1 to 24. The slider's position (currently set at 22 in the screenshot) represents the selected number of cores.

![launcher_dialog_box](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/e378beaf-db90-470f-8105-bf1c9fb51129)

The launcher dialog's slider uses two constant values:

1. `LAUNCH_LOAD_DEFAULT`: Defines the default value of the slider when the dialog is initially displayed.
2. `LAUNCH_LOAD_SLIDER`: Defines the minimum (min), maximum (max), and step (step) values for the slider.

Currently, these values are constants defined as follows in `webapp/src/components/App/Studies/LauncherDialog.tsx`:

```javascript
const LAUNCH_LOAD_DEFAULT = 22;
const LAUNCH_LOAD_SLIDER = { step: 1, min: 1, max: 24 };
```

## Objective of this Enhancement

Our goal is to modify the launcher dialog so that it leverages the "get_nb_cores" endpoint (`/v1/launcher/nbcores`) to initialize the slider's values.

## Enhancement Details

- **Endpoint Name**: `get_nb_cores`
- **HTTP Method**: GET
- **Path**: `/v1/launcher/nbcores`
- **Response Model**: `Dict[str, int]`

**Example Response**:

```json
{
  "min": 2,
  "defaultValue": 4,
  "max": 16
}
```

This enhancement of the user interface is dependent on feature request #1705.

**Comment by makdeuneuv** [comment]
@hdinia The default values is 12 on recette but, it should be 22.

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv, The settings are based on the `application.yaml` file, but it's not updated in the `antares-cd` project yet. We need to change it. Right now, the default is 12 in the `application.yaml` file. So, if you see 12 on the staging server, everything is working as it should! 😀
