### ISSUE TITLE
[ANT-706] Correct ST-storage DELETE Endpoints

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1709]
## Problem statement

When the user wants to delete a short-term storage from the user interface, he or she checks one or more of the items in the list view.

When validating the delete form, the front end calls the DELETE `/v1/studies/{uuid}/areas/{area_id}/storages/{storage_id}` endpoint by passing a list of short term storage IDs.

Currently the DELETE endpoint only accepts a single ID, although multiple IDs may be required.

## Proposed solution

The goal of this feature request is to change the DELETE endpoint to accept a list of IDs (instead of a single ID).

The `STStorageManager` class also needs to be changed to accept a list of strings (instead of a single string).

Tasks:

- [ ] Change the name of the method from `delete_storage` to `delete_storages`;
- [ ] Change the signature of the `delete_storages` method to accept a list of strings;
- [ ] Change the implementation of the method to loop over the IDs;
- [ ] Add unit tests named `test_delete_storages.*` to check the following nominal cases
  1. only one ID is given,
  2. multiple IDs are given
  3. no ID is given;
- [ ] Adapt the integration test to check the nominal case.

**Comment by TLAIDI** [comment]
The endpoint should be like /v1/studies/{uuid}/areas/{area_id}/storages and we need to provide à list of storage ID like input in a payload
