### ISSUE TITLE
It's impossible to scroll at the end of a matrix because of another bigger scroller above it.

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1715]
## Problem Statement

For some matrices (at least the ones for Thermal Clusters), i cannot scroll at the end of the matrix because of the other bigger scroller above it.

## Expected Behavior

I would like to be able to scroll at the end of the matrix.

## Screenshot

See in the bottom right of the screen:

[Capture d’écran vidéo de 31-08-2023 18:12:09.webm](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/ebe8bfcb-1d9d-4bab-90e5-4d083df5c5a3)

**Comment by makdeuneuv** [comment]
issue was fix.
