### ISSUE TITLE
Improved search fields and filters in studies view

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1729]
## Problem Statement

When we make search with a study name or id, after leaving the page (and even logging out) the search bar always contains this last value. The same when we chose some filters values.
 We should facilitate the search for studies with the following proposals (or make others).

## Proposed Solution

- Added a cross to clear the value of research text box.
- Clear automatically the research text box value after we leave the page
- Empty the search field and refresh the list of search results after quit the page

**Comment by makdeuneuv** [comment]
Non présent après le déploiement  de ce matin, peut-être que ce n'était pas encore mergé sur dev. Je retesterai à mon retour.

**Comment by laurent-laporte-pro** [comment]
Checked in integration server ✅.
