### ISSUE TITLE
[ANT-706] Allow all parameters in endpoint for short-term storage creation

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1730]
## Description

When using the Antares Web API to create short-term storage, there are currently two endpoints available:

- a generic one using commands: POST `/v1/studies/{study_id}/commands`, and
- a specific one (REST endpoint): POST `/studies/{uuid}/areas/{area_id}/storages`.

The generic endpoint using commands allows for the inclusion of various parameters,
including `name`, `group`, `injection_nominal_capacity`, `withdrawal_nominal_capacity`, and others.
However, the specific endpoint only allows the inclusion of `name` and `group` parameters.

## Use Case

Our Script team currently uses the generic endpoint, which relies on commands.
They are in the process of modifying their API access client for Antares Web to use the specific REST endpoints instead.
This transition would be greatly facilitated if the specific endpoint allowed for the inclusion of all parameters.

## Current behavior

The following unit test can reproduce the issue:

```python
area_id = transform_name_to_id("FR")
siemens_battery = "Siemens Battery"
res = client.post(
    f"/v1/studies/{study_id}/areas/{area_id}/storages",
    headers={"Authorization": f"Bearer {user_access_token}"},
    json={"name": siemens_battery, "group": "Battery", "injection_nominal_capacity": 0.0,},
)
assert res.status_code == 200, res.json()
```

Running this code raises an 422 error with the following JSON result:

```json
{
  "body": {
    "group": "Battery",
    "injection_nominal_capacity": 0.0,
    "name": "Siemens Battery"
  },
  "description": "extra fields not permitted",
  "exception": "RequestValidationError"
}
```

## Expected Behavior

We expect that the specific endpoint `/studies/{uuid}/areas/{area_id}/storages` will accept and process the same set of
parameters as the generic endpoint.

## Additional Information

- Antares Web API version: 2.15.0

**Comment by laurent-laporte-pro** [comment]
@jacquesaguilera , I opened this ticket following Clément's pertinent remark that there is a difference between the parameters of the `create_st_storage` command and the parameters of the specific endpoint for creating short-term storage.

**Comment by TLAIDI** [comment]
About the new parameters of /studies/{uuid}/areas/{area_id}/storages will be: "parameters": {
                "name": "",
                "group": "",
                "injectionnominalcapacity": ,
                "withdrawalnominalcapacity": ,
                "reservoircapacity": ,
                "efficiency": ,
                "initiallevel": ,
            }
?

**Comment by laurent-laporte-pro** [comment]
> About the new parameters of /studies/{uuid}/areas/{area_id}/storages will be: "parameters": { "name": "", "group": "", "injectionnominalcapacity": , "withdrawalnominalcapacity": , "reservoircapacity": , "efficiency": , "initiallevel": , } ?

Actuellement, l’endpoint de création `create_st_storage` prend deux paramètres obligatoires :

- `name` : Nom du stockage.
- `group` : Groupe du système de stockage d’énergie.

La demande concerne une évolution pour avoir les paramètres optionnels suivants :

- `injection_nominal_capacity` : Capacité nominale d’injection (MW)
- `withdrawal_nominal_capacity` : Capacité nominale de soutirage (MW)
- `reservoir_capacity` : Capacité du réservoir (MWh)
- `efficiency` : Efficacité du système de stockage
- `initial_level` : Niveau initial du système de stockage
- `initial_level_optim` : Flag indiquant si le niveau initial est optimisé ou pas

Du point de vue de l’implémentation, cela signifierait simplement qu'il faut utiliser la classe `StorageInput` au lieu
de la classe `StorageCreation` (à la fin, la classe `StorageCreation` devrait disparaître).

Bien sûr, comme tous les champs de la classe `StorageInput` sont optionnels, nous aurons besoin d’ajouter une
vérification supplémentaire pour s’assurer que le paramètre "name" est bien renseigné (autre que `None`). Cela peut être
fait directement dans la méthode `STStorageManager.create_storage`, mais si tu peux trouver une meilleure
implémentation, j'en serais ravis.

Dans l’implémentation actuelle, il y a une petite erreur dans la classe `StorageCreation`, car le paramètre `group` est
en fait un paramètre qui devrait être optionnel : sa valeur par défaut est `STStorageGroup.OTHER1`. Il faudrait donc
corriger cela dans la classe `StorageInput`.
