### ISSUE TITLE
[ANT-849] Change restrictions on POST v1/tasks API

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1732]
## Description
The AntaresWeb API POST request “v1/tasks” required being admin to be executed correctly (and return results). In our opinion, this query is the only one allowing us to know if the unzipping tasks are still in progress or finished after running a simulation. This is important information when scripting calculation sequences.
 
If there is no logical reason to have to be an admin, can this restriction be lifted?

🚨 Attention: The bug fix of this issue cannot be addressed immediately as it depends on the feature #1124 that introduces a breaking change at the database level. A database schema migration is required to proceed. Please note that this fix will be scheduled for release v2.16, rather than v2.15.5.

**Comment by sylvlecl** [comment]
Note that it does not seem to make sense that this is a **POST** request, it should be a **GET**.
However, this should not be deleted for compatibility reasons (API stability).

**Comment by makdeuneuv** [comment]
Not fixed.

**Comment by makdeuneuv** [comment]
Test OK on API doc and REST Client.
