### ISSUE TITLE
Failed to display JSON file outputs in Debug view 

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/AntaREST#1744]
## Description

JSON files produced by Xpansion in its output directory are not displayed in the Modelisation > Debug view.
### Steps to reproduce the behavior:
1. Open an Xpansion study
2. Go to the Modelisation > Debug tab
3. Try to display the file `output/<my-output>/lp/options.json` or `output/<my-output>/lp/launcher_options.json`

## Actual Behavior
We observe the error `TypeError: r.join is not a function`.

## Expected Behavior
The JSON file should be correctly displayed.

## Screenshots
![Capture d’écran du 2023-09-27 10-31-02](https://github.com/AntaresSimulatorTeam/AntaREST/assets/10436551/a1016b11-eafa-4ef0-bbeb-1dba2f3bfe5c)

## Environment

- [ ] Production (the issue does not occur in production)
- [x] Staging

**Comment by laurent-laporte-pro** [comment]
When the user clicks on a file in the Debug view, we should display the file's content.

In the case of a JSON file, we have the anomaly reported by the user.

This anomaly is specific to the JSON format; there are no issues with other formats.

The error occurs when reviewing the outputs and does not occur in the input configuration files.

We have a specific handling for the JSON format that should be removed as it appears to be a wart existing on both the back office and front end sides.
