### ISSUE TITLE
Unable to launch simulations with more than 24 cpus with the API on the staging environment

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/AntaREST#1745]
## Description
I launch simulations on AntaresWeb using the Python API. When requesting strictly more than 24 CPUs (on the staging environment on which we should be able to request up to 36), the run seems to be executed with only 12 CPUs.

### Steps to reproduce the behavior:
1. Launch a simulation on the staging environment using the Python API to set the number of CPUs
2. Choose a number of CPUs between 25 and 36
## Actual Behavior
When requesting up to 24 CPUs, the behavior is normal as the correct number of CPUs are allocated for the run. However, when requesting more than 24, the job only gets 12 CPUs.

## Expected Behavior
As the staging environment has 36 cores per node, we expect to be able to launch runs with up to 36 CPUs with the API.

## Screenshots
The following files are generated by Xpansion and simply consist in gathering its input arguments (i.e. the input arguments passed to `antares-xpansion-launcher`).
An example of a run where we expect 24 CPUs : 
```json
{
    "method": "benders_by_batch",
    "n_mpi": 24,
    "antares_n_cpu": 24,
    "keep_mps": false,
    "oversubscribe": true,
    "allow_run_as_root": false
}
```

An example of a run where we expect 25 CPUs : 
```json
{
    "method": "benders_by_batch",
    "n_mpi": 12,
    "antares_n_cpu": 12,
    "keep_mps": false,
    "oversubscribe": true,
    "allow_run_as_root": false
}
```
## Environment

- [ ] Production (not applicable)
- [x] Staging

**Comment by tbittar** [comment]
This issue applies to Xpansion runs, I do not know if it is also applicable for Antares-Simulator runs.

**Comment by MartinBelthle** [comment]
The linked PR laid the foundation stone but the max number of cores is not yet dynamically calculated on SLURM environment.
Therefore, this issue is not completed yet.
