### ISSUE TITLE
[ANT-667] Failure to update matrix upon changing frequency in binding constraint

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1760]
## Description

When the user changes the frequency of a binding constraint (for example, switching from "weekly" to "daily"), the second member of the binding constraint (i.e., the matrix) should be reset and set to zero to account for the frequency change (e.g., transitioning from a 52-row matrix to a 365-row matrix).

- Firstly, the front-end display is not updated; if we were on "weekly" and switch to "daily," we still see the old labels corresponding to the weeks.
- Secondly, on the back-office side (using the Debug view), it's observed that the old matrix is retained.

### Steps to reproduce the behavior:

1. Open a study.
2. Select the "MODELING" tab.
3. Choose the "BINDING CONSTRAINTS" tab.
4. Click on the "+" icon at the bottom left of the list of binding constraints to create a new one.
5. Fill out the creation form and validate it.
6. The new binding constraint is created. Click on the "Matrix" tab to view the matrix of the second member of the binding constraint.
7. Modify the frequency of the binding constraint.

## Actual Behavior

When modifying the frequency of the binding constraint, the matrix is not refreshed and remains unchanged.

## Expected Behavior

When changing the frequency of the binding constraint, a new matrix should be created with 3 zero-filled columns.

## Screenshots

![issue-1383-binding-constraints_weekly](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/b5d841c8-2886-461b-99ea-d572ad15083f)

## Environment

- [x] Production
- [x] Staging

Related to #1383

**Comment by makdeuneuv** [comment]
When we create a new binding constraint, no matrix is created.  We need to import it. But when we change the frequency of a binding constraint which have an existing matrix, we need to change tab and come back to see the change. I think it's the refresh which missing.

**Comment by laurent-laporte-pro** [comment]
I'm currently fixing the issue regarding the binding constraint creation.
