### ISSUE TITLE
No display of year-by-year output data for thermal

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1777]
## Description
Study 11d758c0-a9c3-4950-ae30-6b88c910af06 in production is configured to return annual year-by-year results. The results are present in the output files when downloaded to disk (for example details-annual.txtx file in economy\mc-ind\00001\areas\at00). But in the HMI view, nothing is displayed.

**API** call (404 error)
**Request** URL:
https://antares-web.rte-france.com/api/v1/studies/11d758c0-a9c3-4950-ae30-6b88c910af06/raw?path=output%2F20231018-1421eco%2Feconomy%2Fmc-ind%2F00700%2Fareas%2Fat00%2Fvalues-annual&depth=1
**Request** method:
GET
**Status** code:
404 Not Found
**Answer** :
{"description":"'00700' not a child of OutputSimulationModeMcInd","exception":"ChildNotFoundError"}

**First analysis:**
For this study, there are 35 years and in the results form the year number dropdown list is not updated with this information. Furthermore in the API call it is the year 00700 which is sought even though it does not exist. And it is difficult to update the year number dropdown in this form.

### Steps to reproduce the behavior:
1. Take a study with thermal cluster
2. Modify the output filter year-by-year for all areas to annual
3. Run a simulation 
4. Go see the result year-by-year  and you will go the message "No data found", but the data still present

## Expected Behavior
- Send the correct ai request (with the correct year number) and show the results
- update the year number drop-down list according to the result (or the playlist played)
- allow you to directly modify the year number drop-down list (reset to null then add the desired year number)
- Provide a clear and concise description of the issue.
- Describe what you expected to happen.

## Screenshots
![erreur affichage sortie year by year](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/36284cbb-bb29-4860-83d1-822747f2263a)
![erreur affichage sortie year by year2](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/4757dff5-fefc-410e-8b88-8d3f832b5722)

## Environment
- [x] Production
- [x] Staging

**Comment by MartinBelthle** [comment]
Indeed, the year 700 does not exist (the playlist contains only the 35th first years) therefore the output cannot be found. The issue seems to be a front-end one. From what I've seen, the button to choose which year you want to see is completely bugged even on staging environment.
Example of bug I faced on staging environment : study with 4 MC years, whatever the value i chose to see in the results view, the API call raised concerned the 4th year :disappointed:
