### ISSUE TITLE
[ANT-864] Setup of Vite

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1799]
Installation and configuration of [Vite](https://vitejs.dev/) instead of [Create React App](https://create-react-app.dev/) (deprecated).

**Comment by makdeuneuv** [comment]
Will be done during sprint 25 (actually in progress for 3 weeks).

**Comment by makdeuneuv** [comment]
Done on v2.16.4, it's deployed on production.
