### ISSUE TITLE
[ANT-882] Regression on the management of empty matrices

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1802]
## Description

After updating the thermal clusters form, exceptions are thrown when we want to consult clusters which have an empty matrix.
The error doesn't occur in production, because this new dev is not present there (see screenshots).

This problem must be urgently corrected before the new forms for thermal clusters go into production.

## Steps to Reproduce
Take a study which have a thermal cluster with empty matrix and go see this cluster
Example in recette : c6aeeeed-956e-4139-8bc1-7c8668cfc246

## Screenshots

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/9e1e4720-1b3d-4455-820e-63e918aae8e0)

## Environment

- [x] Staging

**Comment by MartinBelthle** [comment]
I tried to reproduce it on local environment with the same study and the same AntaREST commit and i couldn't. 
I also deployed the same AntaREST commit on integration envrionment and there was no issue with the study :disappointed:

**Comment by MartinBelthle** [comment]
The issue also occurs with prepro data which are not empty matrices.   
So I think there is no correlation between the empty matrix and the issue encountered.
Furthermore, other clusters in the same area have empty matrices (example : `at_gas pcomp mid`) and there are no issue with this cluster.

**Comment by laurent-laporte-pro** [comment]
You should receive a 404 error only if the requested file does not exist, not if it is empty.

@MartinBelthle, you may have used a study with empty matrices, not missing files…

@laurent-laporte-pro  i used the exact same study, the one deuneuv mentioned. In this study there are no missing files.

**Comment by laurent-laporte-pro** [comment]
@makdeuneuv Est-ce un bug front ou back => mettre à jour les tags de ce ticket et attribuer la bonne personne.

**Comment by makdeuneuv** [comment]
@laurent-laporte-pro  c'est un bug back et j'ai notifié Hatim du sujet. Je vérifierai après la MEP si le bug se produit aussi en prod.

**Comment by MartinBelthle** [comment]
Je fais un résumé ici de ce que j'ai vu en recette sur une étude raw et managée: 
1) Je crée un cluster thermique avec le endpoint `POST /commands` avec la commande `create_cluster`. Mon cluster a donc une matrice vide dans l'onglet `Series`
2) J'essaie de récupérer la matrice liée au cluster : Avec le endpoint `GET /raw` et le path de la matrice.
    - Si je renseigne `formatted=False`, je reçois un string vide : `""`.
    - Si je renseigne `formatted=True`, je reçois cela : ```{ "data": [[]], "index": [0], "columns": [] }```
3) J'update la matrice avec le endpoint  `POST /commands` avec la commande `create_cluster`, cela fonctionne bien

**Comment by makdeuneuv** [comment]
Thanks for your returns Martin.
This specific bug no longer occurs, in _recette_ or in _production_.
Regarding JIRA issue ANT-882, this is unrelated.
This is a bug for antares R scripts team, this will be mentioned in the Jira issue.
So I'm closing this issue.
