### ISSUE TITLE
Implementing Collapsible and Extensible Areas Menu

### ISSUE THREAD

**Issue by hdinia** [AntaresSimulatorTeam/AntaREST#1823]
### Description:

Request to add a new feature that introduces a collapsible and extensible menu into our application. This feature aims to enhance user experience by providing a more organized and space-efficient navigation interface.

### Feature Details

1. Collapsible Menu:
The areas side menu should be able to collapse, ideally with minimal text, to maximize screen real estate. This is particularly useful for users working on smaller screens or those who prefer a cleaner workspace.

2. Resizable Divider:
Implement a draggable horizontal divider that allows users to resize the areas menu and the rest of the view.
The divider should be easy to grab and drag, with a noticeable and accessible design.

### Screenshot
![side-menu](https://github.com/AntaresSimulatorTeam/AntaREST/assets/33469289/e1cdb0d1-fafc-42e3-a59e-cf6a3e363a16)

- Extensibility:
The menu should be able to expand to show full areas text. This expansion can be triggered by user actions like hover or click.

- User Preference Memory:
The system should remember the user's last preference (collapsed or extended) and maintain this state across sessions.

Despite the collapsible nature, the menu should remain intuitive and easy to navigate, with clear indications of expand/collapse actions.

- Integration with Existing UI:
The new menu design should integrate smoothly with the existing user interface, maintaining the application's overall look and feel.

**Comment by laurent-laporte-pro** [comment]
In the paragraph on "User Preference Memory": we not only recorded the "expanded"/"collapsed" status but also need to store the menu's width.

**Comment by laurent-laporte-pro** [comment]
What about long area names: should we truncate, word-wrap or use a slider?

**Comment by hdinia** [comment]
> In the paragraph on "User Preference Memory": we not only recorded the "expanded"/"collapsed" status but also need to store the menu's width.

True we also need to remember the width for the horizontal divider resize feature.
But not sure we will implement a persistence across sessions(local storage), maybe a persistence across the current session only is enough (like for the main collapsible menu)
