### ISSUE TITLE
Impossible to unarchive a study

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1829]
## Description
When I try to unarchive a study I get this error : 
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/46c0e9d6-d571-40cd-a23f-03218980a48a)

## Additional Information
ID study on recette : 3a636969-d8b1-4383-9b4a-ca3d01adba84

**Comment by MartinBelthle** [comment]
I downloaded the zip and it's a bit weird, it contains no information on area `at` in `thermal/clusters` nor in `thermal/prepro` but it does in `thermal/series` :thinking: . So it's normal that the unzipping task fails. @makdeuneuv who did report this bug to you, or do you know who owns this study?

**Comment by makdeuneuv** [comment]
No body reports this issue for the moment. It's related to this PR #1871
