### ISSUE TITLE
Add verification for fields in thermals, renewables and storages

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1838]
Update thermals, renewables and storages forms: add verification on fields with the specs from the back-end.

**Comment by hdinia** [comment]
TODO:
- [x] Get validation rules from the API code or specs
- [x] Update Thermal form fields
- [x] Update Renewable form fields
- [x] Update Storage from fields
- [x] Test all validation rules works as expected 

### Storage form missing validation rules:
- `initial_level` min: 0 max: 1
- `efficiency` min: 0 max: 1 default: 1 
- `withdrawal_nominal_capacity` min: 0
- `injection_nominal_capacity` min: 0
- `reservoir_capacity` min: 0


### Thermal form missing validation rules:
- `unit_count` min: 1
- `nominal_capacity` min: 0
- `min_up_time` min: 0 max: 168 default: 1
- `min_down_time` min: 0 max: 168 default: 1
- `spinning` min: 0 max: 1
- `volatility_forced` min: 0 max: 1
- `volatility_planned` min: 0 max: 1

### Renewable form missing validation rules:
- `unit_count` min: 1
- `nominal_capacity` min: 0
