### ISSUE TITLE
Use `min` and `max` from "/v1/launcher/nbcores" in LauncherDialog

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1841]
"/v1/launcher/nbcores" returns `min`, `max` and `defaultValue`.
Currently, only `defaultValue` is used in LauncherDialog.
`min` and `max` from the API call must be used in the field.

If "/v1/launcher/nbcores" call fails, the field will be disabled, and it will be impossible to launch the study. 

![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/1954121/4cbe4e00-2da7-4e7c-8b98-c2345b8f2607)

**Comment by laurent-laporte-pro** [comment]
C'est OK pour moi. De plus, lorsqu'on lance une simulation, on voit bien le nombre de cœurs sélectionné :

Par exemple, avec la valeur par défaut en recette = 34, on a bien la commande suivante :

```shell
srun antares-solver --force-parallel=34 -i /scratch/antares_126229/8fa4e025-b376-49d2-8858-8ba2abfc537a
```
Si on choisit 7 cœurs, on a bien :

```shell
srun antares-solver --force-parallel=7 -i /scratch/antares_126230/bed4d2de-ea57-45c8-88f4-3f479fb825d5
```
