### ISSUE TITLE
[ANT-667] Binding constraint matrices length is wrong and makes the solver crash

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1843]
## Describe the problem

Creating binding constraints via the interface seems to create wrong matrices.
This cause the solver to fail.

## Steps to Reproduce

1 - Create a study
2 - Create some binding constraints
3 - See that the matrices do not have the right lengths
4 - Launch the study
5 - See that the solver fails

## Actual Behavior

The matrices lengths:
- Hourly : 8760
- Weekly & Daily : 52

## Expected Behavior

According to Florian, here are the right lengths : 

- Hourly : 8784
- Weekly & Daily : 366

## Environment

- [x] Production
- [x] Staging

## Workaround

Import your own matrices with the right length

## Additional Information

@laurent-laporte-pro, Ali needs this fix to run his study. Because he had a study with empty matrices that he imported on AntaresWeb and now he cannot launch it ... 
He said to me that it would be nice if we can deploy the fix on recette environment as soon as possible.
I let you handle it.

**Comment by laurent-laporte-pro** [comment]
@flomnes, pourrais-tu me préciser les spécifications, car ce n'est pas clair.

Pourquoi a-t-on 8784 heures pour une matrice de contrainte couplante et non pas 8760 ?
Pourquoi la matrice weekly possède 366 lignes et non pas 52 ?
Pourquoi 366 jours et non pas 365 ?

**Comment by laurent-laporte-pro** [comment]
@MartinBelthle, actuellement, les matrices par défaut sont spécifiées dans [binding_constraint/series.py](https://github.com/AntaresSimulatorTeam/AntaREST/blob/e00d58b203023363860cb0e849576e02ed97fd81/antarest/study/storage/variantstudy/business/matrix_constants/binding_constraint/series.py)

Il y a cependant une anomalie dans la classe [`GeneratorMatrixConstants`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/e00d58b203023363860cb0e849576e02ed97fd81/antarest/study/storage/variantstudy/business/matrix_constants_generator.py#L40), car la clef `BINDING_CONSTRAINT_WEEKLY` possède la valeur "empty_2nd_member_daily" au lieu de "empty_2nd_member_weekly`.

Je viens d'ailleurs de constater une anomalie sur la génération des matrices à l'initialisation de la base de données : il crée toutes les matrices mais en supprime une. J'en conclu que l'erreur vient de là.
