### ISSUE TITLE
Modification of the relaxed optimality gap does not yield the correct change in the settings.ini file

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/AntaREST#1864]
## Description

In an Xpansion study, suppose that I want to add or update the value of the setting `Écart d'optimalité (relaxé)`. I do the change in AntaresWeb and save the modification. Then I launch an Xpansion run. It fails because the relaxed optimality gap settings is not correctly written in the `settings.ini` file.

### Steps to reproduce the behavior:
1. Open an Xpansion study.
2. Go to the tab Xpansion > Paramètres
3. Update the value of `Écart d'optimalité (relaxé)` with a positive float and save.
4. Launch an Xpansion run (do not forget to tick Xpansion in the launch window).
## Actual Behavior

The run fails with `check_setting_option_type: Illegal relaxed-optimality-gap option in settings file.`
## Expected Behavior

The study is expected to run normally.
## Screenshots

![Capture d’écran du 2023-12-13 16-51-00](https://github.com/AntaresSimulatorTeam/AntaREST/assets/10436551/f74272b2-c913-4536-9fc2-fccd7be4298c)

## Possible Solution

AntaresWeb writes `relaxed-optimality-gap = <value>` in the `settings.ini` file whereas`relaxed_optimality_gap = <value>`is expected. 
## Environment

- [x] Production
- [x] Staging

**Comment by MartinBelthle** [comment]
Just to add some information to understand the context:

The parameter `Écart d'optimalité (relaxé)` has 2 possible values:
- `relaxed-optimality-gap` for the R version (which we do not support anymore)
- `relaxed_optimality_gap` for the C++ version (which we want to support)

So what's need to be done is to replace `-` by `_` in the code without having to care about retro-compatibility
