### ISSUE TITLE
Adding terms in binding constraints doesn't work

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1884]
## Description

Provide a clear and concise description of the issue.
## Steps to Reproduce
1. Open a study (version 8.6)
2. Add a binding constraint
3. Add a term in the binding constraint. 
# Actual Behavior
- If the constraint is of type "thermal", we get the following error message 
> Cluster 'pologne.Thermique' does not exist in binding constraint 'bc1'
- If it is of "link" type, the user cannot select the areas that define the term (not in the list)
Describe what actually happened.
## Expected Behavior
The user should ba able to add terms to a binding constraint

Describe what you expected to happen.
## Screenshots
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/26088210/6780bf3d-13c1-4951-aa3e-b911091032a2)

## Possible Solution
Fix bug ?

If you have a solution in mind, describe it here.
## Environment

- [X] Production
- [?] Staging
### Add any other context about the problem here.

- If applicable, provide the study ID that this issue relates to: c6360b7d-5bff-47a3-9d1d-6753c59be5f6
- The date and time when the issue occurred:
- Browser and version: Firefox 121.0
- Operating System: Ubuntu 20.04

**Comment by laurent-laporte-pro** [comment]
## Analyse

Lors de la création du terme de la contrainte couplante, le front-end utilise le endpoint POST `/v1/studies/{study_id}/bindingconstraints/{area_id}/term` avec le body : 

```json
{"data":{"area":"area2","cluster":"Base"},"weight":7}
```

Dans la configuration de l'étude, au niveau du fichier `/input/thermal/clusters/area2/list.ini`, on a : 

```ini
[Base]
group = Nuclear
name = Base
co2 = 0.0
```

➡ L’ identifiant du cluster correspond bien au nom de la section, c'est-à-dire "Base", avec une majuscule.

Le fonction qui implémente ce endpoint est la fonction  [`add_constraint_term`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/abb141ffbd8d6d74b6b4257b322052d6cd6b899a/antarest/study/web/study_data_blueprint.py#L892) située dans `antarest/study/web/study_data_blueprint.py`.

Cette fonction utilise la méthode [`BindingConstraintManager.get_constraint_id`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/abb141ffbd8d6d74b6b4257b322052d6cd6b899a/antarest/study/business/binding_constraint_management.py#L247) pour générer un identifiant de contrainte à partir de l'identifiant de Zone et de l'identifiant du cluster. Dans le cadre de la gestion des contrainte couplantes, l'identifiant doit être en minuscules. Or, cette fonction utilise l'identifiant de cluster sans conversion.

## Solution

La solution consiste à corriger la fonction `get_constraint_id` afin qu'elle calcule des identifiants de contraintes couplantes en minuscules.

D'autre part, la fonction de lecture des contraintes couplantes `BindingConstraintManager.get_binding_constraint` doit aussi être corrigée car, actuellement, elle retourne une liste d'objets `BindingConstraintDTO` comportant des IDs de cluster thermiques en minuscules. En conséquence, le front-end n'est pas en mesure de les afficher correctement ni de contrôler les doublons lors de la création de nouveaux termes.

## Guide de développement

Le calcul des IDs de contrainte couplantes peut être implémenté comme suit, ce qui est beaucoup plus simple que l'actuel fonction statique `get_constraint_id` :

```python
class LinkInfoDTO(BaseModel):
    area1: str
    area2: str

    @property
    def constraint_id(self) -> str:
        area1 = min(self.area1, self.area2)
        area2 = max(self.area1, self.area2)
        return f"{area1}%{area2}"


class ClusterInfoDTO(BaseModel):
    area: str
    cluster: str

    @property
    def constraint_id(self) -> str:
        return f"{self.area}%{self.cluster.lower()}"
```

La fonction `get_binding_constraint` doit récupérer les IDs réels des clusters thermiques afin d'avoir un moyen de retrouver les IDs réels connaissant les IDs en minuscules. Cela peut être réalisé à l'aide du dictionnaire suivant :

```python
# Create an index of thermal clusters for each area.
# This index is used to find the real cluster ID base on its ID in lower case.
thermals_index = {
    area_id: {cl.id.lower(): cl.id for cl in area_obj.thermals}
    for area_id, area_obj in file_study.config.areas.items()
}
```

Une méthode de classe dans le classe `BindingConstraintDTO` doit permettre de créer les objets plus simplement à partir des données lues depuis le fichier INI et de ce dictionnaire `thermals_index`. On pourrait utiliser des regex pour faire le parsing des clefs et des valeurs.

➡ Un refactoring est nécessaire pour avoir un code plus simple et plus "pyrthonnique".

**Comment by flomnes** [comment]
Contournement possible : nommer les zones de sorte que `name == id`, donc minuscules, pas d'espaces, caractères spéciaux. Pas testé
