### ISSUE TITLE
Cannot set decimal values for some properties

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#1916]
Some thermal properties can take decimal values. Most costs (fixed, marked bid, marginal) are encoded as doubles.

However, when the user provides a decimal value, a small popup informs them that only integer values are allowed.

Saving these values reveals that decimal values are indeed accepted.

This is not a blocking issue, but it can be misleading for the user.

I attempted to reproduce this issue twice, but I only encountered the message the first time I tried to input decimal values.

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/26088210/931dce99-4723-4142-a1f6-955c465cf07d)

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/26088210/749e003d-f853-4c21-937e-342a3aa2b0ba)

**Comment by laurent-laporte-pro** [comment]
Pour reproduire l'anomalie :

- Sélectionner, avec la souris, une zone de saisie pouvant recevoir un nombre à virgules,
- Saisir une valeur décimale et presser ENTRÉE avec le clavier

Le message suivant s'affiche :

![issue-1916-thermal-form](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/2b364c02-41c2-4a03-9e04-c3a4473a1271)

La valeur saisie peut néanmoins être validée, mais elle apparaît tronqué dans la configuration :

```ini
[Neon]
group = Nuclear
name = Neon
nominalcapacity = 123.45
fixed-cost = 0.002
startup-cost = 6.26
```

**Comment by laurent-laporte-pro** [comment]
solved
