### ISSUE TITLE
[AntaresWeb] Study notes are not always saved in variants

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/AntaREST#1935]
## Description
When a variant is created from an original study, if the user updates the notes of the variant, the modifications are not always taken into account: the modifications are overwritten by the original notes from the original study.

Provide a clear and concise description of the issue.
## Steps to Reproduce
1. Create a study with notes.
2. Create a variant of this study.
3. Update the notes of the variant and save them: a confirmation message appears.
4. Leave the variant, then re-open it to check the notes.

## Expected behavior
After step 4, the updated notes should appear.

## Current behavior
After step 4, the updates of the notes have not always been saved: they have been replaced by the notes from the original study, even though the confirmation message that the notes have been saved appears in step 3.

**Comment by MartinBelthle** [comment]
When editing comments of a variant, it does not trigger a command.
It's written inside the variant folder next to the snapshot directory inside the `patch.json` file.
This is not a desirable behavior (also because in the long term we want to get rid of the `patch.json` file i believe).
Instead, what's need to be done is the following : Using the endpoint on a variant triggers a command : `update_raw_file` such as : 
```
{
  "action": "update_raw_file",
  "args": {
      "target": "settings/comments",
      "b64Data": the data filled by the user
   }
}
```

**Comment by laurent-laporte-pro** [comment]
Il y a des limitations concernant les variants et je pense que les notes en font partie, car celles-ci ne sont pas enregistrées dans l'historique des commandes. Il en est de même pour la configuration Xpansion.

**Comment by MartinBelthle** [comment]
**How to reproduce 100% of the time:**
- Create a study
- Create a variant of this study.
- Update the notes of the variant and save them: a confirmation message appears.
- Generate the variant using the Generation button (top right button with the flash sign next to it)
- Once the generation is over, refresh the page and do anything you want, the comments disappeared.
