### ISSUE TITLE
[AntaresWeb] Output disappeared

### ISSUE THREAD

**Issue by PPlessiez** [AntaresSimulatorTeam/AntaREST#1936]
## Description
I launched simulations on 3 studies which are variants of the same initial study. All three simulations went well and the results were initially accessible.
When trying to access them several hours later, the results had disappeared: they can't be seen in the "Results" tab or in the debug view. However, they are still downloadable from the "Tasks" view.

The outputs of 2 studies were accessible again several hours later, but they are still invisible for one of the studies.
The size of this study is identical to the size of a study with outputs, suggesting that the outputs are there.

## Steps to Reproduce
Initial study ID: 390e2a89-2abe-4707-bf59-bd1877d8429e
Variant study ID which output has disappeared: 7aa4f373-5e3e-40ff-be02-88c76c160eca
Antares version of the study: V8.0

**Comment by MartinBelthle** [comment]
**How to reproduce :**
-  Create a variant and launch it to obtain an output
- Go on `Results` view and see the output.
- Generate the variant using the Generation button (top right button with the flash sign next to it)
- Once the generation is over, go to the `Results` view and see that there is no more outputs. The same goes for Debug view.

I created a test that reproduces this behavior. The test used to fail and now succeeds.
