### ISSUE TITLE
Selecting "Xpress (>= 8.3)" conflict with "Sensibilité" for Xpansion launch

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/AntaREST#2015]
## Description

Provide a clear and concise description of the issue.
### Steps to reproduce the behavior:
1. Start a new run
2. Select xpansion
3. Select Xpress (>= 8.3)
4. Select sensitivity
5. Select an output
## Actual Behavior

Xpansion run starts but sensitivity option was not taken into account
## Expected Behavior

When selecting "Sensitivité" it should works
## Possible Solution

Probably else/if management in LaunchAntares.sh
## Environment

- [ ] Production
- [ x] Staging
### Add any other context about the problem here.

[7fb9e97f-88fa-4178-a29e-e5a431f20b11](https://antares-web-recette.rte-france.com/studies/7fb9e97f-88fa-4178-a29e-e5a431f20b11)

**Comment by MartinBelthle** [comment]
After analysis, this issue is part of a bigger one. Antares-Launcher and the shell scripts do not support more than one option in other_options.

And here, you provided 2: xpress and xpansion_sensitivity. 
I'm going to create a JIRA ticket to trace the issue and decide how are we gonna handle such cases.

**Comment by laurent-laporte-pro** [comment]
> After analysis, this issue is part of a bigger one. Antares-Launcher and the shell scripts do not support more than one option in `other_options`.

Une précision : dans la classe [`SlurmLauncher`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/cc8a50d0af08c473a6ff6d7b375e19ef48f6567c/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py#L560), on gère bien plusieurs options séparées par un espace.

Dans [Antares-Launcher](https://github.com/AntaresSimulatorTeam/antares-launcher/blob/f11641d4d233d61f91b9cbebf6263780ff14eb88/antareslauncher/remote_environnement/slurm_script_features.py#L45), les options sont transmises à la commande `sbatch` sous la forme d'une unique chaîne de caractères. La commande exécutée doit ressembler à ceci:

```sh
sbatch --partition <partition> ... <solver_script_path> ... "other_option1 other_option2"
```

Or, sur CALIN, les options sont bien récupérée dans le paramètre `$OTHER_OPTIONS` :

```sh
#!/bin/bash
#SBATCH --ntasks=1                      # Number of MPI ranks
#SBATCH --nodes=1                       # Number of nodes
#SBATCH --output=antares-out-%j.txt      # Standard output log
#SBATCH --error=antares-err-%j.txt       # Standard error log
#SBATCH --partition=calin1

INPUT_ZIP_NAME=$1
ANTARES_VERSION=$2
JOB_TYPE=$3
POST_PROCESSING=$4
OTHER_OPTIONS=$5
...
```

Le fonction Shell `has_opt` devrait détecter les options : `"xpansion_sensitivity"`, `"xpress"` et `"zip"`.

**Comment by MartinBelthle** [comment]
Yes but we do not handle it when we give the command line to SLURM, see this code inside `slurm_script_features.py` : 
``` python
args.extend(
            shlex.quote(arg)
            for arg in [
                self.solver_script_path,
                script_params.input_zipfile_name,
                str(script_params.antares_version),
                _job_type,
                str(script_params.post_processing),
                script_params.other_options,
            ]
        )
```

So insted of giving `xpress` we give `"xpress xpansion_sensitivity"` which is not understood by the shell script

**Comment by laurent-laporte-pro** [comment]
This issue concerns the `launchAntares.sh` script which is part of `antares-cd` projet.

@JasonMarechal25 , can you open an issue on Jira or in Rte-s GitLab?
