### ISSUE TITLE
Add metadata on new/existing studies

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#264]
- [ ] a file watcher (https://pypi.org/project/watchdog/) should create new metadata for new directory created which are studies
- [ ] at start the file watcher should check and create metadata for missing registered studies
- [ ] on create/import, new metadata for studies should be inserted
- [ ] on delete, metadata for the study should also be deleted

**Comment by FrancoisJ** [comment]
[login.pptx](https://github.com/AntaresSimulatorTeam/AntaREST/files/6101434/login.pptx)

summerize specification for login and permission

**Comment by FrancoisJ** [comment]
[login.pptx](https://github.com/AntaresSimulatorTeam/AntaREST/files/6108652/login.pptx)
