### ISSUE TITLE
Add Matrix/RawFile Service

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#328]
**Context**
A raw study is made of two parts. A global json and data files. 
Currently the data files are referenced in the json in the form "file/<path_within_the_study>" which is not absolute and can't be resolved without additionnal information (the real local path of the study).

One of the issue caused by this system is the inability to copy a study from the main json alone since we don't have the real path of the referenced data files.

**Spec**
A `DataFileResolverService` should be injected to `StudyConfig` (could be then renamed `StudyContext` to make more sense) to help resolve the data file reference that will now be more specific.
Data file reference should be in the form : `<protocol/datasource>://<unique_resource_path>`
Data file reference could be later used to reference file outside of the local filesystem and provided by other services, the  `DataFileResolverService`  would be configured to understand different datasource.
For now it will be :
`"studyfile://<study_id>/<relative_path_to_study>"`

This entails that we will be able to share data files between different studies using `POST /studies/<path:path>` and applying the data reference of another study. (But this is not recommended now, since there will be no guarantee that the study providing the data file isn't tempered/deleted).
It will however allow the use of the future hypothesis data store which will provide indexed data file accessible with something like:
`"resourcefile://<resource_id>"`

The `DataFileResolverService` should have a method `resolve(uri: str) -> Path` that will return the local filesystem path for any resource (for external data, the data will be downloaded into a temporary path).

As a result the endpoint services `GET /file/<path:path>` and `POST /file/<path:path>`  should be changed to use `DataFileResolverService` instead of the study storage service. The `path` will then be an DataFile `uri` as defined before which path will be resolved for the new upload datafile (or to retrieve the datafile content).

**Comment by FrancoisJ** [comment]
[LazyNode.pptx](https://github.com/AntaresSimulatorTeam/AntaREST/files/6695241/LazyNode.pptx)
