### ISSUE TITLE
Add file based matrix store API

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#330]
A new API to store shareable matrix.

A matrix is a file + metadata.
The file is a tsv without headers containing float values.
The metadata comprises an id, name, type (hourly, daily, ...), tags, creation date, modification date, owner, groups, and the file path reference.
Note that the matrix will evolve to have another backend instead of the file system, so the file path reference is temporary and may be replaced by a uri (toward a resource in a timeseries database) in the future.

A new filesystem directory should be configured to host the data files.

Endpoints will be : 
- matrix creation : POST /matrixlib (body: multipart file + metadata)
- matrix listing : GET /matrixlib (query args: filters by field in metadata) -> list of metadatas
- matrix deletion : DELETE /matrixlib/<id_matrix>
- matrix fetching : GET /matrixlib/<id_matrix> -> data (in json or tsv format)

**Comment by FrancoisJ** [comment]
Id will be hash of matrix to share matrix seamlessly between studies
