### ISSUE TITLE
Read the study.antares file contained in the simulation

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/AntaREST#38]
as a user who created or run a study
I need to read the content of the `study.antares` file that is at the root of the study directory
in order to check its content, for example the version of Antares with which it has been generated
`study.antares` is standard inifile

### Acceptance criteria

- [x] the content of study.antares can be added to the variables of the study, hence accessed directly

- [x] for example inside study.antares "antares/version": 700 can be found.
I expect to find the version of Antares by requesting "/studyname/antaresversion"

- [x] i expect to find the caption of the simulation by requesting "studyname/caption"

- [x] I expect to find the "created" value of the simulation by requesting "studyname/created" (it is a unixtime, to confirm)

- [x] I expect to find the "lastsave" value of the simulation by requesting "studyname/lastsave" (it is a unixtime, to confirm)

**Comment by qdesmedt** [comment]
@sgatto > Pour le critère:

"I expect to find the version of Antares by requesting "/studyname/antaresversion"

N'est ce pas: /studyname/study.antares/antaresversion ?
