### ISSUE TITLE
Add mode "parsed" for data node (LazyNode)

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#390]
Some data node have a parsing feature (OutputSeriesMatrix and InputSeriesMatrix) which default to enabled. This should not be the case since the /studies/.../raw should be able to send the raw form of the data.
A new param "parsed" should be added to INode.get so that we can control how much the returned data is parsed/transformed.

**Comment by FrancoisJ** [comment]
Not in project scope ;)
