### ISSUE TITLE
Create a new study by copying an existing one

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/AntaREST#83]
As a user, who is in the process of building a new study, but that wants to start from an existing one
I want to create a new simulation by copying an existing study (with all the same values and all the txt files) without the output
in order to later start modifying the parameters of the study and eventually launch the calculation

### Acceptance Criteria

- [x] the request of the creation should accept the `name` of new simulation and the "origin" simulation from which everything should be copied.
- [x] A new study is created with the new `name` becoming the directory name of the new study
- [x] the `name` should be written in the `study.antares` file as the value of the field `caption`
- [x] the Unix Timestamp of the action should be written int field `lastsave` of `study.antares`
- [x] an error should be returned if a simulation with the same name exists already in the workspace
- [x] an error should be returned if the `origin` reference (the presumably existing study) does not exist

**Comment by pl-buiquang** [comment]
The api should be able to handle different studies with same name. A uid generation system should be implemented. (see #105 and #106 ).

**Comment by qdesmedt** [comment]
> The api should be able to handle different studies with same name. A uid generation system should be implemented. (see #105 and #106 ).

A discuter en daily et/ou review de backlog. C'est pas réellement iso-fonctionnel avec Antares. Cette implémentation demandrait l'installation d'un cache ou d'une base de donnée.

@pl-buiquang : peux tu créer une petite issue même temporaire à ce sujet ? Je n'integrerais pas ce développement dans cette issue. J'ai peur que quand je la fermerais nous perdions ta remarque. Merci !

**Comment by pl-buiquang** [comment]
@qdesmedt les issues sont deja créés (les références sont dans mon commentaire)
