### ISSUE TITLE
Can't download results because of missing file

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#928]
### How to reproduce
Try to download **Gaz_elec_2025_avec vu_stock_init_topo_uae/20220529-2022eco export**. Creation of the archive fails with the following error :
```
[Errno 2] No such file or directory: 'economy/mc-ind/00022/links/g-bg-bgt - g-tr/values-hourly.txt'
```
![image](https://user-images.githubusercontent.com/26088210/170963101-3b15a9a6-0de1-491f-a14a-17e844373933.png)

**Comment by pl-buiquang** [comment]
Fixed in https://github.com/AntaresSimulatorTeam/AntaREST/pull/1198/commits/43758919e9d60946a0c83c09d003eba8e6ee9044
