### ISSUE TITLE
[ANT-964] Add user preference pages

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#960]
In the configuration section add a new subsection for user preferences (which should be the first tab).
The title of this page is "Preferences"
It should display (for now):
- the user name
- the language preference (en or fr)

In the backend, user preferences will be stored in the ConfigData table, so a new endpoint to put and retrieve values in this user's key-value store must be added.

**Comment by laurent-laporte-pro** [comment]
The preferences could also store the last used study, but the user interface must also be able to automatically display the edit page for that study.

**Comment by makdeuneuv** [comment]
It wiil be done on Jira
